/*
 * JInternalFrameNeuerKunde.java
 *
 * Created on 23. Mai 2003, 17:39
 */

package net.sourceforge.wisim.controller;

/**
 *
 * @author  Kay Patzwald
 */
public class JInternalFrameNewCustomer extends javax.swing.JInternalFrame {
  
  /** Creates new form JInternalFrameNeuerKunde */
  public JInternalFrameNewCustomer() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jLabel1 = new javax.swing.JLabel();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Neuer Kunde");
    setPreferredSize(new java.awt.Dimension(700, 600));
    jLabel1.setText("Hello World");
    getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

    pack();
  }//GEN-END:initComponents
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
  
}
