/*
 * JInternalFrameViewCustomers.java
 *
 * Created on 25. Mai 2003, 16:31
 */

package net.sourceforge.wisim.controller;

/**
 *
 * @author  Kay Patzwald
 */
public class JInternalFrameViewCustomers extends javax.swing.JInternalFrame {
	
	/** Creates new form JInternalFrameViewCustomers */
	public JInternalFrameViewCustomers() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  private void initComponents() {//GEN-BEGIN:initComponents

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Kunden\u00fcbersicht");
    pack();
  }//GEN-END:initComponents
	
	
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
	
}
