/*
 * JInternalFrameModifyCustomer.java
 *
 * Created on 24. Mai 2003, 08:40
 */

package net.sourceforge.wisim.controller;

/**
 *
 * @author  Kay Patzwald
 */
public class JInternalFrameModifyCustomer extends javax.swing.JInternalFrame
{
	
	/** Creates new form JInternalFrameModifyCustomer */
	public JInternalFrameModifyCustomer()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  private void initComponents() {//GEN-BEGIN:initComponents
    jLabel1 = new javax.swing.JLabel();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Kunde bearbeiten");
    setPreferredSize(new java.awt.Dimension(200, 500));
    jLabel1.setText("Kunde bearbeiten");
    getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

    pack();
  }//GEN-END:initComponents
	
	
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
	
}
