/*   ********************************************************************   **
**   Copyright notice                                                       **
**                                                                          **
**   (c) 2003 WiSim Development Team					                              **
**   http://wisim.sourceforge.net/   			                                  **
**                                                                          **
**   All rights reserved                                                    **
**                                                                          **
**   This script is part of the WiSim Business Game project. The WiSim      **
**   project is free software; you can redistribute it and/or modify        **
**   it under the terms of the GNU General Public License as published by   **
**   the Free Software Foundation; either version 2 of the License, or      **
**   (at your option) any later version.                                    **
**                                                                          **
**   The GNU General Public License can be found at                         **
**   http://www.gnu.org/copyleft/gpl.html.                                  **
**   A copy is found in the textfile GPL.txt and important notices to the   **
**   license from the team is found in the textfile LICENSE.txt distributed **
**   in these package.                                                      **
**                                                                          **
**   This copyright notice MUST APPEAR in all copies of the file!           **
**   ********************************************************************   */

/*
 * JPanelNeuerVertrag.java
 *
 * Created on 10. Februar 2003, 18:43
 */

/**
 *
 * @author  Kay Patzwald und Denise Freitag
 */

package net.sourceforge.wisim.controller;

import java.util.*;
import javax.swing.*;

import net.sourceforge.wisim.dao.*;
import net.sourceforge.wisim.model.*;

/**
 * @author Denise Freitag
 *
 */
public class JPanelNeuerVertrag extends javax.swing.JPanel {

	private WiSimDAO dao;
	private Hashtable kundeObjekt;
	private Hashtable kundenTabelle;
	private Hashtable artikelTabelle;
	private Hashtable artikelObjekt;
	private Vector artikel;
	private float merkeMwSt;
	private double rabattwert;
	private double skontowert;
	private double angebotsPreis;
	private double stueckPreis;
	private double zwischensum1;
	private double zwischensum2;
	private long mengenwert;
	private boolean skontofrist;
	private Validator validate;
        private WiSimMainController wiSimMainController;
	//Logger
	private WiSimLogger wiSimLogger;

	/** Creates new form JPanelNeuerVertrag */
	public JPanelNeuerVertrag(WiSimMainController wiSimMainController) {
		this.wiSimMainController = wiSimMainController;
                initDAO(wiSimMainController);
		kundeObjekt = new Hashtable();
		kundenTabelle = new Hashtable();
		artikelTabelle = new Hashtable();
		artikelObjekt = new Hashtable();
		artikel = new Vector();
		validate = new Validator();
		merkeMwSt = 0;
		rabattwert = 0;
		skontowert = 0;
		mengenwert = 0;
		angebotsPreis = 0;
		zwischensum1 = 0;
		zwischensum2 = 0;
		stueckPreis = 0;
		skontofrist = false;
		initComponents();
	}

	private void initDAO(WiSimMainController wiSimMainController) {
		dao = wiSimMainController.getDAO();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        jOptionAlert = new javax.swing.JOptionPane();
        jOptionPaneConfirm = new javax.swing.JOptionPane();
        jLabelNeuerVertrag = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelKunde = new javax.swing.JLabel();
        jComboBoxKunde = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabelNeuerVertragKundenTyp = new javax.swing.JLabel();
        jTextFieldNeuerVertragKundentyp = new javax.swing.JTextField();
        jLabelNeuerVertragAnsprueche = new javax.swing.JLabel();
        jTextFieldNeuerVertragAnsprueche = new javax.swing.JTextField();
        jLabelNeuerVertragZahlungsmoral = new javax.swing.JLabel();
        jTextFieldNeuerVertragZahlungsmoral = new javax.swing.JTextField();
        jLabelNeuerVertragAnzahlVertraege = new javax.swing.JLabel();
        jTextFieldNeuerVertragAnzahlVertraege = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelArtikel = new javax.swing.JLabel();
        jComboBoxArtikel = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabelStueckpreis = new javax.swing.JLabel();
        jTextFieldNeuerVertragStueckpreis = new javax.swing.JTextField();
        jLabelEUR2 = new javax.swing.JLabel();
        jLabelMwst = new javax.swing.JLabel();
        jTextFieldMwst = new javax.swing.JTextField();
        jLabelProzent = new javax.swing.JLabel();
        jLabelNeuerVertragAbnahmemenge = new javax.swing.JLabel();
        jTextFieldAbnahmemenge = new javax.swing.JTextField();
        jLabelZwischensumme1 = new javax.swing.JLabel();
        jTextFieldNeuerVertragZwischensumme1 = new javax.swing.JTextField();
        jLabelEUR1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabelNeuerVertragLieferdatum = new javax.swing.JLabel();
        jTextFieldNeuerVertragTag = new javax.swing.JTextField();
        jTextFieldNeuerVertragMonat = new javax.swing.JTextField();
        jTextFieldNeuerVertragJahr = new javax.swing.JTextField();
        jLabelRabatt = new javax.swing.JLabel();
        jTextFieldRabatt = new javax.swing.JTextField();
        jLabelSkonto = new javax.swing.JLabel();
        jTextFieldSkonto = new javax.swing.JTextField();
        jLabelNeuerVertragNettozahldatum = new javax.swing.JLabel();
        jLabelProzent2 = new javax.swing.JLabel();
        jLabelSkontofrist = new javax.swing.JLabel();
        jTextFieldSkontofristTage = new javax.swing.JTextField();
        jLabelTage = new javax.swing.JLabel();
        jLabelProzent1 = new javax.swing.JLabel();
        jTextFieldNeuerVertragNettozahldatum = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldZwischensumme2 = new javax.swing.JTextField();
        jLabelZwischensumme2 = new javax.swing.JLabel();
        jLabelEUR3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelAngebotspreis = new javax.swing.JLabel();
        jTextFieldNeuerVertragAngebotspreis = new javax.swing.JTextField();
        jLabelEUR = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonNeuerVertragAbbrechen = new javax.swing.JButton();
        jButtonNeuerVertragSpeichern = new javax.swing.JButton();

        jOptionAlert.setMessageType(0);
        jOptionPaneConfirm.setMessageType(0);

        setLayout(null);

        jLabelNeuerVertrag.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabelNeuerVertrag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNeuerVertrag.setText("Neuer Vertrag");
        add(jLabelNeuerVertrag);
        jLabelNeuerVertrag.setBounds(0, 0, 810, 40);

        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.TitledBorder("1. Kunden ausw\u00e4hlen"));
        jLabelKunde.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelKunde.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelKunde.setText("Kunde");
        jPanel1.add(jLabelKunde);
        jLabelKunde.setBounds(40, 30, 80, 19);

        jComboBoxKunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKundeActionPerformed(evt);
            }
        });
        jComboBoxKunde.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBoxKundeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.add(jComboBoxKunde);
        jComboBoxKunde.setBounds(170, 30, 170, 20);

        jPanel2.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.TitledBorder(null, "Kundendaten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jLabelNeuerVertragKundenTyp.setText("Kundentyp");
        jPanel2.add(jLabelNeuerVertragKundenTyp);
        jLabelNeuerVertragKundenTyp.setBounds(20, 40, 60, 16);

        jTextFieldNeuerVertragKundentyp.setEditable(false);
        jTextFieldNeuerVertragKundentyp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFieldNeuerVertragKundentyp);
        jTextFieldNeuerVertragKundentyp.setBounds(150, 40, 20, 20);

        jLabelNeuerVertragAnsprueche.setText("Anspr\u00fcche");
        jPanel2.add(jLabelNeuerVertragAnsprueche);
        jLabelNeuerVertragAnsprueche.setBounds(20, 70, 62, 16);

        jTextFieldNeuerVertragAnsprueche.setEditable(false);
        jTextFieldNeuerVertragAnsprueche.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFieldNeuerVertragAnsprueche);
        jTextFieldNeuerVertragAnsprueche.setBounds(150, 70, 130, 20);

        jLabelNeuerVertragZahlungsmoral.setText("Zahlungsmoral");
        jPanel2.add(jLabelNeuerVertragZahlungsmoral);
        jLabelNeuerVertragZahlungsmoral.setBounds(20, 100, 90, 16);

        jTextFieldNeuerVertragZahlungsmoral.setEditable(false);
        jTextFieldNeuerVertragZahlungsmoral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFieldNeuerVertragZahlungsmoral);
        jTextFieldNeuerVertragZahlungsmoral.setBounds(150, 100, 20, 20);

        jLabelNeuerVertragAnzahlVertraege.setText("weitere Vertr\u00e4ge");
        jPanel2.add(jLabelNeuerVertragAnzahlVertraege);
        jLabelNeuerVertragAnzahlVertraege.setBounds(20, 130, 100, 16);

        jTextFieldNeuerVertragAnzahlVertraege.setEditable(false);
        jTextFieldNeuerVertragAnzahlVertraege.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFieldNeuerVertragAnzahlVertraege);
        jTextFieldNeuerVertragAnzahlVertraege.setBounds(150, 130, 20, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 60, 310, 160);

        add(jPanel1);
        jPanel1.setBounds(40, 50, 360, 240);

        jPanel3.setLayout(null);

        jPanel3.setBorder(new javax.swing.border.TitledBorder("2. Artikel ausw\u00e4hlen"));
        jLabelArtikel.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelArtikel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelArtikel.setText("Artikel");
        jPanel3.add(jLabelArtikel);
        jLabelArtikel.setBounds(40, 30, 80, 19);

        jComboBoxArtikel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxArtikelActionPerformed(evt);
            }
        });
        jComboBoxArtikel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBoxArtikelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel3.add(jComboBoxArtikel);
        jComboBoxArtikel.setBounds(150, 30, 150, 20);

        jPanel4.setLayout(null);

        jPanel4.setBorder(new javax.swing.border.TitledBorder(null, "Artikeldaten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jLabelStueckpreis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelStueckpreis.setText("St\u00fcckpreis");
        jPanel4.add(jLabelStueckpreis);
        jLabelStueckpreis.setBounds(20, 30, 80, 20);

        jTextFieldNeuerVertragStueckpreis.setEditable(false);
        jTextFieldNeuerVertragStueckpreis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(jTextFieldNeuerVertragStueckpreis);
        jTextFieldNeuerVertragStueckpreis.setBounds(150, 30, 80, 20);

        jLabelEUR2.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabelEUR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEUR2.setText("\u20ac");
        jPanel4.add(jLabelEUR2);
        jLabelEUR2.setBounds(240, 30, 10, 20);

        jLabelMwst.setText("MwSt");
        jPanel4.add(jLabelMwst);
        jLabelMwst.setBounds(20, 60, 60, 20);

        jTextFieldMwst.setEditable(false);
        jTextFieldMwst.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(jTextFieldMwst);
        jTextFieldMwst.setBounds(180, 60, 50, 20);

        jLabelProzent.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelProzent.setText("%");
        jPanel4.add(jLabelProzent);
        jLabelProzent.setBounds(240, 60, 10, 19);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(30, 60, 270, 100);

        jLabelNeuerVertragAbnahmemenge.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelNeuerVertragAbnahmemenge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNeuerVertragAbnahmemenge.setText("Abnahmemenge");
        jPanel3.add(jLabelNeuerVertragAbnahmemenge);
        jLabelNeuerVertragAbnahmemenge.setBounds(30, 170, 120, 16);

        jTextFieldAbnahmemenge.setDocument(new JTextFieldValidation(10));
        jTextFieldAbnahmemenge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAbnahmemenge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAbnahmemengeFocusLost(evt);
            }
        });

        jPanel3.add(jTextFieldAbnahmemenge);
        jTextFieldAbnahmemenge.setBounds(180, 170, 120, 20);

        jLabelZwischensumme1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelZwischensumme1.setText("Zwischensumme 1");
        jPanel3.add(jLabelZwischensumme1);
        jLabelZwischensumme1.setBounds(30, 210, 120, 16);

        jTextFieldNeuerVertragZwischensumme1.setEditable(false);
        jTextFieldNeuerVertragZwischensumme1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(jTextFieldNeuerVertragZwischensumme1);
        jTextFieldNeuerVertragZwischensumme1.setBounds(180, 210, 120, 20);

        jLabelEUR1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabelEUR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEUR1.setText("\u20ac");
        jPanel3.add(jLabelEUR1);
        jLabelEUR1.setBounds(310, 210, 10, 20);

        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(30, 200, 290, 10);

        add(jPanel3);
        jPanel3.setBounds(410, 50, 340, 240);

        jPanel5.setLayout(null);

        jPanel5.setBorder(new javax.swing.border.TitledBorder("3. Bestelldaten eingeben"));
        jLabelNeuerVertragLieferdatum.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelNeuerVertragLieferdatum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNeuerVertragLieferdatum.setText("Lieferdatum");
        jPanel5.add(jLabelNeuerVertragLieferdatum);
        jLabelNeuerVertragLieferdatum.setBounds(40, 30, 90, 19);

        jTextFieldNeuerVertragTag.setDocument(new JTextFieldValidation(2));
        jTextFieldNeuerVertragTag.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNeuerVertragTag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNeuerVertragTagFocusLost(evt);
            }
        });

        jPanel5.add(jTextFieldNeuerVertragTag);
        jTextFieldNeuerVertragTag.setBounds(180, 30, 30, 20);

        jTextFieldNeuerVertragMonat.setDocument(new JTextFieldValidation(2));
        jTextFieldNeuerVertragMonat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNeuerVertragMonat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNeuerVertragMonatFocusLost(evt);
            }
        });

        jPanel5.add(jTextFieldNeuerVertragMonat);
        jTextFieldNeuerVertragMonat.setBounds(210, 30, 30, 20);

        jTextFieldNeuerVertragJahr.setDocument(new JTextFieldValidation(4));
        jTextFieldNeuerVertragJahr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNeuerVertragJahr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNeuerVertragJahrFocusLost(evt);
            }
        });

        jPanel5.add(jTextFieldNeuerVertragJahr);
        jTextFieldNeuerVertragJahr.setBounds(240, 30, 50, 20);

        jLabelRabatt.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelRabatt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRabatt.setText("Rabatt");
        jPanel5.add(jLabelRabatt);
        jLabelRabatt.setBounds(40, 60, 50, 20);

        jTextFieldRabatt.setDocument(new JTextFieldValidation(5));
        jTextFieldRabatt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRabatt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRabattFocusLost(evt);
            }
        });

        jPanel5.add(jTextFieldRabatt);
        jTextFieldRabatt.setBounds(180, 60, 40, 20);

        jLabelSkonto.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelSkonto.setText("Skonto");
        jPanel5.add(jLabelSkonto);
        jLabelSkonto.setBounds(40, 90, 60, 16);

        jTextFieldSkonto.setDocument(new JTextFieldValidation(5));
        jTextFieldSkonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSkonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSkontoFocusLost(evt);
            }
        });

        jPanel5.add(jTextFieldSkonto);
        jTextFieldSkonto.setBounds(180, 90, 40, 20);

        jLabelNeuerVertragNettozahldatum.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelNeuerVertragNettozahldatum.setText("Nettozahldatum");
        jPanel5.add(jLabelNeuerVertragNettozahldatum);
        jLabelNeuerVertragNettozahldatum.setBounds(40, 150, 110, 19);

        jLabelProzent2.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelProzent2.setText("%");
        jPanel5.add(jLabelProzent2);
        jLabelProzent2.setBounds(230, 90, 10, 19);

        jLabelSkontofrist.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelSkontofrist.setText("Skontofrist");
        jPanel5.add(jLabelSkontofrist);
        jLabelSkontofrist.setBounds(40, 120, 80, 19);

        jTextFieldSkontofristTage.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSkontofristTage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSkontofristTageFocusLost(evt);
            }
        });

        jPanel5.add(jTextFieldSkontofristTage);
        jTextFieldSkontofristTage.setBounds(180, 120, 40, 20);

        jLabelTage.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelTage.setText("Tage");
        jPanel5.add(jLabelTage);
        jLabelTage.setBounds(230, 120, 34, 19);

        jLabelProzent1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelProzent1.setText("%");
        jPanel5.add(jLabelProzent1);
        jLabelProzent1.setBounds(230, 60, 10, 19);

        jTextFieldNeuerVertragNettozahldatum.setEditable(false);
        jTextFieldNeuerVertragNettozahldatum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextFieldNeuerVertragNettozahldatum);
        jTextFieldNeuerVertragNettozahldatum.setBounds(180, 150, 110, 20);

        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(40, 180, 280, 10);

        jTextFieldZwischensumme2.setEditable(false);
        jTextFieldZwischensumme2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(jTextFieldZwischensumme2);
        jTextFieldZwischensumme2.setBounds(180, 190, 120, 20);

        jLabelZwischensumme2.setText("Zwischensumme 2");
        jPanel5.add(jLabelZwischensumme2);
        jLabelZwischensumme2.setBounds(40, 190, 110, 16);

        jLabelEUR3.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabelEUR3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEUR3.setText("\u20ac");
        jPanel5.add(jLabelEUR3);
        jLabelEUR3.setBounds(310, 190, 10, 20);

        add(jPanel5);
        jPanel5.setBounds(40, 310, 360, 220);

        jPanel6.setLayout(null);

        jPanel6.setBorder(new javax.swing.border.TitledBorder("4. Vertrag"));
        jLabelAngebotspreis.setFont(new java.awt.Font("Dialog", 1, 20));
        jLabelAngebotspreis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAngebotspreis.setText("Angebotspreis");
        jPanel6.add(jLabelAngebotspreis);
        jLabelAngebotspreis.setBounds(90, 40, 140, 26);

        jTextFieldNeuerVertragAngebotspreis.setEditable(false);
        jTextFieldNeuerVertragAngebotspreis.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextFieldNeuerVertragAngebotspreis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel6.add(jTextFieldNeuerVertragAngebotspreis);
        jTextFieldNeuerVertragAngebotspreis.setBounds(50, 90, 210, 20);

        jLabelEUR.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabelEUR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEUR.setText("\u20ac");
        jPanel6.add(jLabelEUR);
        jLabelEUR.setBounds(270, 90, 10, 20);

        jPanel6.add(jSeparator3);
        jSeparator3.setBounds(20, 140, 290, 10);

        jButtonNeuerVertragAbbrechen.setFont(new java.awt.Font("Dialog", 1, 11));
        jButtonNeuerVertragAbbrechen.setText("Abbrechen");
        jButtonNeuerVertragAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNeuerVertragAbbrechenActionPerformed(evt);
            }
        });

        jPanel6.add(jButtonNeuerVertragAbbrechen);
        jButtonNeuerVertragAbbrechen.setBounds(190, 170, 120, 25);

        jButtonNeuerVertragSpeichern.setFont(new java.awt.Font("Dialog", 1, 11));
        jButtonNeuerVertragSpeichern.setText("Speichern");
        jButtonNeuerVertragSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNeuerVertragSpeichernActionPerformed(evt);
            }
        });

        jPanel6.add(jButtonNeuerVertragSpeichern);
        jButtonNeuerVertragSpeichern.setBounds(20, 170, 120, 25);

        add(jPanel6);
        jPanel6.setBounds(410, 310, 340, 220);

    }//GEN-END:initComponents
    
	private void jTextFieldSkontofristTageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSkontofristTageFocusLost
		pruefeSkontofrist();
	} //GEN-LAST:event_jTextFieldSkontofristTageFocusLost

	private void jTextFieldNeuerVertragJahrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNeuerVertragJahrFocusLost
		pruefeLieferdatumJahr();
	} //GEN-LAST:event_jTextFieldNeuerVertragJahrFocusLost

	private void jTextFieldNeuerVertragMonatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNeuerVertragMonatFocusLost
		pruefeLieferdatumMonat();
	} //GEN-LAST:event_jTextFieldNeuerVertragMonatFocusLost

	private void jTextFieldNeuerVertragTagFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNeuerVertragTagFocusLost
		pruefeLieferdatumTag();
	} //GEN-LAST:event_jTextFieldNeuerVertragTagFocusLost

	private void jComboBoxKundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKundeActionPerformed
		ladeKundendaten();
	} //GEN-LAST:event_jComboBoxKundeActionPerformed

	private void jTextFieldSkontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSkontoFocusLost
		pruefeSkonto();
	} //GEN-LAST:event_jTextFieldSkontoFocusLost

	private void jTextFieldRabattFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRabattFocusLost
		pruefeRabatt();
	} //GEN-LAST:event_jTextFieldRabattFocusLost

	private void jTextFieldAbnahmemengeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAbnahmemengeFocusLost
		pruefeAbnahmemenge();
	} //GEN-LAST:event_jTextFieldAbnahmemengeFocusLost

	private void jComboBoxArtikelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxArtikelActionPerformed
		ladeStueckpreis();
		ladeMwSt();
	} //GEN-LAST:event_jComboBoxArtikelActionPerformed

	private void jComboBoxArtikelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBoxArtikelAncestorAdded
		ladeArtikel();
	} //GEN-LAST:event_jComboBoxArtikelAncestorAdded

	private void jComboBoxKundeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBoxKundeAncestorAdded
		ladeKunden();
	} //GEN-LAST:event_jComboBoxKundeAncestorAdded

	private void jButtonNeuerVertragAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNeuerVertragAbbrechenActionPerformed
		clearFields();
		ladeKunden();
		ladeArtikel();
	} //GEN-LAST:event_jButtonNeuerVertragAbbrechenActionPerformed

	private void jButtonNeuerVertragSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNeuerVertragSpeichernActionPerformed
		speicherVertrag();
	} //GEN-LAST:event_jButtonNeuerVertragSpeichernActionPerformed

	/**
	 * Method pruefeSkontofrist. Überprüft, ob eine Zahl und das etwas eingegeben wurde.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	public void pruefeSkontofrist() {

		String skontofrist = jTextFieldSkontofristTage.getText();
		boolean skontofristOk = false;
		if (!skontofrist.equals("") && skontofrist != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird die Skontofrist immer wieder überprüft
			while (!skontofristOk && skontofrist != null) {
				//Erlaubt sind nur Eingaben von Zahlen
				if (!validate.checkZahl(skontofrist)) {
					jOptionPaneConfirm.setWantsInput(true);
					skontofrist =
						JOptionPane.showInputDialog(
							this,
							"Ungültige Skontofrist! Bitte neu eingeben:",
							skontofrist);
				} else {
					skontofristOk = true;
				}
			}
			if (skontofrist != null) {
				jTextFieldSkontofristTage.setText(skontofrist);
			} else {
				jTextFieldSkontofristTage.setText("");
			}
		}

		//Das Nettozahldatum wird erzeugt
		if (!jTextFieldSkontofristTage.getText().equals("")
			&& !jTextFieldSkontofristTage.getText().equals("0")) {

			long nettoDatumMili =
				wiSimMainController.getActDate().getTime()
					+ (Long.parseLong(jTextFieldSkontofristTage.getText())
						* 1000
						* 60
						* 60
						* 24);
			GregorianCalendar nettoDatum = new GregorianCalendar();
			nettoDatum.setTimeInMillis(nettoDatumMili);

			String Tag = String.valueOf(nettoDatum.get(Calendar.DATE));
			String Monat = String.valueOf(nettoDatum.get(Calendar.MONTH) + 1);
			String Jahr = String.valueOf(nettoDatum.get(Calendar.YEAR));
			jTextFieldNeuerVertragNettozahldatum.setText(
				Tag + "." + Monat + "." + Jahr);
		} else {
			jTextFieldNeuerVertragNettozahldatum.setText("Keins vorhanden!");
		}
	}

	/**
	 * Method pruefeSkonto. Überprüft, ob ein korrekter Skontowert eingegeben wurde.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	public void pruefeSkonto() {

		String skonto = jTextFieldSkonto.getText();
		
                //Falls Zahl ohne "." eingegeben wurde wird ".0" ergänzt
                if (skonto.matches("^[0-9]{1,2}$")) {
                    skonto = skonto + ".0";
                    jTextFieldSkonto.setText(skonto);
                }
                
                //Falls Zahl mit "," statt "." wird "," mit "." ersetzt
                if (skonto.matches("^[0-9]{1,2}[,][0-9]{1,2}$")) {
                    skonto = skonto.replaceAll(",", ".");
                    jTextFieldSkonto.setText(skonto);
                }
                
                boolean skontoOk = false;

		if (!skonto.equals("") && skonto != null) {

			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird der Skontowert immer wieder geprüft
			while (!skontoOk && skonto != null) {
				/*Erlaubt sind nur Eingaben von 1- oder 2-stellige Zahlen mit 1 Nachkommastelle
				getrennt durch einen Punkt*/

				if (!validate.checkProzent(skonto)) {
					jOptionPaneConfirm.setWantsInput(true);
					skonto =
						JOptionPane.showInputDialog(
							this,
							"Ungültiger Skonto-Wert (Format: x.y)! Bitte neu eingeben:",
							skonto);
                                        
                                        //Falls Zahl ohne "." eingegeben wurde wird ".0" ergänzt
                                        if (skonto != null) {
                                            if (skonto.matches("^[0-9]{1,2}$")) {
                                                skonto = skonto + ".0";
                                                jTextFieldSkonto.setText(skonto);
                                            }
                                            
                                            //Falls Zahl mit "," statt "." wird "," mit "." ersetzt
                                            if (skonto.matches("^[0-9]{1,2}[,][0-9]{1,2}$")) {
                                                skonto = skonto.replaceAll(",", ".");
                                                jTextFieldSkonto.setText(skonto);
                                            }
                                        }
                                        
				} else {
					skontoOk = true;
				}
			}
			if (skonto != null) {
				jTextFieldSkonto.setText(skonto);
				skontowert = Double.parseDouble(skonto);
			} else {
				jTextFieldSkonto.setText("");
				skontowert = 0;
			}

		}
		berechneZwischensumme2();
		berechneAngebotspreis();
	}

	/**
	 * Method pruefeRabatt. Überprüft, ob ein korrekter Rabattwert eingegeben wurde.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	public void pruefeRabatt() {

		String rabatt = jTextFieldRabatt.getText();
		
                //Falls Zahl ohne "." eingegeben wurde wird ".0" ergänzt
                if (rabatt.matches("^[0-9]{1,2}$")) {
                    rabatt = rabatt + ".0";
                    jTextFieldRabatt.setText(rabatt);
                }
                
                //Falls Zahl mit "," statt "." wird "," mit "." ersetzt
                if (rabatt.matches("^[0-9]{1,2}[,][0-9]{1,2}$")) {
                    rabatt = rabatt.replaceAll(",", ".");
                    jTextFieldRabatt.setText(rabatt);
                }
                
                boolean rabattOk = false;

		if (!rabatt.equals("") && rabatt != null) {

			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird der Rabatt immer wieder überprüft
			while (!rabattOk && rabatt != null) {
				/*Erlaubt sind nur Eingaben von 1- oder 2-stellige Zahlen mit 1 Nachkommastelle
				getrennt durch einen Punkt*/

				if (!validate.checkProzent(rabatt)) {
					jOptionPaneConfirm.setWantsInput(true);
					rabatt =
						JOptionPane.showInputDialog(
							this,
							"Ungültiger Rabatt (Format: x.y)! Bitte neu eingeben:",
							rabatt);
                                        
                                        //Falls Zahl ohne "." eingegeben wurde wird ".0" ergänzt
                                        if (rabatt != null) {
                                            if (rabatt.matches("^[0-9]{1,2}$")) {
                                                rabatt = rabatt + ".0";
                                                jTextFieldRabatt.setText(rabatt);
                                            }
                                            
                                            //Falls Zahl mit "," statt "." wird "," mit "." ersetzt
                                            if (rabatt.matches("^[0-9]{1,2}[,][0-9]{1,2}$")) {
                                                rabatt = rabatt.replaceAll(",", ".");
                                                jTextFieldRabatt.setText(rabatt);
                                            }
                                        }
                                        
				} else {
					rabattOk = true;
				}
			}
			if (rabatt != null) {
				jTextFieldRabatt.setText(rabatt);
				rabattwert = Double.parseDouble(rabatt);
			} else {
				jTextFieldRabatt.setText("");
				rabattwert = 0;
			}
		}
		berechneZwischensumme2();
		berechneAngebotspreis();
	}

	/**
	 * Method pruefeLieferdatumTag. Überprüft den eingegebenen Lieferdatumstag.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	public void pruefeLieferdatumTag() {
		String lieferdatum = jTextFieldNeuerVertragTag.getText();
		boolean lieferdatumOk = false;
		if (!lieferdatum.equals("") && lieferdatum != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird das Lieferdatum immer wieder überprüft
			while (!lieferdatumOk && lieferdatum != null) {
				//Erlaubt sind nur Eingaben von 1- oder 2-stellige Zahlen
				if (!validate.checkTwoDigits(lieferdatum)
					|| Integer.parseInt(lieferdatum) > 31) {
					jOptionPaneConfirm.setWantsInput(true);
					lieferdatum =
						JOptionPane.showInputDialog(
							this,
							"Ungültiger Tag! Bitte neu eingeben:",
							lieferdatum);
				} else {
					lieferdatumOk = true;
				}
			}
			if (lieferdatum != null) {
				jTextFieldNeuerVertragTag.setText(lieferdatum);
			} else {
				jTextFieldNeuerVertragTag.setText("");
			}
		}
	}

	/**
	 * Method pruefeLieferdatumMonat. Überprüft den eingegebenen Lieferdatumsmonat.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	public void pruefeLieferdatumMonat() {
		String lieferdatum = jTextFieldNeuerVertragMonat.getText();
		boolean lieferdatumOk = false;
		if (!lieferdatum.equals("") && lieferdatum != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird das Lieferdatum immer wieder überprüft
			while (!lieferdatumOk && lieferdatum != null) {
				//Erlaubt sind nur Eingaben von 1- oder 2-stellige Zahlen || Monatsangabe darf nicht größer 12 sein
				if (!validate.checkTwoDigits(lieferdatum)
					|| Integer.parseInt(lieferdatum) > 12) {
					jOptionPaneConfirm.setWantsInput(true);
					lieferdatum =
						JOptionPane.showInputDialog(
							this,
							"Ungültiger Monat! Bitte neu eingeben:",
							lieferdatum);
				} else {
					lieferdatumOk = true;
				}
			}
			if (lieferdatum != null) {
				jTextFieldNeuerVertragMonat.setText(lieferdatum);
			} else {
				jTextFieldNeuerVertragMonat.setText("");
			}
		}
	}

	/**
	 * Method pruefeLieferdatumJahr. Überprüft das eingegebene Lieferdatumsjahr.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	public void pruefeLieferdatumJahr() {
		String lieferdatum = jTextFieldNeuerVertragJahr.getText();
		boolean lieferdatumOk = false;
		if (!lieferdatum.equals("") && lieferdatum != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird das Lieferdatum immer wieder überprüft
			while (!lieferdatumOk && lieferdatum != null) {
				/*Erlaubt sind nur Eingaben von 4-stelligen Zahlen die nicht mit 0 beginnen*/
				if (!validate.checkYear(lieferdatum)) {
					jOptionPaneConfirm.setWantsInput(true);
					lieferdatum =
						JOptionPane.showInputDialog(
							this,
							"Ungültiges Jahr! Bitte neu eingeben:",
							lieferdatum);
				} else {
					lieferdatumOk = true;
				}
			}
			if (lieferdatum != null) {
				jTextFieldNeuerVertragJahr.setText(lieferdatum);
			} else {
				jTextFieldNeuerVertragJahr.setText("");
			}
		}
	}

	/**
	 * Method pruefeAbnahmemenge. Überprüft die Abnahmemenge.
	 * Wenn der Benutzer etwas falsche eingibt, wird er zur Korrektureingabe
	 * gefordert.
	 */
	public void pruefeAbnahmemenge() {

		angebotsPreis = 0;
		zwischensum1 = 0;
		zwischensum2 = 0;

		String abnahmemenge = jTextFieldAbnahmemenge.getText();
		boolean abnahmemengeOk = false;
		if (!abnahmemenge.equals("") && abnahmemenge != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird die Abnahmemenge immer wieder überprüft
			while (!abnahmemengeOk && abnahmemenge != null) {
				/*Erlaubt sind nur Eingaben von Zahlen und nur 10-stellig*/
				if (!validate.checkZahl(abnahmemenge)) {
					jOptionPaneConfirm.setWantsInput(true);
					abnahmemenge =
						JOptionPane.showInputDialog(
							this,
							"Ungültige Mengenangabe (Format: 1 - 999)! Bitte neu eingeben:",
							abnahmemenge);
				} else {
					abnahmemengeOk = true;
				}
			}
			if (abnahmemenge != null) {
				jTextFieldAbnahmemenge.setText(abnahmemenge);
				mengenwert = Long.parseLong(abnahmemenge);
			} else {
				jTextFieldAbnahmemenge.setText("");
				mengenwert = 0;
			}

		}

		berechneZwischensumme1();
		berechneZwischensumme2();
		berechneAngebotspreis();
	}

	/**
	 * Method berechneZwischensumme2. Berechnet die zweite Zwischensumme.
	 */
	public void berechneZwischensumme2() {

		zwischensum2 = stueckPreis * mengenwert;
		zwischensum2 =
			zwischensum2
				+ (zwischensum2 * merkeMwSt / 100)
				- (zwischensum2 * rabattwert / 100)
				- (zwischensum2 * skontowert / 100);
		jTextFieldZwischensumme2.setText(String.valueOf(zwischensum2));
	}

	/**
	 * Method berechneZwischensumme1. Berechnet die erste Zwischensumme.
	 */
	public void berechneZwischensumme1() {

		zwischensum1 = stueckPreis * mengenwert;
		zwischensum1 = zwischensum1 + (zwischensum1 * merkeMwSt / 100);
		jTextFieldNeuerVertragZwischensumme1.setText(
			String.valueOf(zwischensum1));
	}

	/**
	 * Method berechneAngebotspreis. Berechnet den Angebotspreis.
	 */
	public void berechneAngebotspreis() {

		angebotsPreis = stueckPreis * mengenwert;
		angebotsPreis =
			angebotsPreis
				+ (angebotsPreis * merkeMwSt / 100)
				- (angebotsPreis * rabattwert / 100)
				- (angebotsPreis * skontowert / 100);
		jTextFieldNeuerVertragAngebotspreis.setText(
			String.valueOf(angebotsPreis));
	}

	/**
	 * Method ladeKunden. Lädt alle Kunden aus der Datenbank.
	 */
	private void ladeKunden() {
		Collection kunden = null;
		try {
			kunden = dao.getKunden();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("ladeKunden()", e);
		}

		DefaultComboBoxModel model =
			(DefaultComboBoxModel) jComboBoxKunde.getModel();
		model.removeAllElements();
		model.addElement("Bitte wählen:");

		// Verhindert NullPointerException bei einer leeren Liste
		if (kunden != null) {
			Iterator it = kunden.iterator();
			while (it.hasNext()) {
				Kunde kunde = (Kunde) it.next();
				//Merken des Nachnamen und Vornamen, um diese in die ComboBox einzutragen
				String merkeName =
					String.valueOf(kunde.getVorname()).concat(" ");
				merkeName =
					merkeName.concat(String.valueOf(kunde.getNachname()));
				model.addElement(merkeName);
				kundeObjekt.put(String.valueOf(kunde.getId()), kunde);
				kundenTabelle.put(
					kunde.getNachname(),
					String.valueOf(kunde.getId()));
			}
			jComboBoxKunde.setModel(model);
		}
	}

	/**
	 * Method ladeKundendaten. Lädt den Kundentyp, Zahlungsmoral und Ansprüche
	 * zum ausgewählten Kunden aus der Hashtable kundeObjekt.
	 */
	private void ladeKundendaten() {

		//liefert listItem des selektierten Eintrags
		String listItem = String.valueOf(jComboBoxKunde.getSelectedIndex());

		//sucht das ausgewählte KundenObjekt in Hashtabelle kundeObjekt
		Kunde auswahlKunde = (Kunde) kundeObjekt.get(listItem);

		if (auswahlKunde != null) {

			// sucht vorhandenen Vertraege zum Kunden
			Collection vertraege = null;
			int vertragszaehler = 0;

			try {
				vertraege = dao.getVertraege();
			} catch (WiSimDAOException e) {
				wiSimLogger.log("ladeKundendaten()", e);
			}

			if (vertraege != null) {
				Iterator it = vertraege.iterator();

				while (it.hasNext()) {
					Vertrag vertrag = (Vertrag) it.next();

					if (vertrag.getKundenId() == auswahlKunde.getId()) {
						vertragszaehler++;
					}
				}
			}

			//Gibt aus dem vorher ausgewähltem und dann gespeichertem Kundenobjekt die Daten zu Kundentyp, Zahlungsmoral und Ansprüche aus
			jTextFieldNeuerVertragKundentyp.setText(
				auswahlKunde.getKundentyp());
			jTextFieldNeuerVertragAnsprueche.setText(
				auswahlKunde.getAnspruch());
			jTextFieldNeuerVertragZahlungsmoral.setText(
				auswahlKunde.getZahlungsmoral());
			jTextFieldNeuerVertragAnzahlVertraege.setText(
				String.valueOf(vertragszaehler));
		} else {
			jTextFieldNeuerVertragKundentyp.setText("");
			jTextFieldNeuerVertragAnsprueche.setText("");
			jTextFieldNeuerVertragZahlungsmoral.setText("");
			jTextFieldNeuerVertragAnzahlVertraege.setText("");
		}
	}

	/**
	 * Method ladeArtikel. Lädt die Artikel aus der Datenbank.
	 */
	private void ladeArtikel() {
		Collection artikel = null;
		try {
			artikel = dao.getAlleArtikel();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("ladeArtikel()", e);
		}

		DefaultComboBoxModel model =
			(DefaultComboBoxModel) jComboBoxArtikel.getModel();
		model.removeAllElements();
		model.addElement("Bitte wählen:");

		// Verhindert NullPointerException bei einer leeren Liste
		if (artikel != null) {
			Iterator it = artikel.iterator();
			while (it.hasNext()) {
				Artikel artikel2 = (Artikel) it.next();
				model.addElement(artikel2.getName());
				artikelTabelle.put(
					artikel2.getName(),
					String.valueOf(artikel2.getNr()));
				//speichert das Objekt zum ausgewählten Artikel in die Hashtable artikelObjekt
				artikelObjekt.put(String.valueOf(artikel2.getNr()), artikel2);
			}
			jComboBoxArtikel.setModel(model);
		}
	}

	/**
	 * Method ladeStueckpreis. Lädt von dem ausgewähltem Artikel den Stückpreis aus der Datenbank.
	 */
	private void ladeStueckpreis() {

		//liefert listItem des selektierten Eintrags
		String listItem = String.valueOf(jComboBoxArtikel.getSelectedIndex());

		//sucht das ausgewählte ArtikelObjekt in Hashtabelle artikelObjekt
		Artikel auswahlArtikel = (Artikel) artikelObjekt.get(listItem);

		if (auswahlArtikel != null) {
			//Gibt aus dem vorher ausgewähltem und dann gespeichertem Artikelobjekt den Stückpreis aus
			jTextFieldNeuerVertragStueckpreis.setText(
				String.valueOf(auswahlArtikel.getStueckpreis()));
			stueckPreis =
				Double.parseDouble(
					jTextFieldNeuerVertragStueckpreis.getText().toString());
			jTextFieldMwst.setText(String.valueOf(merkeMwSt));
		} else {
			jTextFieldNeuerVertragStueckpreis.setText("");
			stueckPreis = 0;
			jTextFieldMwst.setText("");
		}

		berechneZwischensumme1();
		berechneZwischensumme2();
		berechneAngebotspreis();

	}

	/**
	 * Method ladeMwSt. Ladet den Wert der Mwst aus der Datenbank.
	 */

	private void ladeMwSt() {
		//MwSt-Satz bestimmen
		float mwst = -1;
		try {
			merkeMwSt = dao.getMwSt();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("ladeMwSt()", e);
		}
	}

	/** Überprüft alle Pflichtfelder auf Inhalt. Gibt eine Fehlemeldung
	   * an den Benutzer, falls ein oder mehrere Felder leer gelassen
	   * wurden.
	   * @return false: Es wurden nicht alle Felder gefüllt.
	   * true: Alle Pflichtfelder sind gefüllt.
	   */
	public boolean ueberpruefenFelder() {
		Collection pflichtfelder = new Vector();

		if (jComboBoxKunde.getSelectedIndex() == 0) {
			pflichtfelder.add("Kunde");
		}

		if (jComboBoxArtikel.getSelectedIndex() == 0) {
			pflichtfelder.add("Artikel");
		}

		if (jTextFieldAbnahmemenge.getText().equals("")) {
			pflichtfelder.add("Abnahmemenge");
		}

		if (jTextFieldRabatt.getText().equals("")) {
			pflichtfelder.add("Rabatt");
		}

		if (jTextFieldSkonto.getText().equals("")) {
			pflichtfelder.add("Skonto");
		}

		if (jTextFieldSkontofristTage.getText().equals("")) {
			pflichtfelder.add("Skontofrist");
		}

		if (jTextFieldNeuerVertragTag.getText().equals("")
			|| jTextFieldNeuerVertragMonat.getText().equals("")
			|| jTextFieldNeuerVertragJahr.getText().equals("")) {
			pflichtfelder.add("Lieferdatum");
		}

		/*Wurde ein oder mehrere Pflichtfelder nicht ausgefüllt erscheint ein JOptionPane, dass dem
		 *Benutzer die fehlenden noch leeren Felder anzeigt*/
		if (!pflichtfelder.isEmpty()) {
			JOptionPane errorPane = new JOptionPane();
			if (pflichtfelder.size() > 1)
				JOptionPane.showMessageDialog(
					this,
					"Folgende Felder müssen ausgefüllt werden: "
						+ pflichtfelder.toString().substring(
							1,
							pflichtfelder.toString().length() - 1),
					"Fehler beim Anlegen des neuen Vertrages",
					JOptionPane.ERROR_MESSAGE);
			else
				JOptionPane.showMessageDialog(
					this,
					"Das folgende Feld muss ausgefüllt werden: "
						+ pflichtfelder.toString().substring(
							1,
							pflichtfelder.toString().length() - 1),
					"Fehler beim Anlegen des neuen Vertrages",
					JOptionPane.ERROR_MESSAGE);

			return false;
		}
		return true;
	}

	/** Überprüft das eingegebene Lieferdatum
	   * @return Gibt das Lieferdatum als GregorianDate zurück. Oder NULL, wenn das
	   * Datum ungültig ist.
	   */
	public GregorianCalendar ueberpruefeLieferdatum() {
		int lieferTag = Integer.parseInt(jTextFieldNeuerVertragTag.getText());
		int lieferMonat =
			Integer.parseInt(jTextFieldNeuerVertragMonat.getText()) - 1;
		int lieferJahr = Integer.parseInt(jTextFieldNeuerVertragJahr.getText());

		GregorianCalendar lieferDatum =
			new GregorianCalendar(lieferJahr, lieferMonat, lieferTag);

		if (lieferTag != lieferDatum.get(Calendar.DATE)) {
			JOptionPane.showMessageDialog(
				this,
				"Ungültiges Lieferdatum!",
				"Fehler",
				0);
			return null;
		}

		if (lieferDatum.getTime().before(wiSimMainController.getActDate())) {
                    JOptionPane.showMessageDialog(this, "Lieferdatum liegt in der Vergangenheit!", "Fehler", 0);
                    return null;
		}
		return lieferDatum;
	}

	/** Löscht alle Felder und setzt alle Werte zurück. */
	public void clearFields() {
		jTextFieldNeuerVertragKundentyp.setText("");
		jTextFieldNeuerVertragAnsprueche.setText("");
		jTextFieldNeuerVertragZahlungsmoral.setText("");
		jTextFieldNeuerVertragAnzahlVertraege.setText("");
		jTextFieldNeuerVertragStueckpreis.setText("");
		jTextFieldAbnahmemenge.setText("");
		jTextFieldMwst.setText("");
		jTextFieldSkonto.setText("");
		jTextFieldSkontofristTage.setText("");
		jTextFieldRabatt.setText("");
		jTextFieldNeuerVertragTag.setText("");
		jTextFieldNeuerVertragMonat.setText("");
		jTextFieldNeuerVertragJahr.setText("");
		jTextFieldNeuerVertragNettozahldatum.setText("");
		jTextFieldZwischensumme2.setText("");
		jTextFieldNeuerVertragZwischensumme1.setText("");
		jTextFieldNeuerVertragAngebotspreis.setText("");

		merkeMwSt = 0;
		rabattwert = 0;
		skontowert = 0;
		mengenwert = 0;
		angebotsPreis = 0;
		stueckPreis = 0;
		boolean Deleted = true;

		jComboBoxArtikel.setSelectedIndex(0);
		jComboBoxKunde.setSelectedIndex(0);
	}

	/**
	 * Method speicherVertrag. Schreibt die Daten in die Datenbank.
	 */
	public void speicherVertrag() {

		int i = 0;
		int j = 0;
		float mwst = 0;

		//Test der Pflichtfelder
		if (ueberpruefenFelder() != true) {
			return;
		}

		//Validierung des Lieferdatums
		GregorianCalendar lieferDatum = ueberpruefeLieferdatum();
		if (lieferDatum == null) {
			return;
		}
		java.sql.Date lieferDateSQL =
			new java.sql.Date(lieferDatum.getTimeInMillis());

		// Id's in Auftragsrechnung und in Auftrag zählen

		Collection vertraege = null;
		Collection atrechnungen = null;

		try {
			vertraege = dao.getVertraege();
			mwst = dao.getMwSt();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}
		// Verhindert NullPointerException bei einer leeren Liste
		if (vertraege != null) {
			Iterator it = vertraege.iterator();
			while (it.hasNext()) {
				Vertrag testVertrag = (Vertrag) it.next();
				i++;
			}
		}

		try {
			atrechnungen = dao.getAuftragsrechnungen();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}

		if (atrechnungen != null) {
			Iterator it = atrechnungen.iterator();
			while (it.hasNext()) {
				Auftragsrechnung testAtr = (Auftragsrechnung) it.next();
				j++;
			}
		}

		//liefert listItem des selektierten Eintrags aus der ComboBox vom Kunden
		String listItem1 = String.valueOf(jComboBoxKunde.getSelectedIndex());
		//sucht das ausgewählte KundenObjekt in Hashtabelle kundeObjekt
		Kunde auswahlKunde = (Kunde) kundeObjekt.get(listItem1);
		int kdId = auswahlKunde.getId();

		//liefert listItem des selektierten Eintrags aus der ComboBox vom Artikel
		String listItem2 = String.valueOf(jComboBoxArtikel.getSelectedIndex());
		//sucht das ausgewählte Artikelobjekt in Hashtabelle artikelObjekt
		Artikel auswahlArtikel = (Artikel) artikelObjekt.get(listItem2);
		int artId = auswahlArtikel.getNr();
		boolean zleingang = false;

		Auftragsrechnung atr = new Auftragsrechnung();
		// Auftragsrechnungsdaten vorbereiten
		atr.setNr(j + 1);
		atr.setBetrag(
			Double.parseDouble(
				jTextFieldNeuerVertragAngebotspreis.getText().toString()));
		atr.setAuftragNr(i + 1);
		atr.setMwSt(mwst);
		atr.setzEingang(zleingang);

		try {
			dao.setAuftragsrechnung(atr);
		} catch (WiSimDAOException e) {
			wiSimLogger.log("speicherVertrag()", e);
		} catch (WiSimDAOWriteException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}

		Vertrag vertrag = new Vertrag();
		// Vertragsdaten vorbereiten
		vertrag.setVertragsId(i + 1);
		vertrag.setKundenId(kdId);
		vertrag.setLieferdatum(lieferDateSQL);
		vertrag.setRabatt(
			Double.parseDouble(jTextFieldRabatt.getText().toString()));
		vertrag.setSkonto(
			Double.parseDouble(jTextFieldSkonto.getText().toString()));
		vertrag.setSkontofrist(
			Long.parseLong(jTextFieldSkontofristTage.getText().toString()));
		vertrag.setVertragsdatum(new java.sql.Date(wiSimMainController.getActDate().getTime()));
		vertrag.setAuftragsrechnungsId(j + 1);

		try {
			dao.setNeuenVertrag(vertrag);
		} catch (WiSimDAOException e) {
			wiSimLogger.log("speicherVertrag()", e);
		} catch (WiSimDAOWriteException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}

		AuftragsPosition atp = new AuftragsPosition();
		//AuftragsPositionsdaten vorbereiten
		atp.setAtNr(i + 1);
		atp.setArtNr(artId);
		atp.setBestellmenge(
			Long.parseLong(jTextFieldAbnahmemenge.getText().toString()));

		try {
			dao.setAuftragsPosition(atp);
		} catch (WiSimDAOWriteException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}

		i = 0;
		j = 0;
		clearFields();
		ladeKunden();
		ladeArtikel();

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNeuerVertragAbbrechen;
    private javax.swing.JButton jButtonNeuerVertragSpeichern;
    private javax.swing.JComboBox jComboBoxArtikel;
    private javax.swing.JComboBox jComboBoxKunde;
    private javax.swing.JLabel jLabelAngebotspreis;
    private javax.swing.JLabel jLabelArtikel;
    private javax.swing.JLabel jLabelEUR;
    private javax.swing.JLabel jLabelEUR1;
    private javax.swing.JLabel jLabelEUR2;
    private javax.swing.JLabel jLabelEUR3;
    private javax.swing.JLabel jLabelKunde;
    private javax.swing.JLabel jLabelMwst;
    private javax.swing.JLabel jLabelNeuerVertrag;
    private javax.swing.JLabel jLabelNeuerVertragAbnahmemenge;
    private javax.swing.JLabel jLabelNeuerVertragAnsprueche;
    private javax.swing.JLabel jLabelNeuerVertragAnzahlVertraege;
    private javax.swing.JLabel jLabelNeuerVertragKundenTyp;
    private javax.swing.JLabel jLabelNeuerVertragLieferdatum;
    private javax.swing.JLabel jLabelNeuerVertragNettozahldatum;
    private javax.swing.JLabel jLabelNeuerVertragZahlungsmoral;
    private javax.swing.JLabel jLabelProzent;
    private javax.swing.JLabel jLabelProzent1;
    private javax.swing.JLabel jLabelProzent2;
    private javax.swing.JLabel jLabelRabatt;
    private javax.swing.JLabel jLabelSkonto;
    private javax.swing.JLabel jLabelSkontofrist;
    private javax.swing.JLabel jLabelStueckpreis;
    private javax.swing.JLabel jLabelTage;
    private javax.swing.JLabel jLabelZwischensumme1;
    private javax.swing.JLabel jLabelZwischensumme2;
    private javax.swing.JOptionPane jOptionAlert;
    private javax.swing.JOptionPane jOptionPaneConfirm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldAbnahmemenge;
    private javax.swing.JTextField jTextFieldMwst;
    private javax.swing.JTextField jTextFieldNeuerVertragAngebotspreis;
    private javax.swing.JTextField jTextFieldNeuerVertragAnsprueche;
    private javax.swing.JTextField jTextFieldNeuerVertragAnzahlVertraege;
    private javax.swing.JTextField jTextFieldNeuerVertragJahr;
    private javax.swing.JTextField jTextFieldNeuerVertragKundentyp;
    private javax.swing.JTextField jTextFieldNeuerVertragMonat;
    private javax.swing.JTextField jTextFieldNeuerVertragNettozahldatum;
    private javax.swing.JTextField jTextFieldNeuerVertragStueckpreis;
    private javax.swing.JTextField jTextFieldNeuerVertragTag;
    private javax.swing.JTextField jTextFieldNeuerVertragZahlungsmoral;
    private javax.swing.JTextField jTextFieldNeuerVertragZwischensumme1;
    private javax.swing.JTextField jTextFieldRabatt;
    private javax.swing.JTextField jTextFieldSkonto;
    private javax.swing.JTextField jTextFieldSkontofristTage;
    private javax.swing.JTextField jTextFieldZwischensumme2;
    // End of variables declaration//GEN-END:variables
}