/*
 * JPanelHilfe.java
 *
 * Created on 10. Februar 2003, 20:26
 */

package net.sourceforge.wisim.controller;

import javax.swing.JOptionPane;

/**
 *
 * @author  Kay Patzwald
 */
public class JPanelHilfe extends javax.swing.JPanel {

  /** Creates new form JPanelHilfe */
  public JPanelHilfe(WiSimMainController wiSimMainController) {
    initComponents();
  }


  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    private void initComponents() {//GEN-BEGIN:initComponents
        jOptionPaneVerInfo = new javax.swing.JOptionPane();
        jScrollPaneHilfe = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelHilfe = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jOptionPaneVerInfo.setMessageType(1);

        setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setText("Dieses Programm ist eine Simulation eines Waren-Wirtschaftssystems.\nFolgende Funktionen sind implementiert:\n\n    - Kundenverwaltung (Anlegen, Editieren, L\u00f6schen, \u00dcbersicht)\n    - Lieferantenverwaltung (Anlegen, Editieren, L\u00f6schen, \u00dcbersicht)\n    - Auftragsverwaltung (Anlegen, \u00dcbersicht)\n    - Arbeitsplatz- und Lager\u00fcbersicht mit Statusbalken\n    - Zahlungseingang verwalten\n    - Simulation der Produktion mit Auswertung\n\nChristian Drechsler\nDenise Freitag\nBenjamin Pasero\nKay Patzwald\nJanett Ziola\n\nDieses Programm ist ausschlie\u00dflich f\u00fcr\nBerufsschulzwecke gedacht und darf au\u00dferhalb \ndes OSZ KIM Berlin nur mit Genehmigung\nder Autoren eingesetzt werden.\nCopyright (c) 2003 Berlin - All Rights Reserved.\n");
        jScrollPaneHilfe.setViewportView(jTextArea1);

        add(jScrollPaneHilfe);
        jScrollPaneHilfe.setBounds(20, 40, 750, 355);

        jLabelHilfe.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabelHilfe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHilfe.setText("Info");
        add(jLabelHilfe);
        jLabelHilfe.setBounds(370, 10, 70, 20);

        jButton1.setText("Version");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1);
        jButton1.setBounds(370, 400, 81, 26);

    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Ver. 1.0");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelHilfe;
    private javax.swing.JOptionPane jOptionPaneVerInfo;
    private javax.swing.JScrollPane jScrollPaneHilfe;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}