/*   ********************************************************************   **
**   Copyright notice                                                       **
**                                                                          **
**   (c) 2003 WiSim Development Team					                              **
**   http://wisim.sourceforge.net/   			                                  **
**                                                                          **
**   All rights reserved                                                    **
**                                                                          **
**   This script is part of the WiSim Business Game project. The WiSim      **
**   project is free software; you can redistribute it and/or modify        **
**   it under the terms of the GNU General Public License as published by   **
**   the Free Software Foundation; either version 2 of the License, or      **
**   (at your option) any later version.                                    **
**                                                                          **
**   The GNU General Public License can be found at                         **
**   http://www.gnu.org/copyleft/gpl.html.                                  **
**   A copy is found in the textfile GPL.txt and important notices to the   **
**   license from the team is found in the textfile LICENSE.txt distributed **
**   in these package.                                                      **
**                                                                          **
**   This copyright notice MUST APPEAR in all copies of the file!           **
**   ********************************************************************   */

/*
 * JPanelVertragEinsehen.java
 *
 * Created on 10. Februar 2003, 21:04
 */

package net.sourceforge.wisim.controller;

import java.util.*;
import javax.swing.*;

import net.sourceforge.wisim.dao.*;
import net.sourceforge.wisim.model.*;
import javax.swing.table.DefaultTableModel;
import java.awt.image.*;
import java.awt.*;

/**
 *
 * @author  Denise Freitag
 */
public class JPanelVertragEinsehen extends javax.swing.JPanel {

	private WiSimDAO dao;
	private String Tag;
	private String Monat;
	private String Jahr;
	private int kdId;
	private Hashtable auftragObjekt1;
	private Hashtable auftragObjekt2;
	private Hashtable kundeObjekt;
	private Hashtable kundenId;
	private Date auftragDateSQL;
	private int vertragAnzahl;
	private int rows;
	private int selectedAuftrag1;
	private int selectedAuftrag2;
	private int eingabeDatumTag;
	private int eingabeDatumMonat;
	private int eingabeDatumJahr;
	private Color darkgreen = new Color(51, 153, 51);
	private Color red = new Color(255, 0, 0);
	private Color orange = new Color(255, 153, 0);
	private Date heuteDateSQL;
        private WiSimMainController wiSimMainController;

	//Logger
	private WiSimLogger wiSimLogger;

	/** Creates new form JPanelVertragEinsehen */
	public JPanelVertragEinsehen(WiSimMainController wiSimMainController) {
		this.wiSimMainController = wiSimMainController;
                initDAO(wiSimMainController);
		auftragObjekt1 = new Hashtable();
		auftragObjekt2 = new Hashtable();
		kundeObjekt = new Hashtable();
		kundenId = new Hashtable();
		auftragDateSQL = null;
		heuteDateSQL = null;
		rows = 0;
		kdId = 0;
		selectedAuftrag1 = 0;
		selectedAuftrag2 = 0;
		eingabeDatumTag = 0;
		eingabeDatumMonat = 0;
		eingabeDatumJahr = 0;
                initComponents();
                showLegende();
	}

	private void initDAO(WiSimMainController wiSimMainController) {
		dao = wiSimMainController.getDAO();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabelVertragEinsehen = new javax.swing.JLabel();
        jScrollPaneVertraegeEinsehen = new javax.swing.JScrollPane();
        jTableVertraegeEinsehenVertraege = new javax.swing.JTable();
        jTableVertraegeEinsehenVertraege.setSelectionMode(0);
        jTableVertraegeEinsehenVertraege.getTableHeader().setReorderingAllowed(false);

        jLabelAuftraege = new javax.swing.JLabel();
        jPanelLegende = new javax.swing.JPanel();
        jLabelGruen = new javax.swing.JLabel();
        jLabelRot = new javax.swing.JLabel();
        jPanelVertraegeEinsehenDetails = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelArtikel = new javax.swing.JLabel();
        jTextFieldArtikel = new javax.swing.JTextField();
        jLabelStueckpreis = new javax.swing.JLabel();
        jTextFieldStueckpreis = new javax.swing.JTextField();
        jLabelEUR2 = new javax.swing.JLabel();
        jLabelMwst = new javax.swing.JLabel();
        jTextFieldMwst = new javax.swing.JTextField();
        jLabelProzent1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelMenge = new javax.swing.JLabel();
        jTextFieldMenge = new javax.swing.JTextField();
        jLabelZwischensumme1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldZwischensumme1 = new javax.swing.JTextField();
        jLabelEUR3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelRabatt = new javax.swing.JLabel();
        jTextFieldRabatt = new javax.swing.JTextField();
        jLabelProzent2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelSkonto = new javax.swing.JLabel();
        jLabelProzent3 = new javax.swing.JLabel();
        jTextSkonto = new javax.swing.JTextField();
        jLabelSkontofrist = new javax.swing.JLabel();
        jLabelTage = new javax.swing.JLabel();
        jTextFieldSkontofrist = new javax.swing.JTextField();
        jLabelNettozahldatum = new javax.swing.JLabel();
        jTextFieldNettozahldatum = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelZwischensumme2 = new javax.swing.JLabel();
        jTextField2Zwischensumme2 = new javax.swing.JTextField();
        jLabelEUR4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelAngebotspreis1 = new javax.swing.JLabel();
        jTextFieldAngebotspreis1 = new javax.swing.JTextField();
        jLabelEUR1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelAuftragsdatum1 = new javax.swing.JLabel();
        jLabelVertraegeEinsehenKunde = new javax.swing.JLabel();
        jComboBoxVertraegeEinsehenAuftragsdatumTag = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxVertraegeEinsehenAuftragsdatumMonat = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxVertraegeEinsehenAuftragsdatumJahr = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxVertraegeEinsehenKunde = new javax.swing.JComboBox();
        jButtonVertraegeEinsehenAuftragsdatumOK = new javax.swing.JButton();
        jButtonVertraegeEinsehenKundeOK = new javax.swing.JButton();
        jTextFieldVertraegeEinsehen = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldAnmerkung = new javax.swing.JTextField();

        setLayout(null);

        jLabelVertragEinsehen.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabelVertragEinsehen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVertragEinsehen.setText("Vertr\u00e4ge einsehen");
        add(jLabelVertragEinsehen);
        jLabelVertragEinsehen.setBounds(0, 0, 800, 40);

        jTableVertraegeEinsehenVertraege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVertraegeEinsehenVertraege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVertraegeEinsehenVertraegeMouseClicked(evt);
            }
        });

        jScrollPaneVertraegeEinsehen.setViewportView(jTableVertraegeEinsehenVertraege);

        add(jScrollPaneVertraegeEinsehen);
        jScrollPaneVertraegeEinsehen.setBounds(20, 200, 300, 250);

        jLabelAuftraege.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelAuftraege.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAuftraege.setText("Vertr\u00e4ge");
        add(jLabelAuftraege);
        jLabelAuftraege.setBounds(20, 180, 300, 16);

        jPanelLegende.setLayout(null);

        jPanelLegende.setBorder(new javax.swing.border.TitledBorder("Legende"));
        jLabelGruen.setText("Auftrag abgeschlossen");
        jPanelLegende.add(jLabelGruen);
        jLabelGruen.setBounds(30, 20, 180, 16);

        jLabelRot.setText("Auftrag noch nicht abgeschlossen");
        jPanelLegende.add(jLabelRot);
        jLabelRot.setBounds(30, 50, 280, 16);

        add(jPanelLegende);
        jPanelLegende.setBounds(20, 460, 300, 80);

        jPanelVertraegeEinsehenDetails.setLayout(null);

        jPanelVertraegeEinsehenDetails.setBorder(new javax.swing.border.TitledBorder("Details zum ausgew\u00e4hlten Vertrag"));
        jPanel2.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.TitledBorder(null, "Angaben zum Artikel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jLabelArtikel.setText("Artikel :");
        jPanel2.add(jLabelArtikel);
        jLabelArtikel.setBounds(10, 30, 50, 16);

        jTextFieldArtikel.setEditable(false);
        jTextFieldArtikel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldArtikel.setBorder(null);
        jPanel2.add(jTextFieldArtikel);
        jTextFieldArtikel.setBounds(90, 30, 70, 16);

        jLabelStueckpreis.setText("St\u00fcckpreis :");
        jPanel2.add(jLabelStueckpreis);
        jLabelStueckpreis.setBounds(10, 60, 80, 16);

        jTextFieldStueckpreis.setEditable(false);
        jTextFieldStueckpreis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldStueckpreis.setBorder(null);
        jPanel2.add(jTextFieldStueckpreis);
        jTextFieldStueckpreis.setBounds(90, 60, 70, 16);

        jLabelEUR2.setFont(new java.awt.Font("Dialog", 1, 16));
        jLabelEUR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEUR2.setText("\u20ac");
        jLabelEUR2.setMaximumSize(new java.awt.Dimension(9, 22));
        jLabelEUR2.setMinimumSize(new java.awt.Dimension(9, 22));
        jLabelEUR2.setPreferredSize(new java.awt.Dimension(9, 22));
        jPanel2.add(jLabelEUR2);
        jLabelEUR2.setBounds(170, 60, 10, 20);

        jLabelMwst.setText("MwSt :");
        jPanel2.add(jLabelMwst);
        jLabelMwst.setBounds(10, 90, 40, 16);

        jTextFieldMwst.setEditable(false);
        jTextFieldMwst.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMwst.setBorder(null);
        jPanel2.add(jTextFieldMwst);
        jTextFieldMwst.setBounds(120, 90, 40, 16);

        jLabelProzent1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelProzent1.setText("%");
        jPanel2.add(jLabelProzent1);
        jLabelProzent1.setBounds(170, 90, 10, 19);

        jPanelVertraegeEinsehenDetails.add(jPanel2);
        jPanel2.setBounds(20, 30, 190, 120);

        jPanel4.setLayout(null);

        jPanel4.setBorder(new javax.swing.border.TitledBorder(null, "Weiteres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jLabelMenge.setText("Menge :");
        jPanel4.add(jLabelMenge);
        jLabelMenge.setBounds(10, 30, 50, 16);

        jTextFieldMenge.setEditable(false);
        jTextFieldMenge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMenge.setBorder(null);
        jPanel4.add(jTextFieldMenge);
        jTextFieldMenge.setBounds(60, 30, 100, 16);

        jLabelZwischensumme1.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabelZwischensumme1.setText("Zwischensumme");
        jPanel4.add(jLabelZwischensumme1);
        jLabelZwischensumme1.setBounds(50, 70, 100, 16);

        jPanel4.add(jSeparator2);
        jSeparator2.setBounds(10, 60, 170, 10);

        jTextFieldZwischensumme1.setEditable(false);
        jTextFieldZwischensumme1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldZwischensumme1.setBorder(null);
        jPanel4.add(jTextFieldZwischensumme1);
        jTextFieldZwischensumme1.setBounds(20, 90, 140, 16);

        jLabelEUR3.setFont(new java.awt.Font("Dialog", 1, 16));
        jLabelEUR3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEUR3.setText("\u20ac");
        jLabelEUR3.setMaximumSize(new java.awt.Dimension(9, 22));
        jLabelEUR3.setMinimumSize(new java.awt.Dimension(9, 22));
        jLabelEUR3.setPreferredSize(new java.awt.Dimension(9, 22));
        jPanel4.add(jLabelEUR3);
        jLabelEUR3.setBounds(170, 90, 10, 20);

        jPanelVertraegeEinsehenDetails.add(jPanel4);
        jPanel4.setBounds(230, 30, 190, 120);

        jPanel5.setLayout(null);

        jPanel5.setBorder(new javax.swing.border.TitledBorder(null, "Abz\u00fcge", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jLabelRabatt.setText("Rabatt :");
        jPanel5.add(jLabelRabatt);
        jLabelRabatt.setBounds(10, 30, 50, 16);

        jTextFieldRabatt.setEditable(false);
        jTextFieldRabatt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRabatt.setBorder(null);
        jPanel5.add(jTextFieldRabatt);
        jTextFieldRabatt.setBounds(120, 30, 40, 16);

        jLabelProzent2.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelProzent2.setText("%");
        jPanel5.add(jLabelProzent2);
        jLabelProzent2.setBounds(170, 30, 10, 19);

        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(10, 60, 380, 10);

        jLabelSkonto.setText("Skonto :");
        jPanel5.add(jLabelSkonto);
        jLabelSkonto.setBounds(10, 70, 50, 16);

        jLabelProzent3.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelProzent3.setText("%");
        jPanel5.add(jLabelProzent3);
        jLabelProzent3.setBounds(170, 70, 10, 19);

        jTextSkonto.setEditable(false);
        jTextSkonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextSkonto.setBorder(null);
        jPanel5.add(jTextSkonto);
        jTextSkonto.setBounds(120, 70, 40, 16);

        jLabelSkontofrist.setText("Skontofrist :");
        jPanel5.add(jLabelSkontofrist);
        jLabelSkontofrist.setBounds(220, 70, 70, 16);

        jLabelTage.setText("Tage");
        jPanel5.add(jLabelTage);
        jLabelTage.setBounds(360, 70, 30, 16);

        jTextFieldSkontofrist.setEditable(false);
        jTextFieldSkontofrist.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSkontofrist.setBorder(null);
        jPanel5.add(jTextFieldSkontofrist);
        jTextFieldSkontofrist.setBounds(310, 70, 40, 16);

        jLabelNettozahldatum.setText("Nettozahldatum :");
        jPanel5.add(jLabelNettozahldatum);
        jLabelNettozahldatum.setBounds(10, 100, 100, 16);

        jTextFieldNettozahldatum.setEditable(false);
        jTextFieldNettozahldatum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNettozahldatum.setBorder(null);
        jPanel5.add(jTextFieldNettozahldatum);
        jTextFieldNettozahldatum.setBounds(120, 100, 120, 16);

        jPanel5.add(jSeparator3);
        jSeparator3.setBounds(10, 120, 380, 10);

        jLabelZwischensumme2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabelZwischensumme2.setText("Zwischensumme :");
        jPanel5.add(jLabelZwischensumme2);
        jLabelZwischensumme2.setBounds(10, 140, 110, 16);

        jTextField2Zwischensumme2.setEditable(false);
        jTextField2Zwischensumme2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2Zwischensumme2.setBorder(null);
        jPanel5.add(jTextField2Zwischensumme2);
        jTextField2Zwischensumme2.setBounds(120, 140, 150, 16);

        jLabelEUR4.setFont(new java.awt.Font("Dialog", 1, 16));
        jLabelEUR4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEUR4.setText("\u20ac");
        jLabelEUR4.setMaximumSize(new java.awt.Dimension(9, 22));
        jLabelEUR4.setMinimumSize(new java.awt.Dimension(9, 22));
        jLabelEUR4.setPreferredSize(new java.awt.Dimension(9, 22));
        jPanel5.add(jLabelEUR4);
        jLabelEUR4.setBounds(280, 140, 10, 20);

        jPanelVertraegeEinsehenDetails.add(jPanel5);
        jPanel5.setBounds(20, 160, 400, 170);

        jPanel6.setLayout(null);

        jPanel6.setBorder(new javax.swing.border.TitledBorder(null, "Preis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jLabelAngebotspreis1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabelAngebotspreis1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAngebotspreis1.setText("Angebotspreis :");
        jPanel6.add(jLabelAngebotspreis1);
        jLabelAngebotspreis1.setBounds(20, 30, 140, 24);

        jTextFieldAngebotspreis1.setEditable(false);
        jTextFieldAngebotspreis1.setFont(new java.awt.Font("Dialog", 0, 18));
        jTextFieldAngebotspreis1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAngebotspreis1.setBorder(null);
        jPanel6.add(jTextFieldAngebotspreis1);
        jTextFieldAngebotspreis1.setBounds(170, 30, 200, 20);

        jLabelEUR1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabelEUR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEUR1.setText("\u20ac");
        jPanel6.add(jLabelEUR1);
        jLabelEUR1.setBounds(370, 30, 20, 20);

        jPanelVertraegeEinsehenDetails.add(jPanel6);
        jPanel6.setBounds(20, 340, 400, 70);

        add(jPanelVertraegeEinsehenDetails);
        jPanelVertraegeEinsehenDetails.setBounds(340, 120, 440, 420);

        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Eingabe von Vertragsdatum oder Kunde"));
        jLabelAuftragsdatum1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAuftragsdatum1.setText("Vertragsdatum");
        jPanel1.add(jLabelAuftragsdatum1);
        jLabelAuftragsdatum1.setBounds(10, 30, 100, 16);

        jLabelVertraegeEinsehenKunde.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelVertraegeEinsehenKunde.setText("Kunde");
        jPanel1.add(jLabelVertraegeEinsehenKunde);
        jLabelVertraegeEinsehenKunde.setBounds(10, 60, 110, 16);

        jComboBoxVertraegeEinsehenAuftragsdatumTag.setFont(new java.awt.Font("Dialog", 1, 10));
        jComboBoxVertraegeEinsehenAuftragsdatumTag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jComboBoxVertraegeEinsehenAuftragsdatumTag);
        jComboBoxVertraegeEinsehenAuftragsdatumTag.setBounds(110, 30, 40, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 9));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tag");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 20, 40, 10);

        jComboBoxVertraegeEinsehenAuftragsdatumMonat.setFont(new java.awt.Font("Dialog", 1, 10));
        jComboBoxVertraegeEinsehenAuftragsdatumMonat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jComboBoxVertraegeEinsehenAuftragsdatumMonat);
        jComboBoxVertraegeEinsehenAuftragsdatumMonat.setBounds(150, 30, 40, 20);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 9));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Monat");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 20, 40, 10);

        jComboBoxVertraegeEinsehenAuftragsdatumJahr.setFont(new java.awt.Font("Dialog", 1, 10));
        jComboBoxVertraegeEinsehenAuftragsdatumJahr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "2002", "2003", "2004", "2005", "2006" }));
        jPanel1.add(jComboBoxVertraegeEinsehenAuftragsdatumJahr);
        jComboBoxVertraegeEinsehenAuftragsdatumJahr.setBounds(190, 30, 60, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 9));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jahr");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 20, 60, 12);

        jComboBoxVertraegeEinsehenKunde.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBoxVertraegeEinsehenKundeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.add(jComboBoxVertraegeEinsehenKunde);
        jComboBoxVertraegeEinsehenKunde.setBounds(110, 60, 140, 20);

        jButtonVertraegeEinsehenAuftragsdatumOK.setBackground(new java.awt.Color(153, 153, 153));
        jButtonVertraegeEinsehenAuftragsdatumOK.setFont(new java.awt.Font("Dialog", 1, 10));
        jButtonVertraegeEinsehenAuftragsdatumOK.setText("OK");
        jButtonVertraegeEinsehenAuftragsdatumOK.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVertraegeEinsehenAuftragsdatumOK.setMargin(new java.awt.Insets(1, 2, 2, 1));
        jButtonVertraegeEinsehenAuftragsdatumOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVertraegeEinsehenAuftragsdatumOKActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonVertraegeEinsehenAuftragsdatumOK);
        jButtonVertraegeEinsehenAuftragsdatumOK.setBounds(270, 30, 20, 18);

        jButtonVertraegeEinsehenKundeOK.setBackground(new java.awt.Color(153, 153, 153));
        jButtonVertraegeEinsehenKundeOK.setFont(new java.awt.Font("Dialog", 1, 10));
        jButtonVertraegeEinsehenKundeOK.setText("OK");
        jButtonVertraegeEinsehenKundeOK.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVertraegeEinsehenKundeOK.setMargin(new java.awt.Insets(1, 2, 2, 1));
        jButtonVertraegeEinsehenKundeOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVertraegeEinsehenKundeOKActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonVertraegeEinsehenKundeOK);
        jButtonVertraegeEinsehenKundeOK.setBounds(270, 60, 20, 18);

        jTextFieldVertraegeEinsehen.setEditable(false);
        jTextFieldVertraegeEinsehen.setFont(new java.awt.Font("Dialog", 1, 12));
        jTextFieldVertraegeEinsehen.setForeground(new java.awt.Color(255, 51, 0));
        jTextFieldVertraegeEinsehen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVertraegeEinsehen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldVertraegeEinsehen.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldVertraegeEinsehen);
        jTextFieldVertraegeEinsehen.setBounds(10, 90, 280, 18);

        add(jPanel1);
        jPanel1.setBounds(20, 50, 300, 130);

        jPanel3.setLayout(null);

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Anmerkung"));
        jTextFieldAnmerkung.setEditable(false);
        jTextFieldAnmerkung.setForeground(new java.awt.Color(51, 0, 255));
        jTextFieldAnmerkung.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAnmerkung.setBorder(null);
        jPanel3.add(jTextFieldAnmerkung);
        jTextFieldAnmerkung.setBounds(10, 30, 420, 20);

        add(jPanel3);
        jPanel3.setBounds(340, 50, 440, 60);

    }//GEN-END:initComponents

	private void jTableVertraegeEinsehenVertraegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVertraegeEinsehenVertraegeMouseClicked
		getVertragsdaten();
	} //GEN-LAST:event_jTableVertraegeEinsehenVertraegeMouseClicked

	private void jComboBoxVertraegeEinsehenKundeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBoxVertraegeEinsehenKundeAncestorAdded
		ladeKunden();
	} //GEN-LAST:event_jComboBoxVertraegeEinsehenKundeAncestorAdded

	private void jButtonVertraegeEinsehenKundeOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVertraegeEinsehenKundeOKActionPerformed
		merkeDaten2();
	} //GEN-LAST:event_jButtonVertraegeEinsehenKundeOKActionPerformed

	private void jButtonVertraegeEinsehenAuftragsdatumOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVertraegeEinsehenAuftragsdatumOKActionPerformed
		pruefeEingabeDatum();
	} //GEN-LAST:event_jButtonVertraegeEinsehenAuftragsdatumOKActionPerformed
	/**
	 * Method pruefeEingabeDatum. Prüft, ob Tag, Monat und Jahr ausgefüllt wurde.
	 * Wenn eines fehlt, wird eine Fehlermeldung ausgegeben.
	 */
	public void pruefeEingabeDatum() {
		jComboBoxVertraegeEinsehenKunde.setSelectedIndex(0);

		if (jComboBoxVertraegeEinsehenAuftragsdatumTag.getSelectedIndex()
			== 0) {
			jTextFieldVertraegeEinsehen.setText(
				"Vertragsdatum falsch eingegeben!");
			eingabeDatumTag = 1;
		} else
			eingabeDatumTag = 0;

		if (jComboBoxVertraegeEinsehenAuftragsdatumMonat.getSelectedIndex()
			== 0) {
			jTextFieldVertraegeEinsehen.setText(
				"Vertragsdatum falsch eingegeben!");
			eingabeDatumMonat = 1;
		} else
			eingabeDatumMonat = 0;

		if (jComboBoxVertraegeEinsehenAuftragsdatumJahr.getSelectedIndex()
			== 0) {
			jTextFieldVertraegeEinsehen.setText(
				"Vertragsdatum falsch eingegeben!");
			eingabeDatumJahr = 1;
		} else
			eingabeDatumJahr = 0;

		pruefeAuftragsdatum();
	}

	/**
	 * Method pruefeAuftragsdatum. Auftragsdatum == Vertragsdatum.
	 * Prüft, ob für das ausgewählte Auftragsdatum ein Vertrag besteht.
	 * Vertrag == Auftrag.
	 */
	public void pruefeAuftragsdatum() {

		jComboBoxVertraegeEinsehenKunde.setSelectedIndex(0);

		if ((eingabeDatumTag == 0)
			&& (eingabeDatumMonat == 0)
			&& (eingabeDatumJahr == 0)) {

			Tag =
				String.valueOf(
					jComboBoxVertraegeEinsehenAuftragsdatumTag
						.getSelectedItem());
			Monat =
				String.valueOf(
					jComboBoxVertraegeEinsehenAuftragsdatumMonat
						.getSelectedItem());
			Jahr =
				String.valueOf(
					jComboBoxVertraegeEinsehenAuftragsdatumJahr
						.getSelectedItem());

			int auftragTag = Integer.parseInt(Tag);
			int auftragMonat = Integer.parseInt(Monat) - 1;
			int auftragJahr = Integer.parseInt(Jahr);

			GregorianCalendar auftragDatum =
				new GregorianCalendar(auftragJahr, auftragMonat, auftragTag);

			auftragDateSQL = new java.sql.Date(auftragDatum.getTimeInMillis());

			// Lädt alle Verträge aus der Datenbank
			Collection vertraege = null;
			try {
				vertraege = dao.getVertraege();
			} catch (WiSimDAOException e) {
				wiSimLogger.log("pruefeAuftragsdatum()", e);
			}

			// Verhindert NullPointerException bei einer leeren Liste
			if (vertraege != null) {
				Iterator it = vertraege.iterator();
				while (it.hasNext()) {
					Vertrag vertrag = (Vertrag) it.next();
					//Schreibt die Objekte von Vertrag in eine Hashtable, die aDatum entsprechen
					if (vertrag.getVertragsdatum().equals(auftragDateSQL)) {
						rows++;
					}
				}
				if (rows > 0) {
					jTextFieldVertraegeEinsehen.setText(
						"Vertragsdatum ist vorhanden!");
					rows = 0;
					merkeDaten1();
				} else {
					jTextFieldVertraegeEinsehen.setText(
						"Vertragsdatum nicht vorhanden!");
					leereFelder();
					clearTabelle();
				}
			}
		} else {
			leereFelder();
			clearTabelle();
		}
		rows = 0;
	}

	/**
	* Method merkeDaten1. Merkt sich das ausgewählte Vertragsdatum, um die dazu gehörigen
	* Vertragsdaten und Kunden aus der Datenbank zu laden.
	* Der Benutzer hat einen Kundennamen gewählt.
	*/
	public void merkeDaten1() {
		Collection vertragList = null;
		selectedAuftrag2 = 0;
		selectedAuftrag1 = 1;
		leereFelder();
		try {
			vertragList = dao.getVertraege();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("merkeDaten1()", e);
		}

		if (vertragList != null) {
			Iterator it = vertragList.iterator();

			while (it.hasNext()) {
				Vertrag vertrag = (Vertrag) it.next();

				if (vertrag.getVertragsdatum().equals(auftragDateSQL)) {
					rows++;
					auftragObjekt1.put((String.valueOf(rows)), vertrag);
				}
			}

			if (rows > 0) {

				Kunde kunde = null;
				int j = 0;
				setVertragsTabelle1();

				for (int n = 1; n <= rows; n++) {

					Vertrag auftrag1 =
						(Vertrag) auftragObjekt1.get((String.valueOf(n)));

					if (auftrag1 != null) {

						kdId = auftrag1.getKundenId();

						try {
							kunde = dao.getKunde(kdId);
						} catch (WiSimDAOException e) {
							wiSimLogger.log("merkeDaten1()", e);
						}

						jTableVertraegeEinsehenVertraege.setValueAt(
							String.valueOf(auftrag1.getVertragsId()),
							j,
							0);
						jTableVertraegeEinsehenVertraege.setValueAt(
							String.valueOf(
								kunde.getVorname().concat(
									" " + String.valueOf(kunde.getNachname()))),
							j,
							1);
						jTableVertraegeEinsehenVertraege.setValueAt(
							formatDate(auftrag1.getLieferdatum()),
							j,
							2);

						//Status Icon
						Image image = new BufferedImage(28, 30, 2);
						Graphics g = image.getGraphics();
						Date heuteDate = new Date();

						if (auftrag1.getLieferdatum().before(wiSimMainController.getActDate())) {
							g.setColor(darkgreen);
						} else {
							g.setColor(red);
						}
						g.fillRoundRect(10, 11, 10, 10, 3, 3);

						ImageIcon ic = new ImageIcon(image);

						jTableVertraegeEinsehenVertraege.setValueAt(ic, j, 3);

						j++;
					}
				}
			}
		}
		rows = 0;
		kdId = 0;
		auftragDateSQL = null;
	}

	/**
	 * Method setVertragsTabelle1. Erstellt den Tabellenkopf für die 1. Form der Vertragsausgabe.
	 * Der Benutzer hat ein Vertragsdatum ausgewählt.
	 */
	public void setVertragsTabelle1() {

		//DefaultTableModel mit Variablen Zeilen, 4 TableHeads und nicht editierbaren Zellen
		Object[][] tableInit = new Object[rows][4];
		DefaultTableModel defTable =
			new DefaultTableModel(
				tableInit,
				new String[] { "Nr", "Kunde", "Lieferdatum", "Status" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };
			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
			public Class getColumnClass(int c) {
				return getValueAt(0, c).getClass();
			}
		};
		jTableVertraegeEinsehenVertraege.setModel(defTable);
		jTableVertraegeEinsehenVertraege.setFocusable(false);

		javax.swing.table.TableColumn column = null;
		for (int i = 0; i < 4; i++) {
			column =
				jTableVertraegeEinsehenVertraege.getColumnModel().getColumn(i);
			if (i == 1) {
				column.setPreferredWidth(70);
			} else if (i == 2) {
				column.setPreferredWidth(60);
			} else if (i == 3) {
				column.setPreferredWidth(20);
			} else {
				column.setPreferredWidth(10);
			}
		}

		jTableVertraegeEinsehenVertraege.getTableHeader().setReorderingAllowed(
			false);
		jTableVertraegeEinsehenVertraege.setDragEnabled(false);

	}

	/**
	 * Method merkeDaten2. Merkt sich den ausgewählten Kunden, um die dazu gehörigen
	 * Vertragsdaten aus der Datenbank zu laden.
	 * Der Benutzer hat einen Kundennamen gewählt.
	 */
	public void merkeDaten2() {
		selectedAuftrag1 = 0;
		selectedAuftrag2 = 1;
		leereFelder();

		jComboBoxVertraegeEinsehenAuftragsdatumTag.setSelectedIndex(0);
		jComboBoxVertraegeEinsehenAuftragsdatumMonat.setSelectedIndex(0);
		jComboBoxVertraegeEinsehenAuftragsdatumJahr.setSelectedIndex(0);
		jTableVertraegeEinsehenVertraege.setSelectionMode(0);

		if ((jComboBoxVertraegeEinsehenKunde.getSelectedIndex()) != 0) {
			jTextFieldVertraegeEinsehen.setText(
				"Sie haben einen Kunden gewählt!");

			//liefert listItem des selektierten Eintrags
			String listItem =
				String.valueOf(
					jComboBoxVertraegeEinsehenKunde.getSelectedIndex());

			//sucht das ausgewählte KundenObjekt in Hashtabelle kundeObjekt
			Kunde auswahlKunde = (Kunde) kundeObjekt.get(listItem);

			if (auswahlKunde != null) {
				kdId = auswahlKunde.getId();
			}

			Collection vertragList = null;

			try {
				vertragList = dao.getVertraege();
			} catch (WiSimDAOException e) {
				wiSimLogger.log("merkeDaten2()", e);
			}

			if (vertragList != null) {
				Iterator it = vertragList.iterator();

				while (it.hasNext()) {
					Vertrag vertrag = (Vertrag) it.next();

					if (vertrag.getKundenId() == kdId) {
						rows++;
						auftragObjekt2.put(String.valueOf(rows), vertrag);
					}
				}

				if (rows > 0) {

					Vertrag auftrag = null;
					setVertragsTabelle2();
					int j = 0;

					for (int n = 1; n <= rows; n++) {

						Vertrag auftrag2 =
							(Vertrag) auftragObjekt2.get(String.valueOf(n));

						if (auftrag2 != null) {
							jTableVertraegeEinsehenVertraege.setValueAt(
								String.valueOf(auftrag2.getVertragsId()),
								j,
								0);
							jTableVertraegeEinsehenVertraege.setValueAt(
								formatDate(auftrag2.getVertragsdatum()),
								j,
								1);
							jTableVertraegeEinsehenVertraege.setValueAt(
								formatDate(auftrag2.getLieferdatum()),
								j,
								2);

							//Status Icon
							Image image = new BufferedImage(28, 30, 2);
							Graphics g = image.getGraphics();
							Date heuteDate = new Date();

							if (auftrag2.getLieferdatum().before(wiSimMainController.getActDate())) {
								g.setColor(darkgreen);
							} else {
								g.setColor(red);
							}
							g.fillRoundRect(10, 11, 10, 10, 3, 3);

							ImageIcon ic = new ImageIcon(image);

							jTableVertraegeEinsehenVertraege.setValueAt(
								ic,
								j,
								3);
							j++;
						}
					}
				} else {
					jTextFieldVertraegeEinsehen.setText(
						"Kein Auftrag für diesen Kunden!");
					clearTabelle();
					leereFelder();
				}
			}
		} else {
			jTextFieldVertraegeEinsehen.setText("Es wurde nichts ausgewählt!");
			clearTabelle();
			leereFelder();
		}
		rows = 0;
		kdId = 0;
	}

	/**
	 * Method setVertragsTabelle2. Erstellt den Tabellenkopf für die 2. Form der Vertragsausgabe.
	 * Der Benutzer hat einen Kundennamen gewählt.
	 */
	public void setVertragsTabelle2() {

		//DefaultTableModel mit Variablen Zeilen, 3 TableHeads und nicht editierbaren Zellen
		Object[][] tableInit = new Object[rows][4];
		DefaultTableModel defTable =
			new DefaultTableModel(
				tableInit,
				new String[] {
					"Nr",
					"Auftragsdatum",
					"Lieferdatum",
					"Status" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };
			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
			public Class getColumnClass(int c) {
				return getValueAt(0, c).getClass();
			}
		};

		jTableVertraegeEinsehenVertraege.setModel(defTable);
		jTableVertraegeEinsehenVertraege.setFocusable(false);

		javax.swing.table.TableColumn column = null;
		for (int i = 0; i < 4; i++) {
			column =
				jTableVertraegeEinsehenVertraege.getColumnModel().getColumn(i);
			if (i == 1) {
				column.setPreferredWidth(60);
			} else if (i == 2) {
				column.setPreferredWidth(50);
			} else if (i == 3) {
				column.setPreferredWidth(30);
			} else {
				column.setPreferredWidth(10);
			}
		}

		jTableVertraegeEinsehenVertraege.getTableHeader().setReorderingAllowed(
			false);
		jTableVertraegeEinsehenVertraege.setDragEnabled(false);

	}

	/**
	 * Method clearTabelle. Löscht die Tabelle der Verträge mit Tabellenkopf.
	 */
	public void clearTabelle() {
		//DefaultTableModel mit Variablen Zeilen, 4 TableHeads und nicht editierbaren Zellen
		jTableVertraegeEinsehenVertraege
			.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
		}, new String[] { "", "", "", "" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
	}

	/** Formatiert ein Date Objekt zu einem String TT.MM.JJJJ.
	* @param dateToFormat Das zu formatierende Datum.
	* @return Das formatierte Datum.
	*/
	public String formatDate(java.sql.Date dateToFormat) {
		String date = String.valueOf(dateToFormat);
		String year = date.substring(0, 4);
		String month = date.substring(5, 7);
		String day = date.substring(8, 10);
		String formattedDate = day + "." + month + "." + year;
		return formattedDate;
	}

	/** Zeigt die Legende an */
	public void showLegende() {
		//Legende
		Image imageIconGreen = new BufferedImage(28, 30, 2);
		Graphics g = imageIconGreen.getGraphics();
		g.setColor(darkgreen);
		g.fillRoundRect(10, 11, 10, 10, 3, 3);
		ImageIcon ic = new ImageIcon(imageIconGreen);
		jLabelGruen.setIcon(ic);

		Image imageIconRed = new BufferedImage(28, 30, 2);
		g = imageIconRed.getGraphics();
		g.setColor(red);
		g.fillRoundRect(10, 11, 10, 10, 3, 3);
		ic = new ImageIcon(imageIconRed);
		jLabelRot.setIcon(ic);
	}

	/**
	 * Method ladeKunden. Lädt die Kunden aus der Datenbank.
	 * Diese werden in die Combo-Box geladen.
	 */
	public void ladeKunden() {
		Collection kunden = null;
		try {
			kunden = dao.getKunden();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("ladeKunden()", e);
		}

		DefaultComboBoxModel model =
			(DefaultComboBoxModel) jComboBoxVertraegeEinsehenKunde.getModel();
		model.removeAllElements();
		model.addElement("Bitte auswählen:");

		// Verhindert NullPointerException bei einer leeren Liste
		if (kunden != null) {
			Iterator it = kunden.iterator();
			while (it.hasNext()) {
				Kunde kunde = (Kunde) it.next();
				//Merken des Nachnamen und Vornamen, um diese in die ComboBox einzutragen
				String merkeName =
					String.valueOf(kunde.getVorname()).concat(" ");
				merkeName =
					merkeName.concat(String.valueOf(kunde.getNachname()));
				model.addElement(merkeName);
				kundeObjekt.put(String.valueOf(kunde.getId()), kunde);

			}
			jComboBoxVertraegeEinsehenKunde.setModel(model);
		}
	}

	/**
	 * Method getVertragsdaten. Lädt die Daten für einen ausgewählten Vertrag aus der Datenbank.
	 * Zwischensummen werden berechnet.
	 */
	public void getVertragsdaten() {
		int merkeNr = jTableVertraegeEinsehenVertraege.getSelectedRow();
		float mwst = 0;
		// + 1, weil index der Zeile mit 0 beginnt!!!

		if (selectedAuftrag1 == 1) {
			selectedAuftrag2 = 0;
			leereFelder();
			Vertrag auftrag1 =
				(Vertrag) auftragObjekt1.get(String.valueOf(merkeNr + 1));
			Kunde kunde = null;
			Artikel artikel = null;
			Collection vertragList = null;
			AuftragsPosition atp = null;
			Auftragsrechnung atr = null;
			int i = 0;

			try {
				kunde = dao.getKunde(auftrag1.getKundenId());
				atp = dao.getAuftragsPosition(auftrag1.getVertragsId());
				artikel = dao.getArtikel(atp.getArtNr());
				mwst = dao.getMwSt();
				vertragList = dao.getVertraege();
				atr =
					dao.getAuftragsrechnung(auftrag1.getAuftragsrechnungsId());
			} catch (WiSimDAOException e) {
				wiSimLogger.log("getVertragsdaten()", e);
			}

			if (vertragList != null) {
				Iterator it = vertragList.iterator();
				while (it.hasNext()) {
					Vertrag vertrag = (Vertrag) it.next();

					if (vertrag.getKundenId() == auftrag1.getKundenId()) {
						i++;
					}
				}
			}

			if (i == 1)
				jTextFieldAnmerkung.setText(
					"Der Kunde "
						+ kunde.getVorname().concat(" " + kunde.getNachname())
						+ " besitzt "
						+ i
						+ " Vertrag.");
			else
				jTextFieldAnmerkung.setText(
					"Der Kunde "
						+ kunde.getVorname().concat(" " + kunde.getNachname())
						+ " besitzt "
						+ i
						+ " Verträge.");

			jTextFieldRabatt.setText(String.valueOf(auftrag1.getRabatt()));
			jTextSkonto.setText(String.valueOf(auftrag1.getSkonto()));
			jTextFieldSkontofrist.setText(
				String.valueOf(auftrag1.getSkontofrist()));
			jTextFieldArtikel.setText(artikel.getName());
			jTextFieldStueckpreis.setText(
				String.valueOf(artikel.getStueckpreis()));
			jTextFieldMwst.setText(String.valueOf(mwst));
			jTextFieldMenge.setText(String.valueOf(atp.getBestellmenge()));
			jTextFieldAngebotspreis1.setText(String.valueOf(atr.getBetrag()));

			// Zwischensummen werden berechnet
			double stueckPreis = 0;
			long menge = 0;
			double zwischensum1 = 0;
			double zwischensum2 = 0;
			double summe = 0;
			double rabatt = 0;
			double skonto = 0;

			stueckPreis = artikel.getStueckpreis();
			menge = atp.getBestellmenge();
			rabatt = auftrag1.getRabatt();
			skonto = auftrag1.getSkonto();

			summe = stueckPreis * menge;
			zwischensum1 = summe + (summe * mwst / 100);
			zwischensum2 =
				summe
					+ (summe * mwst / 100)
					- (summe * rabatt / 100)
					- (summe * skonto / 100);

			jTextFieldZwischensumme1.setText(String.valueOf(zwischensum1));
			jTextField2Zwischensumme2.setText(String.valueOf(zwischensum2));

			//Das Nettozahldatum wird erzeugt
			if ((!jTextFieldSkontofrist.getText().equals(""))
				&& (!jTextFieldSkontofrist.getText().equals("0"))) {
				Date auftragsDatum = auftrag1.getVertragsdatum();
				long nettoDatumMili =
					auftragsDatum.getTime()
						+ (Long.parseLong(jTextFieldSkontofrist.getText())
							* 1000
							* 60
							* 60
							* 24);
				GregorianCalendar nettoDatum = new GregorianCalendar();
				nettoDatum.setTimeInMillis(nettoDatumMili);

				String Tag = String.valueOf(nettoDatum.get(Calendar.DATE));
				String Monat =
					String.valueOf(nettoDatum.get(Calendar.MONTH) + 1);
				String Jahr = String.valueOf(nettoDatum.get(Calendar.YEAR));
				jTextFieldNettozahldatum.setForeground(Color.red);
				jTextFieldNettozahldatum.setText(
					Tag + "." + Monat + "." + Jahr);
			} else {
				jTextFieldNettozahldatum.setText("Keins vorhanden!");
			}

			i = 0;

		}

		if (selectedAuftrag2 == 1) {
			selectedAuftrag1 = 0;
			leereFelder();
			Vertrag auftrag2 =
				(Vertrag) auftragObjekt2.get(String.valueOf(merkeNr + 1));
			Kunde kunde = null;
			Artikel artikel = null;
			Collection vertragList = null;
			AuftragsPosition atp = null;
			Auftragsrechnung atr = null;
			int i = 0;

			try {
				kunde = dao.getKunde(auftrag2.getKundenId());
				atp = dao.getAuftragsPosition(auftrag2.getVertragsId());
				artikel = dao.getArtikel(atp.getArtNr());
				mwst = dao.getMwSt();
				vertragList = dao.getVertraege();
				atr =
					dao.getAuftragsrechnung(auftrag2.getAuftragsrechnungsId());
			} catch (WiSimDAOException e) {
				wiSimLogger.log("getVertragsdaten()", e);
			}

			if (vertragList != null) {
				Iterator it = vertragList.iterator();
				while (it.hasNext()) {
					Vertrag vertrag = (Vertrag) it.next();

					if (vertrag.getKundenId() == auftrag2.getKundenId()) {
						i++;
					}
				}
			}

			if (i == 1)
				jTextFieldAnmerkung.setText(
					"Der Kunde "
						+ kunde.getVorname().concat(" " + kunde.getNachname())
						+ " besitzt "
						+ i
						+ " Vertrag.");
			else
				jTextFieldAnmerkung.setText(
					"Der Kunde "
						+ kunde.getVorname().concat(" " + kunde.getNachname())
						+ " besitzt "
						+ i
						+ " Verträge.");

			jTextFieldRabatt.setText(String.valueOf(auftrag2.getRabatt()));
			jTextSkonto.setText(String.valueOf(auftrag2.getSkonto()));
			jTextFieldSkontofrist.setText(
				String.valueOf(auftrag2.getSkontofrist()));
			jTextFieldArtikel.setText(artikel.getName());
			jTextFieldStueckpreis.setText(
				String.valueOf(artikel.getStueckpreis()));
			jTextFieldMwst.setText(String.valueOf(mwst));
			jTextFieldMenge.setText(String.valueOf(atp.getBestellmenge()));
			jTextFieldAngebotspreis1.setText(String.valueOf(atr.getBetrag()));

			//Die Zwischensummen werden berechnet
			double stueckPreis = 0;
			long menge = 0;
			double zwischensum1 = 0;
			double zwischensum2 = 0;
			double hilfe = 0;
			double summe = 0;
			double rabatt = 0;
			double skonto = 0;

			stueckPreis = artikel.getStueckpreis();
			menge = atp.getBestellmenge();
			rabatt = auftrag2.getRabatt();
			skonto = auftrag2.getSkonto();

			summe = stueckPreis * menge;
			zwischensum1 = summe + (summe * mwst / 100);
			zwischensum2 =
				summe
					+ (summe * mwst / 100)
					- (summe * rabatt / 100)
					- (summe * skonto / 100);

			jTextFieldZwischensumme1.setText(String.valueOf(zwischensum1));
			jTextField2Zwischensumme2.setText(String.valueOf(zwischensum2));

			//Das Nettozahldatum wird erzeugt
			if ((!jTextFieldSkontofrist.getText().equals(""))
				&& (!jTextFieldSkontofrist.getText().equals("0"))) {
				Date auftragsDatum = auftrag2.getVertragsdatum();
				long nettoDatumMili =
					auftragsDatum.getTime()
						+ (Long.parseLong(jTextFieldSkontofrist.getText())
							* 1000
							* 60
							* 60
							* 24);
				GregorianCalendar nettoDatum = new GregorianCalendar();
				nettoDatum.setTimeInMillis(nettoDatumMili);

				String Tag = String.valueOf(nettoDatum.get(Calendar.DATE));
				String Monat =
					String.valueOf(nettoDatum.get(Calendar.MONTH) + 1);
				String Jahr = String.valueOf(nettoDatum.get(Calendar.YEAR));
				jTextFieldNettozahldatum.setForeground(Color.red);
				jTextFieldNettozahldatum.setText(
					Tag + "." + Monat + "." + Jahr);
			} else {
				jTextFieldNettozahldatum.setText("Keins vorhanden!");
			}

			i = 0;
		}
	}

	/**
	 * Method leereFelder. Leert alle Textfelder und setzt die Werte wieder zurück.
	 */
	public void leereFelder() {

		jTextField2Zwischensumme2.setText("");
		jTextFieldAngebotspreis1.setText("");
		jTextFieldAnmerkung.setText("");
		jTextFieldArtikel.setText("");
		jTextFieldMenge.setText("");
		jTextFieldMwst.setText("");
		jTextFieldNettozahldatum.setText("");
		jTextFieldRabatt.setText("");
		jTextFieldSkontofrist.setText("");
		jTextFieldStueckpreis.setText("");
		jTextFieldZwischensumme1.setText("");
		jTextSkonto.setText("");

	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVertraegeEinsehenAuftragsdatumOK;
    private javax.swing.JButton jButtonVertraegeEinsehenKundeOK;
    private javax.swing.JComboBox jComboBoxVertraegeEinsehenAuftragsdatumJahr;
    private javax.swing.JComboBox jComboBoxVertraegeEinsehenAuftragsdatumMonat;
    private javax.swing.JComboBox jComboBoxVertraegeEinsehenAuftragsdatumTag;
    private javax.swing.JComboBox jComboBoxVertraegeEinsehenKunde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAngebotspreis1;
    private javax.swing.JLabel jLabelArtikel;
    private javax.swing.JLabel jLabelAuftraege;
    private javax.swing.JLabel jLabelAuftragsdatum1;
    private javax.swing.JLabel jLabelEUR1;
    private javax.swing.JLabel jLabelEUR2;
    private javax.swing.JLabel jLabelEUR3;
    private javax.swing.JLabel jLabelEUR4;
    private javax.swing.JLabel jLabelGruen;
    private javax.swing.JLabel jLabelMenge;
    private javax.swing.JLabel jLabelMwst;
    private javax.swing.JLabel jLabelNettozahldatum;
    private javax.swing.JLabel jLabelProzent1;
    private javax.swing.JLabel jLabelProzent2;
    private javax.swing.JLabel jLabelProzent3;
    private javax.swing.JLabel jLabelRabatt;
    private javax.swing.JLabel jLabelRot;
    private javax.swing.JLabel jLabelSkonto;
    private javax.swing.JLabel jLabelSkontofrist;
    private javax.swing.JLabel jLabelStueckpreis;
    private javax.swing.JLabel jLabelTage;
    private javax.swing.JLabel jLabelVertraegeEinsehenKunde;
    private javax.swing.JLabel jLabelVertragEinsehen;
    private javax.swing.JLabel jLabelZwischensumme1;
    private javax.swing.JLabel jLabelZwischensumme2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelLegende;
    private javax.swing.JPanel jPanelVertraegeEinsehenDetails;
    private javax.swing.JScrollPane jScrollPaneVertraegeEinsehen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableVertraegeEinsehenVertraege;
    private javax.swing.JTextField jTextField2Zwischensumme2;
    private javax.swing.JTextField jTextFieldAngebotspreis1;
    private javax.swing.JTextField jTextFieldAnmerkung;
    private javax.swing.JTextField jTextFieldArtikel;
    private javax.swing.JTextField jTextFieldMenge;
    private javax.swing.JTextField jTextFieldMwst;
    private javax.swing.JTextField jTextFieldNettozahldatum;
    private javax.swing.JTextField jTextFieldRabatt;
    private javax.swing.JTextField jTextFieldSkontofrist;
    private javax.swing.JTextField jTextFieldStueckpreis;
    private javax.swing.JTextField jTextFieldVertraegeEinsehen;
    private javax.swing.JTextField jTextFieldZwischensumme1;
    private javax.swing.JTextField jTextSkonto;
    // End of variables declaration//GEN-END:variables
}