/*
 * JPanelNewGUITest2.java
 *
 * Created on 1. Juni 2003, 19:23
 */

package net.sourceforge.wisim.controller;

/**
 *
 * @author  Kay
 */
public class JPanelNewGUITest2 extends javax.swing.JPanel {
	
	/** Creates new form JPanelNewGUITest2 */
	public JPanelNewGUITest2() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  private void initComponents() {//GEN-BEGIN:initComponents
    jLabelNeuerKunde = new javax.swing.JLabel();
    jLabelVorname = new javax.swing.JLabel();
    jLabelNachname = new javax.swing.JLabel();
    jTextFieldNeuerKundeNachname = new javax.swing.JTextField();
    jLabelFirma = new javax.swing.JLabel();
    jTextFieldNeuerKundeFirma = new javax.swing.JTextField();
    jLabelStrasse = new javax.swing.JLabel();
    jTextFieldNeuerKundeStrasse = new javax.swing.JTextField();
    jLabelKundentyp = new javax.swing.JLabel();
    jComboBoxNeuerKundeKundentyp = new javax.swing.JComboBox();
    jLabelNotiz = new javax.swing.JLabel();
    jScrollPaneBemerkungen = new javax.swing.JScrollPane();
    jTextAreaNeuerKundeNotiz = new javax.swing.JTextArea();
    jButtonNeuerKundeSpeichern = new javax.swing.JButton();
    jLabelPLZ = new javax.swing.JLabel();
    jTextFieldNeuerKundePLZ = new javax.swing.JTextField();
    jLabelTelefon = new javax.swing.JLabel();
    jTextFieldNeuerKundeTelefon = new javax.swing.JTextField();
    jLabelFax = new javax.swing.JLabel();
    jTextFieldNeuerKundeFax = new javax.swing.JTextField();
    jLabelEMail = new javax.swing.JLabel();
    jTextFieldNeuerKundeEMail = new javax.swing.JTextField();
    jLabelOrt = new javax.swing.JLabel();
    jTextFieldNeuerKundeOrt = new javax.swing.JTextField();
    jButtonNeuerKundeReset = new javax.swing.JButton();
    jSeparator = new javax.swing.JSeparator();
    jTextFieldNeuerKundeVorname = new javax.swing.JTextField();
    jComboBoxNeuerLieferantZuverlaessigkeit = new javax.swing.JComboBox();
    jLabelZahlungsmoral = new javax.swing.JLabel();

    setLayout(null);

    jLabelNeuerKunde.setFont(new java.awt.Font("Dialog", 1, 24));
    jLabelNeuerKunde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelNeuerKunde.setText("Neuer Kunde");
    add(jLabelNeuerKunde);
    jLabelNeuerKunde.setBounds(0, 0, 800, 40);

    jLabelVorname.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelVorname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelVorname.setText("Vorname");
    add(jLabelVorname);
    jLabelVorname.setBounds(350, 60, 120, 19);

    jLabelNachname.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelNachname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelNachname.setText("Name");
    add(jLabelNachname);
    jLabelNachname.setBounds(-10, 60, 120, 19);

    jTextFieldNeuerKundeNachname.setDocument(new JTextFieldValidation(50));
    add(jTextFieldNeuerKundeNachname);
    jTextFieldNeuerKundeNachname.setBounds(120, 60, 210, 20);

    jLabelFirma.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelFirma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelFirma.setText("Firma");
    add(jLabelFirma);
    jLabelFirma.setBounds(-10, 90, 120, 19);

    jTextFieldNeuerKundeFirma.setDocument(new JTextFieldValidation(50));
    add(jTextFieldNeuerKundeFirma);
    jTextFieldNeuerKundeFirma.setBounds(120, 90, 210, 20);

    jLabelStrasse.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelStrasse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelStrasse.setText("Strasse");
    add(jLabelStrasse);
    jLabelStrasse.setBounds(350, 90, 120, 20);

    jTextFieldNeuerKundeStrasse.setDocument(new JTextFieldValidation(50));
    add(jTextFieldNeuerKundeStrasse);
    jTextFieldNeuerKundeStrasse.setBounds(480, 90, 210, 20);

    jLabelKundentyp.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelKundentyp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelKundentyp.setText("Kunden Typ");
    add(jLabelKundentyp);
    jLabelKundentyp.setBounds(350, 180, 120, 20);

    jComboBoxNeuerKundeKundentyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
    add(jComboBoxNeuerKundeKundentyp);
    jComboBoxNeuerKundeKundentyp.setBounds(480, 180, 40, 25);

    jLabelNotiz.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelNotiz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelNotiz.setText("Bemerkungen");
    add(jLabelNotiz);
    jLabelNotiz.setBounds(320, 240, 120, 19);

    jScrollPaneBemerkungen.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jTextAreaNeuerKundeNotiz.setLineWrap(true);
    jScrollPaneBemerkungen.setViewportView(jTextAreaNeuerKundeNotiz);

    add(jScrollPaneBemerkungen);
    jScrollPaneBemerkungen.setBounds(90, 270, 600, 120);

    jButtonNeuerKundeSpeichern.setText("Speichern");
    add(jButtonNeuerKundeSpeichern);
    jButtonNeuerKundeSpeichern.setBounds(270, 420, 110, 26);

    jLabelPLZ.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelPLZ.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelPLZ.setText("PLZ");
    add(jLabelPLZ);
    jLabelPLZ.setBounds(430, 120, 40, 20);

    jTextFieldNeuerKundePLZ.setDocument(new JTextFieldValidation(5));
    add(jTextFieldNeuerKundePLZ);
    jTextFieldNeuerKundePLZ.setBounds(480, 120, 40, 20);

    jLabelTelefon.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelTelefon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelTelefon.setText("Telefon");
    add(jLabelTelefon);
    jLabelTelefon.setBounds(-10, 150, 120, 20);

    jTextFieldNeuerKundeTelefon.setDocument(new JTextFieldValidation(30));
    add(jTextFieldNeuerKundeTelefon);
    jTextFieldNeuerKundeTelefon.setBounds(120, 150, 210, 20);

    jLabelFax.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelFax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelFax.setText("Fax");
    add(jLabelFax);
    jLabelFax.setBounds(350, 150, 120, 20);

    jTextFieldNeuerKundeFax.setDocument(new JTextFieldValidation(30));
    add(jTextFieldNeuerKundeFax);
    jTextFieldNeuerKundeFax.setBounds(480, 150, 210, 20);

    jLabelEMail.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelEMail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelEMail.setText("eMail");
    add(jLabelEMail);
    jLabelEMail.setBounds(-10, 180, 120, 20);

    jTextFieldNeuerKundeEMail.setDocument(new JTextFieldValidation(50));
    add(jTextFieldNeuerKundeEMail);
    jTextFieldNeuerKundeEMail.setBounds(120, 180, 210, 20);

    jLabelOrt.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelOrt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelOrt.setText("Ort");
    add(jLabelOrt);
    jLabelOrt.setBounds(80, 120, 30, 20);

    jTextFieldNeuerKundeOrt.setDocument(new JTextFieldValidation(50));
    add(jTextFieldNeuerKundeOrt);
    jTextFieldNeuerKundeOrt.setBounds(120, 120, 210, 20);

    jButtonNeuerKundeReset.setText("L\u00f6schen");
    add(jButtonNeuerKundeReset);
    jButtonNeuerKundeReset.setBounds(420, 420, 110, 26);

    add(jSeparator);
    jSeparator.setBounds(90, 220, 600, 10);

    jTextFieldNeuerKundeVorname.setDocument(new JTextFieldValidation(50));
    add(jTextFieldNeuerKundeVorname);
    jTextFieldNeuerKundeVorname.setBounds(480, 60, 210, 20);

    jComboBoxNeuerLieferantZuverlaessigkeit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3" }));
    jComboBoxNeuerLieferantZuverlaessigkeit.setEnabled(false);
    add(jComboBoxNeuerLieferantZuverlaessigkeit);
    jComboBoxNeuerLieferantZuverlaessigkeit.setBounds(650, 180, 40, 25);

    jLabelZahlungsmoral.setFont(new java.awt.Font("Dialog", 1, 14));
    jLabelZahlungsmoral.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelZahlungsmoral.setText("Zahlungsmoral");
    add(jLabelZahlungsmoral);
    jLabelZahlungsmoral.setBounds(520, 180, 120, 20);

  }//GEN-END:initComponents
	
	
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonNeuerKundeReset;
  private javax.swing.JButton jButtonNeuerKundeSpeichern;
  private javax.swing.JComboBox jComboBoxNeuerKundeKundentyp;
  private javax.swing.JComboBox jComboBoxNeuerLieferantZuverlaessigkeit;
  private javax.swing.JLabel jLabelEMail;
  private javax.swing.JLabel jLabelFax;
  private javax.swing.JLabel jLabelFirma;
  private javax.swing.JLabel jLabelKundentyp;
  private javax.swing.JLabel jLabelNachname;
  private javax.swing.JLabel jLabelNeuerKunde;
  private javax.swing.JLabel jLabelNotiz;
  private javax.swing.JLabel jLabelOrt;
  private javax.swing.JLabel jLabelPLZ;
  private javax.swing.JLabel jLabelStrasse;
  private javax.swing.JLabel jLabelTelefon;
  private javax.swing.JLabel jLabelVorname;
  private javax.swing.JLabel jLabelZahlungsmoral;
  private javax.swing.JScrollPane jScrollPaneBemerkungen;
  private javax.swing.JSeparator jSeparator;
  private javax.swing.JTextArea jTextAreaNeuerKundeNotiz;
  private javax.swing.JTextField jTextFieldNeuerKundeEMail;
  private javax.swing.JTextField jTextFieldNeuerKundeFax;
  private javax.swing.JTextField jTextFieldNeuerKundeFirma;
  private javax.swing.JTextField jTextFieldNeuerKundeNachname;
  private javax.swing.JTextField jTextFieldNeuerKundeOrt;
  private javax.swing.JTextField jTextFieldNeuerKundePLZ;
  private javax.swing.JTextField jTextFieldNeuerKundeStrasse;
  private javax.swing.JTextField jTextFieldNeuerKundeTelefon;
  private javax.swing.JTextField jTextFieldNeuerKundeVorname;
  // End of variables declaration//GEN-END:variables
	
}
