/*   ********************************************************************   **
**   Copyright notice                                                       **
**                                                                          **
**   (c) 2003 WiSim Development Team					                              **
**   http://wisim.sourceforge.net/   			                                  **
**                                                                          **
**   All rights reserved                                                    **
**                                                                          **
**   This script is part of the WiSim Business Game project. The WiSim      **
**   project is free software; you can redistribute it and/or modify        **
**   it under the terms of the GNU General Public License as published by   **
**   the Free Software Foundation; either version 2 of the License, or      **
**   (at your option) any later version.                                    **
**                                                                          **
**   The GNU General Public License can be found at                         **
**   http://www.gnu.org/copyleft/gpl.html.                                  **
**   A copy is found in the textfile GPL.txt and important notices to the   **
**   license from the team is found in the textfile LICENSE.txt distributed **
**   in these package.                                                      **
**                                                                          **
**   This copyright notice MUST APPEAR in all copies of the file!           **
**   ********************************************************************   */

/** JPanelNeuerVertrag
 *
 * @author  Kay Patzwald und Denise Freitag
 * Created on 10. Februar 2003, 18:43
 */

package net.sourceforge.wisim.controller;

import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Collection;
import java.util.GregorianCalendar;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import net.sourceforge.wisim.dao.WiSimDAO;
import net.sourceforge.wisim.dao.WiSimDAOException;
import net.sourceforge.wisim.dao.WiSimDAOWriteException;
import net.sourceforge.wisim.model.Article;
import net.sourceforge.wisim.model.Contract;
import net.sourceforge.wisim.model.ContractAccount;
import net.sourceforge.wisim.model.Customer;
import net.sourceforge.wisim.model.OrderItem;
import net.sourceforge.wisim.model.Validator;
import net.sourceforge.wisim.model.WiSimLogger;

/**
 * @author Denise Freitag
 */
public class JPanelNewContract extends JPanel {
	private WiSimDAO dao;
	private Hashtable kundeObjekt;
	//private Hashtable kundenTabelle;
	private Hashtable artikelTabelle;
	private Hashtable artikelObjekt;
	private float mwst;

	private Validator validate;
	private WiSimMainController wiSimMainController;
	//Logger
	private WiSimLogger wiSimLogger;

	private DecimalFormat form;

	/** Creates new form JPanelNeuerVertrag */
	public JPanelNewContract(WiSimMainController wiSimMainController) {
		this.wiSimMainController = wiSimMainController;
		initDAO(wiSimMainController);
		kundeObjekt = new Hashtable();
		//kundenTabelle = new Hashtable();
		artikelTabelle = new Hashtable();
		artikelObjekt = new Hashtable();
		validate = new Validator();
		initComponents();
		loadMwSt();
		form = new DecimalFormat("###,##0.00");
	}

	private void initDAO(WiSimMainController wiSimMainController) {
		dao = wiSimMainController.getDAO();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() { //GEN-BEGIN:initComponents
		jOptionAlert = new javax.swing.JOptionPane();
		jOptionPaneConfirm = new javax.swing.JOptionPane();
		jLabelNeuerVertrag = new javax.swing.JLabel();
		jPanelKundeWaehlen = new javax.swing.JPanel();
		jLabelKunde = new javax.swing.JLabel();
		jComboBoxKunde = new javax.swing.JComboBox();
		jPanelKundendaten = new javax.swing.JPanel();
		jLabelNeuerVertragKundenTyp = new javax.swing.JLabel();
		jTextFieldNeuerVertragKundentyp = new javax.swing.JTextField();
		jLabelNeuerVertragAnsprueche = new javax.swing.JLabel();
		jTextFieldNeuerVertragAnsprueche = new javax.swing.JTextField();
		jLabelNeuerVertragZahlungsmoral = new javax.swing.JLabel();
		jTextFieldNeuerVertragZahlungsmoral = new javax.swing.JTextField();
		jLabelNeuerVertragAnzahlVertraege = new javax.swing.JLabel();
		jTextFieldNeuerVertragAnzahlVertraege = new javax.swing.JTextField();
		jPanelArtikelWaehlen = new javax.swing.JPanel();
		jLabelArtikel = new javax.swing.JLabel();
		jComboBoxArtikel = new javax.swing.JComboBox();
		jLabelNeuerVertragAbnahmemenge = new javax.swing.JLabel();
		jTextFieldNeuerVertragAbnahmemenge = new javax.swing.JTextField();
		jLabelZwischensumme1 = new javax.swing.JLabel();
		jTextFieldNeuerVertragIntermediateResult1 = new javax.swing.JTextField();
		jLabelEUR1 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jLabelStueckpreis = new javax.swing.JLabel();
		jTextFieldNeuerVertragStueckpreis = new javax.swing.JTextField();
		jLabelEUR2 = new javax.swing.JLabel();
		jPanelBestelldatenEingeben = new javax.swing.JPanel();
		jLabelNeuerVertragLieferdatum = new javax.swing.JLabel();
		jTextFieldNeuerVertragTag = new javax.swing.JTextField();
		jTextFieldNeuerVertragMonat = new javax.swing.JTextField();
		jTextFieldNeuerVertragJahr = new javax.swing.JTextField();
		jLabelRabatt = new javax.swing.JLabel();
		jTextFieldRabatt = new javax.swing.JTextField();
		jLabelSkonto = new javax.swing.JLabel();
		jTextFieldSkonto = new javax.swing.JTextField();
		jLabelNeuerVertragNettozahldatum = new javax.swing.JLabel();
		jLabelProzent2 = new javax.swing.JLabel();
		jLabelSkontofrist = new javax.swing.JLabel();
		jTextFieldSkontofristTage = new javax.swing.JTextField();
		jLabelTage = new javax.swing.JLabel();
		jLabelProzent1 = new javax.swing.JLabel();
		jTextFieldNeuerVertragNettozahldatum = new javax.swing.JTextField();
		jPanelAngebotspreis = new javax.swing.JPanel();
		jLabelZwischensumme2 = new javax.swing.JLabel();
		jTextFieldNeuerVertragIntermediateResult2 = new javax.swing.JTextField();
		jLabelEUR = new javax.swing.JLabel();
		jTextFieldMwst = new javax.swing.JTextField();
		jLabelProzent = new javax.swing.JLabel();
		jLabelMwst = new javax.swing.JLabel();
		jTextFieldNeuerVertragAngebotspreisMwST = new javax.swing.JTextField();
		jLabelRabatt2 = new javax.swing.JLabel();
		jTextFieldNeuerVertragAngebotspreisOhneRabatt = new javax.swing.JTextField();
		jLabelSkonto2 = new javax.swing.JLabel();
		jTextFieldNeuerVertragAngebotspreisOhneSkonto = new javax.swing.JTextField();
		jLabelEUR3 = new javax.swing.JLabel();
		jLabelEUR4 = new javax.swing.JLabel();
		jLabelEUR5 = new javax.swing.JLabel();
		jLabelZwischensumme3 = new javax.swing.JLabel();
		jTextFieldNeuerVertragIntermediateResult3 = new javax.swing.JTextField();
		jLabelEUR6 = new javax.swing.JLabel();
		jTextFieldNeuerVertragAngebotspreis = new javax.swing.JTextField();
		jLabelAngebotspreis = new javax.swing.JLabel();
		jLabelEUR7 = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		jLabelMinus = new javax.swing.JLabel();
		jLabelGleich = new javax.swing.JLabel();
		jLabelMinus2 = new javax.swing.JLabel();
		jLabelGleich2 = new javax.swing.JLabel();
		jLabelGleich3 = new javax.swing.JLabel();
		jButtonNeuerVertragSpeichern = new javax.swing.JButton();
		jButtonNeuerVertragAbbrechen = new javax.swing.JButton();

		jOptionAlert.setMessageType(0);
		jOptionPaneConfirm.setMessageType(0);

		setLayout(null);

		setPreferredSize(new java.awt.Dimension(800, 600));
		jLabelNeuerVertrag.setFont(new java.awt.Font("Dialog", 1, 24));
		jLabelNeuerVertrag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelNeuerVertrag.setText("Neuer Vertrag");
		add(jLabelNeuerVertrag);
		jLabelNeuerVertrag.setBounds(0, 0, 810, 40);

		jPanelKundeWaehlen.setLayout(null);

		jPanelKundeWaehlen.setBorder(new javax.swing.border.TitledBorder("1. Kunden ausw\u00e4hlen"));
		jLabelKunde.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelKunde.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabelKunde.setText("Kunde");
		jPanelKundeWaehlen.add(jLabelKunde);
		jLabelKunde.setBounds(40, 30, 80, 19);

		jComboBoxKunde.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxKundeActionPerformed(evt);
			}
		});
		jComboBoxKunde.addAncestorListener(new javax.swing.event.AncestorListener() {
			public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
			}
			public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
				jComboBoxKundeAncestorAdded(evt);
			}
			public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
			}
		});

		jPanelKundeWaehlen.add(jComboBoxKunde);
		jComboBoxKunde.setBounds(170, 30, 170, 20);

		jPanelKundendaten.setLayout(null);

		jPanelKundendaten.setBorder(new javax.swing.border.TitledBorder(null, "Kundendaten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
		jLabelNeuerVertragKundenTyp.setText("Kundentyp");
		jPanelKundendaten.add(jLabelNeuerVertragKundenTyp);
		jLabelNeuerVertragKundenTyp.setBounds(20, 20, 60, 16);

		jTextFieldNeuerVertragKundentyp.setEditable(false);
		jTextFieldNeuerVertragKundentyp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanelKundendaten.add(jTextFieldNeuerVertragKundentyp);
		jTextFieldNeuerVertragKundentyp.setBounds(150, 20, 20, 20);

		jLabelNeuerVertragAnsprueche.setText("Anspr\u00fcche");
		jPanelKundendaten.add(jLabelNeuerVertragAnsprueche);
		jLabelNeuerVertragAnsprueche.setBounds(20, 50, 62, 16);

		jTextFieldNeuerVertragAnsprueche.setEditable(false);
		jTextFieldNeuerVertragAnsprueche.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanelKundendaten.add(jTextFieldNeuerVertragAnsprueche);
		jTextFieldNeuerVertragAnsprueche.setBounds(150, 50, 130, 20);

		jLabelNeuerVertragZahlungsmoral.setText("Zahlungsmoral");
		jPanelKundendaten.add(jLabelNeuerVertragZahlungsmoral);
		jLabelNeuerVertragZahlungsmoral.setBounds(20, 80, 90, 16);

		jTextFieldNeuerVertragZahlungsmoral.setEditable(false);
		jTextFieldNeuerVertragZahlungsmoral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanelKundendaten.add(jTextFieldNeuerVertragZahlungsmoral);
		jTextFieldNeuerVertragZahlungsmoral.setBounds(150, 80, 20, 20);

		jLabelNeuerVertragAnzahlVertraege.setText("weitere Vertr\u00e4ge");
		jPanelKundendaten.add(jLabelNeuerVertragAnzahlVertraege);
		jLabelNeuerVertragAnzahlVertraege.setBounds(20, 110, 100, 16);

		jTextFieldNeuerVertragAnzahlVertraege.setEditable(false);
		jTextFieldNeuerVertragAnzahlVertraege.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanelKundendaten.add(jTextFieldNeuerVertragAnzahlVertraege);
		jTextFieldNeuerVertragAnzahlVertraege.setBounds(150, 110, 20, 20);

		jPanelKundeWaehlen.add(jPanelKundendaten);
		jPanelKundendaten.setBounds(30, 60, 310, 140);

		add(jPanelKundeWaehlen);
		jPanelKundeWaehlen.setBounds(40, 50, 360, 210);

		jPanelArtikelWaehlen.setLayout(null);

		jPanelArtikelWaehlen.setBorder(new javax.swing.border.TitledBorder("2. Artikel ausw\u00e4hlen"));
		jLabelArtikel.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelArtikel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabelArtikel.setText("Artikel");
		jPanelArtikelWaehlen.add(jLabelArtikel);
		jLabelArtikel.setBounds(40, 40, 80, 19);

		jComboBoxArtikel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxArtikelActionPerformed(evt);
			}
		});
		jComboBoxArtikel.addAncestorListener(new javax.swing.event.AncestorListener() {
			public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
			}
			public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
				jComboBoxArtikelAncestorAdded(evt);
			}
			public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
			}
		});

		jPanelArtikelWaehlen.add(jComboBoxArtikel);
		jComboBoxArtikel.setBounds(150, 40, 150, 20);

		jLabelNeuerVertragAbnahmemenge.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelNeuerVertragAbnahmemenge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabelNeuerVertragAbnahmemenge.setText("Abnahmemenge");
		jPanelArtikelWaehlen.add(jLabelNeuerVertragAbnahmemenge);
		jLabelNeuerVertragAbnahmemenge.setBounds(30, 130, 120, 16);

		jTextFieldNeuerVertragAbnahmemenge.setDocument(new Validator(10));
		jTextFieldNeuerVertragAbnahmemenge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jTextFieldNeuerVertragAbnahmemenge.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextFieldNeuerVertragAbnahmemengeFocusLost(evt);
			}
		});

		jPanelArtikelWaehlen.add(jTextFieldNeuerVertragAbnahmemenge);
		jTextFieldNeuerVertragAbnahmemenge.setBounds(180, 130, 120, 20);

		jLabelZwischensumme1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabelZwischensumme1.setText("Zwischensumme 1");
		jPanelArtikelWaehlen.add(jLabelZwischensumme1);
		jLabelZwischensumme1.setBounds(30, 170, 120, 16);

		jTextFieldNeuerVertragIntermediateResult1.setEditable(false);
		jTextFieldNeuerVertragIntermediateResult1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jPanelArtikelWaehlen.add(jTextFieldNeuerVertragIntermediateResult1);
		jTextFieldNeuerVertragIntermediateResult1.setBounds(180, 170, 120, 20);

		jLabelEUR1.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelEUR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelEUR1.setText("\u20ac");
		jPanelArtikelWaehlen.add(jLabelEUR1);
		jLabelEUR1.setBounds(310, 170, 10, 20);

		jPanelArtikelWaehlen.add(jSeparator1);
		jSeparator1.setBounds(30, 160, 290, 10);

		jLabelStueckpreis.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelStueckpreis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabelStueckpreis.setText("St\u00fcckpreis");
		jPanelArtikelWaehlen.add(jLabelStueckpreis);
		jLabelStueckpreis.setBounds(30, 100, 80, 20);

		jTextFieldNeuerVertragStueckpreis.setEditable(false);
		jTextFieldNeuerVertragStueckpreis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jPanelArtikelWaehlen.add(jTextFieldNeuerVertragStueckpreis);
		jTextFieldNeuerVertragStueckpreis.setBounds(180, 100, 120, 20);

		jLabelEUR2.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelEUR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelEUR2.setText("\u20ac");
		jPanelArtikelWaehlen.add(jLabelEUR2);
		jLabelEUR2.setBounds(310, 100, 10, 20);

		add(jPanelArtikelWaehlen);
		jPanelArtikelWaehlen.setBounds(410, 50, 340, 210);

		jPanelBestelldatenEingeben.setLayout(null);

		jPanelBestelldatenEingeben.setBorder(new javax.swing.border.TitledBorder("3. Bestelldaten eingeben"));
		jLabelNeuerVertragLieferdatum.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelNeuerVertragLieferdatum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabelNeuerVertragLieferdatum.setText("Lieferdatum");
		jPanelBestelldatenEingeben.add(jLabelNeuerVertragLieferdatum);
		jLabelNeuerVertragLieferdatum.setBounds(40, 40, 90, 19);

		jTextFieldNeuerVertragTag.setDocument(new Validator(2));
		jTextFieldNeuerVertragTag.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextFieldNeuerVertragTag.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextFieldNeuerVertragTagFocusLost(evt);
			}
		});

		jPanelBestelldatenEingeben.add(jTextFieldNeuerVertragTag);
		jTextFieldNeuerVertragTag.setBounds(180, 40, 30, 20);

		jTextFieldNeuerVertragMonat.setDocument(new Validator(2));
		jTextFieldNeuerVertragMonat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextFieldNeuerVertragMonat.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextFieldNeuerVertragMonatFocusLost(evt);
			}
		});

		jPanelBestelldatenEingeben.add(jTextFieldNeuerVertragMonat);
		jTextFieldNeuerVertragMonat.setBounds(210, 40, 30, 20);

		jTextFieldNeuerVertragJahr.setDocument(new Validator(4));
		jTextFieldNeuerVertragJahr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextFieldNeuerVertragJahr.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextFieldNeuerVertragJahrFocusLost(evt);
			}
		});

		jPanelBestelldatenEingeben.add(jTextFieldNeuerVertragJahr);
		jTextFieldNeuerVertragJahr.setBounds(240, 40, 50, 20);

		jLabelRabatt.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelRabatt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabelRabatt.setText("Rabatt");
		jPanelBestelldatenEingeben.add(jLabelRabatt);
		jLabelRabatt.setBounds(40, 70, 50, 20);

		jTextFieldRabatt.setDocument(new Validator(5));
		jTextFieldRabatt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jTextFieldRabatt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextFieldRabattFocusLost(evt);
			}
		});

		jPanelBestelldatenEingeben.add(jTextFieldRabatt);
		jTextFieldRabatt.setBounds(180, 70, 40, 20);

		jLabelSkonto.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelSkonto.setText("Skonto");
		jPanelBestelldatenEingeben.add(jLabelSkonto);
		jLabelSkonto.setBounds(40, 100, 60, 16);

		jTextFieldSkonto.setDocument(new Validator(5));
		jTextFieldSkonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jTextFieldSkonto.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextFieldSkontoFocusLost(evt);
			}
		});

		jPanelBestelldatenEingeben.add(jTextFieldSkonto);
		jTextFieldSkonto.setBounds(180, 100, 40, 20);

		jLabelNeuerVertragNettozahldatum.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelNeuerVertragNettozahldatum.setText("Nettozahldatum");
		jPanelBestelldatenEingeben.add(jLabelNeuerVertragNettozahldatum);
		jLabelNeuerVertragNettozahldatum.setBounds(40, 160, 110, 19);

		jLabelProzent2.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelProzent2.setText("%");
		jPanelBestelldatenEingeben.add(jLabelProzent2);
		jLabelProzent2.setBounds(230, 100, 10, 19);

		jLabelSkontofrist.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelSkontofrist.setText("Skontofrist");
		jPanelBestelldatenEingeben.add(jLabelSkontofrist);
		jLabelSkontofrist.setBounds(40, 130, 80, 19);

		jTextFieldSkontofristTage.setDocument(new Validator(5));
		jTextFieldSkontofristTage.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jTextFieldSkontofristTage.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextFieldSkontofristTageFocusLost(evt);
			}
		});

		jPanelBestelldatenEingeben.add(jTextFieldSkontofristTage);
		jTextFieldSkontofristTage.setBounds(180, 130, 40, 20);

		jLabelTage.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelTage.setText("Tage");
		jPanelBestelldatenEingeben.add(jLabelTage);
		jLabelTage.setBounds(230, 130, 34, 19);

		jLabelProzent1.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelProzent1.setText("%");
		jPanelBestelldatenEingeben.add(jLabelProzent1);
		jLabelProzent1.setBounds(230, 70, 10, 19);

		jTextFieldNeuerVertragNettozahldatum.setEditable(false);
		jTextFieldNeuerVertragNettozahldatum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jPanelBestelldatenEingeben.add(jTextFieldNeuerVertragNettozahldatum);
		jTextFieldNeuerVertragNettozahldatum.setBounds(180, 160, 110, 20);

		add(jPanelBestelldatenEingeben);
		jPanelBestelldatenEingeben.setBounds(40, 270, 360, 230);

		jPanelAngebotspreis.setLayout(null);

		jPanelAngebotspreis.setBorder(new javax.swing.border.TitledBorder("4. Vertrag"));
		jLabelZwischensumme2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabelZwischensumme2.setText("Zwischensumme 2");
		jPanelAngebotspreis.add(jLabelZwischensumme2);
		jLabelZwischensumme2.setBounds(10, 30, 110, 20);

		jTextFieldNeuerVertragIntermediateResult2.setEditable(false);
		jTextFieldNeuerVertragIntermediateResult2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jPanelAngebotspreis.add(jTextFieldNeuerVertragIntermediateResult2);
		jTextFieldNeuerVertragIntermediateResult2.setBounds(150, 30, 150, 20);

		jLabelEUR.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelEUR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelEUR.setText("\u20ac");
		jPanelAngebotspreis.add(jLabelEUR);
		jLabelEUR.setBounds(310, 30, 10, 20);

		jTextFieldMwst.setEditable(false);
		jTextFieldMwst.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jPanelAngebotspreis.add(jTextFieldMwst);
		jTextFieldMwst.setBounds(80, 200, 30, 20);

		jLabelProzent.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabelProzent.setText("%");
		jPanelAngebotspreis.add(jLabelProzent);
		jLabelProzent.setBounds(110, 200, 10, 19);

		jLabelMwst.setText("Incl. MwSt");
		jPanelAngebotspreis.add(jLabelMwst);
		jLabelMwst.setBounds(10, 200, 60, 20);

		jTextFieldNeuerVertragAngebotspreisMwST.setEditable(false);
		jTextFieldNeuerVertragAngebotspreisMwST.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jPanelAngebotspreis.add(jTextFieldNeuerVertragAngebotspreisMwST);
		jTextFieldNeuerVertragAngebotspreisMwST.setBounds(150, 200, 150, 20);

		jLabelRabatt2.setText("Abzg. Rabatt");
		jPanelAngebotspreis.add(jLabelRabatt2);
		jLabelRabatt2.setBounds(10, 60, 90, 20);

		jTextFieldNeuerVertragAngebotspreisOhneRabatt.setEditable(false);
		jTextFieldNeuerVertragAngebotspreisOhneRabatt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jPanelAngebotspreis.add(jTextFieldNeuerVertragAngebotspreisOhneRabatt);
		jTextFieldNeuerVertragAngebotspreisOhneRabatt.setBounds(150, 60, 150, 20);

		jLabelSkonto2.setText("Abzg. Skonto");
		jPanelAngebotspreis.add(jLabelSkonto2);
		jLabelSkonto2.setBounds(10, 130, 90, 20);

		jTextFieldNeuerVertragAngebotspreisOhneSkonto.setEditable(false);
		jTextFieldNeuerVertragAngebotspreisOhneSkonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jPanelAngebotspreis.add(jTextFieldNeuerVertragAngebotspreisOhneSkonto);
		jTextFieldNeuerVertragAngebotspreisOhneSkonto.setBounds(150, 130, 150, 20);

		jLabelEUR3.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelEUR3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelEUR3.setText("\u20ac");
		jPanelAngebotspreis.add(jLabelEUR3);
		jLabelEUR3.setBounds(310, 60, 10, 20);

		jLabelEUR4.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelEUR4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelEUR4.setText("\u20ac");
		jPanelAngebotspreis.add(jLabelEUR4);
		jLabelEUR4.setBounds(310, 130, 10, 20);

		jLabelEUR5.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelEUR5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelEUR5.setText("\u20ac");
		jPanelAngebotspreis.add(jLabelEUR5);
		jLabelEUR5.setBounds(310, 200, 10, 20);

		jLabelZwischensumme3.setText("Zwischensumme 3");
		jPanelAngebotspreis.add(jLabelZwischensumme3);
		jLabelZwischensumme3.setBounds(10, 100, 110, 20);

		jTextFieldNeuerVertragIntermediateResult3.setEditable(false);
		jTextFieldNeuerVertragIntermediateResult3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jPanelAngebotspreis.add(jTextFieldNeuerVertragIntermediateResult3);
		jTextFieldNeuerVertragIntermediateResult3.setBounds(150, 100, 150, 20);

		jLabelEUR6.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelEUR6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelEUR6.setText("\u20ac");
		jPanelAngebotspreis.add(jLabelEUR6);
		jLabelEUR6.setBounds(310, 100, 10, 20);

		jTextFieldNeuerVertragAngebotspreis.setEditable(false);
		jTextFieldNeuerVertragAngebotspreis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jPanelAngebotspreis.add(jTextFieldNeuerVertragAngebotspreis);
		jTextFieldNeuerVertragAngebotspreis.setBounds(150, 170, 150, 20);

		jLabelAngebotspreis.setText("Angebotspreis");
		jPanelAngebotspreis.add(jLabelAngebotspreis);
		jLabelAngebotspreis.setBounds(10, 170, 90, 20);

		jLabelEUR7.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelEUR7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelEUR7.setText("\u20ac");
		jPanelAngebotspreis.add(jLabelEUR7);
		jLabelEUR7.setBounds(310, 170, 10, 20);

		jPanelAngebotspreis.add(jSeparator2);
		jSeparator2.setBounds(10, 90, 310, 10);

		jPanelAngebotspreis.add(jSeparator3);
		jSeparator3.setBounds(10, 160, 310, 10);

		jLabelMinus.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelMinus.setText("-");
		jPanelAngebotspreis.add(jLabelMinus);
		jLabelMinus.setBounds(130, 60, 20, 20);

		jLabelGleich.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelGleich.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelGleich.setText("=");
		jPanelAngebotspreis.add(jLabelGleich);
		jLabelGleich.setBounds(130, 100, 20, 20);

		jLabelMinus2.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelMinus2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelMinus2.setText("-");
		jPanelAngebotspreis.add(jLabelMinus2);
		jLabelMinus2.setBounds(130, 130, 20, 20);

		jLabelGleich2.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelGleich2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelGleich2.setText("=");
		jPanelAngebotspreis.add(jLabelGleich2);
		jLabelGleich2.setBounds(130, 170, 20, 20);

		jLabelGleich3.setFont(new java.awt.Font("Dialog", 1, 18));
		jLabelGleich3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelGleich3.setText("=");
		jPanelAngebotspreis.add(jLabelGleich3);
		jLabelGleich3.setBounds(130, 200, 20, 20);

		add(jPanelAngebotspreis);
		jPanelAngebotspreis.setBounds(410, 270, 340, 230);

		jButtonNeuerVertragSpeichern.setFont(new java.awt.Font("Dialog", 1, 11));
		jButtonNeuerVertragSpeichern.setText("Speichern");
		jButtonNeuerVertragSpeichern.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonNeuerVertragSpeichernActionPerformed(evt);
			}
		});

		add(jButtonNeuerVertragSpeichern);
		jButtonNeuerVertragSpeichern.setBounds(260, 510, 120, 25);

		jButtonNeuerVertragAbbrechen.setFont(new java.awt.Font("Dialog", 1, 11));
		jButtonNeuerVertragAbbrechen.setText("Abbrechen");
		jButtonNeuerVertragAbbrechen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonNeuerVertragAbbrechenActionPerformed(evt);
			}
		});

		add(jButtonNeuerVertragAbbrechen);
		jButtonNeuerVertragAbbrechen.setBounds(430, 510, 120, 25);

	} //GEN-END:initComponents

	private void jTextFieldSkontofristTageFocusLost(java.awt.event.FocusEvent evt) { //GEN-FIRST:event_jTextFieldSkontofristTageFocusLost
		checkCashDiscountLimit();
	} //GEN-LAST:event_jTextFieldSkontofristTageFocusLost

	private void jTextFieldNeuerVertragJahrFocusLost(java.awt.event.FocusEvent evt) { //GEN-FIRST:event_jTextFieldNeuerVertragJahrFocusLost
		checkDateYear();
	} //GEN-LAST:event_jTextFieldNeuerVertragJahrFocusLost

	private void jTextFieldNeuerVertragMonatFocusLost(java.awt.event.FocusEvent evt) { //GEN-FIRST:event_jTextFieldNeuerVertragMonatFocusLost
		checkDateMonth();
	} //GEN-LAST:event_jTextFieldNeuerVertragMonatFocusLost

	private void jTextFieldNeuerVertragTagFocusLost(java.awt.event.FocusEvent evt) { //GEN-FIRST:event_jTextFieldNeuerVertragTagFocusLost
		checkDateDay();
	} //GEN-LAST:event_jTextFieldNeuerVertragTagFocusLost

	private void jComboBoxKundeActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jComboBoxKundeActionPerformed
		loadCustomerData();
	} //GEN-LAST:event_jComboBoxKundeActionPerformed

	private void jTextFieldSkontoFocusLost(java.awt.event.FocusEvent evt) { //GEN-FIRST:event_jTextFieldSkontoFocusLost
		checkCashDiscount();
		calculate();
	} //GEN-LAST:event_jTextFieldSkontoFocusLost

	private void jTextFieldRabattFocusLost(java.awt.event.FocusEvent evt) { //GEN-FIRST:event_jTextFieldRabattFocusLost
		checkDiscount();
		calculate();
	} //GEN-LAST:event_jTextFieldRabattFocusLost

	private void jTextFieldNeuerVertragAbnahmemengeFocusLost(java.awt.event.FocusEvent evt) { //GEN-FIRST:event_jTextFieldNeuerVertragAbnahmemengeFocusLost
		checkPurchaseAmount();
		calculate();
	} //GEN-LAST:event_jTextFieldNeuerVertragAbnahmemengeFocusLost

	private void jComboBoxArtikelActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jComboBoxArtikelActionPerformed
		loadPrice();
	} //GEN-LAST:event_jComboBoxArtikelActionPerformed

	private void jComboBoxArtikelAncestorAdded(javax.swing.event.AncestorEvent evt) { //GEN-FIRST:event_jComboBoxArtikelAncestorAdded
		loadArticle();
	} //GEN-LAST:event_jComboBoxArtikelAncestorAdded

	private void jComboBoxKundeAncestorAdded(javax.swing.event.AncestorEvent evt) { //GEN-FIRST:event_jComboBoxKundeAncestorAdded
		loadCustomer();
	} //GEN-LAST:event_jComboBoxKundeAncestorAdded

	private void jButtonNeuerVertragAbbrechenActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButtonNeuerVertragAbbrechenActionPerformed
		clearFields();
	} //GEN-LAST:event_jButtonNeuerVertragAbbrechenActionPerformed

	private void jButtonNeuerVertragSpeichernActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButtonNeuerVertragSpeichernActionPerformed
		saveContract();
	} //GEN-LAST:event_jButtonNeuerVertragSpeichernActionPerformed

	/**
	 * Method pruefeSkontofrist. Überprüft, ob eine Zahl und das etwas eingegeben wurde.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	private void checkCashDiscountLimit() {

		String skontofrist = jTextFieldSkontofristTage.getText();
		boolean skontofristOk = false;
		if (!skontofrist.equals("") && skontofrist != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird die Skontofrist immer wieder überprüft
			while (!skontofristOk && skontofrist != null) {
				//Erlaubt sind nur Eingaben von Zahlen
				if (!validate.checkZahl(skontofrist)) {
					jOptionPaneConfirm.setWantsInput(true);
					skontofrist = JOptionPane.showInputDialog(this, "Ungültige Skontofrist! Bitte neu eingeben:", skontofrist);
				} else {
					skontofristOk = true;
				}
			}
			if (skontofrist != null) {
				jTextFieldSkontofristTage.setText(skontofrist);
			} else {
				jTextFieldSkontofristTage.setText("");
			}
		}

		//Das Nettozahldatum wird erzeugt
		if (!jTextFieldSkontofristTage.getText().equals("") && !jTextFieldSkontofristTage.getText().equals("0")) {

			long nettoDatumMili = wiSimMainController.getActDate().getTime() + (Long.parseLong(jTextFieldSkontofristTage.getText()) * 1000 * 60 * 60 * 24);
			GregorianCalendar nettoDatum = new GregorianCalendar();
			nettoDatum.setTimeInMillis(nettoDatumMili);

			String tag = String.valueOf(nettoDatum.get(Calendar.DATE));
			String monat = String.valueOf(nettoDatum.get(Calendar.MONTH) + 1);
			String jahr = String.valueOf(nettoDatum.get(Calendar.YEAR));
			jTextFieldNeuerVertragNettozahldatum.setText(tag + "." + monat + "." + jahr);
		} else {
			jTextFieldNeuerVertragNettozahldatum.setText("Keins vorhanden!");
		}
	}

	/**
	 * Method pruefeSkonto. Überprüft, ob ein korrekter Skontowert eingegeben wurde.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	private void checkCashDiscount() {

		String skonto = jTextFieldSkonto.getText();

		boolean skontoOk = false;

		if (!skonto.equals("") && skonto != null) {

			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird der Skontowert immer wieder geprüft
			while (!skontoOk && skonto != null) {
				/*Erlaubt sind nur Eingaben von 1- oder 2-stellige Zahlen mit 1 Nachkommastelle
				getrennt durch einen Punkt*/

				if (!validate.checkPercent(skonto)) {
					jOptionPaneConfirm.setWantsInput(true);
					skonto = JOptionPane.showInputDialog(this, "Ungültiger Skonto-Wert (Format: xx.xx)! Bitte neu eingeben:", skonto);
				} else {
					skontoOk = true;
				}
			}
			if (skonto != null) {
				jTextFieldSkonto.setText(skonto);
			} else {
				jTextFieldSkonto.setText("");
			}

		}
	}

	/**
	 * Method pruefeRabatt. Überprüft, ob ein korrekter Rabattwert eingegeben wurde.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	private void checkDiscount() {

		String rabatt = jTextFieldRabatt.getText();

		boolean rabattOk = false;

		if (!rabatt.equals("") && rabatt != null) {

			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird der Rabatt immer wieder überprüft
			while (!rabattOk && rabatt != null) {
				/*Erlaubt sind nur Eingaben von 1- oder 2-stellige Zahlen mit 1 Nachkommastelle
				getrennt durch einen Punkt*/

				if (!validate.checkPercent(rabatt)) {
					jOptionPaneConfirm.setWantsInput(true);
					rabatt = JOptionPane.showInputDialog(this, "Ungültiger Rabatt (Format: xx.xx)! Bitte neu eingeben:", rabatt);
				} else {
					rabattOk = true;
				}
			}
			if (rabatt == null) {
				jTextFieldRabatt.setText("");
			} else {
				jTextFieldRabatt.setText(rabatt);
			}
		}
	}

	/**
	 * Method pruefeLieferdatumTag. Überprüft den eingegebenen Lieferdatumstag.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	private void checkDateDay() {
		String lieferdatum = jTextFieldNeuerVertragTag.getText();
		boolean lieferdatumOk = false;
		if (!lieferdatum.equals("") && lieferdatum != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird das Lieferdatum immer wieder überprüft
			while (!lieferdatumOk && lieferdatum != null) {
				//Erlaubt sind nur Eingaben von 1- oder 2-stellige Zahlen
				if (!validate.checkTwoDigits(lieferdatum) || Integer.parseInt(lieferdatum) > 31) {
					jOptionPaneConfirm.setWantsInput(true);
					lieferdatum = JOptionPane.showInputDialog(this, "Ungültiger Tag! Bitte neu eingeben:", lieferdatum);
				} else {
					lieferdatumOk = true;
				}
			}
			if (lieferdatum != null) {
				jTextFieldNeuerVertragTag.setText(lieferdatum);
			} else {
				jTextFieldNeuerVertragTag.setText("");
			}
		}
	}

	/**
	 * Method pruefeLieferdatumMonat. Überprüft den eingegebenen Lieferdatumsmonat.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	private void checkDateMonth() {
		String lieferdatum = jTextFieldNeuerVertragMonat.getText();
		boolean lieferdatumOk = false;
		if (!lieferdatum.equals("") && lieferdatum != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird das Lieferdatum immer wieder überprüft
			while (!lieferdatumOk && lieferdatum != null) {
				//Erlaubt sind nur Eingaben von 1- oder 2-stellige Zahlen || Monatsangabe darf nicht größer 12 sein
				if (!validate.checkTwoDigits(lieferdatum) || Integer.parseInt(lieferdatum) > 12) {
					jOptionPaneConfirm.setWantsInput(true);
					lieferdatum = JOptionPane.showInputDialog(this, "Ungültiger Monat! Bitte neu eingeben:", lieferdatum);
				} else {
					lieferdatumOk = true;
				}
			}
			if (lieferdatum != null) {
				jTextFieldNeuerVertragMonat.setText(lieferdatum);
			} else {
				jTextFieldNeuerVertragMonat.setText("");
			}
		}
	}

	/**
	 * Method pruefeLieferdatumJahr. Überprüft das eingegebene Lieferdatumsjahr.
	 * Wenn vom Benutzer etwas falsches eingegeben wurde, wird er zu Korrektueingabe
	 * aufgefordert.
	 */
	private void checkDateYear() {
		String lieferdatum = jTextFieldNeuerVertragJahr.getText();
		boolean lieferdatumOk = false;
		if (!lieferdatum.equals("") && lieferdatum != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird das Lieferdatum immer wieder überprüft
			while (!lieferdatumOk && lieferdatum != null) {
				/*Erlaubt sind nur Eingaben von 4-stelligen Zahlen die nicht mit 0 beginnen*/
				if (!validate.checkYear(lieferdatum)) {
					jOptionPaneConfirm.setWantsInput(true);
					lieferdatum = JOptionPane.showInputDialog(this, "Ungültiges Jahr! Bitte neu eingeben:", lieferdatum);
				} else {
					lieferdatumOk = true;
				}
			}
			if (lieferdatum != null) {
				jTextFieldNeuerVertragJahr.setText(lieferdatum);
			} else {
				jTextFieldNeuerVertragJahr.setText("");
			}
		}
	}

	/**
	 * Method pruefeAbnahmemenge. Überprüft die Abnahmemenge.
	 * Wenn der Benutzer etwas falsche eingibt, wird er zur Korrektureingabe
	 * gefordert.
	 */
	private void checkPurchaseAmount() {
		String abnahmemenge = jTextFieldNeuerVertragAbnahmemenge.getText();
		boolean abnahmemengeOk = false;
		if (!abnahmemenge.equals("") && abnahmemenge != null) {
			//So lange der Benutzer keine richtige Eingabe gemacht hat und nicht auf Abbrechen geklickt hat wird die Abnahmemenge immer wieder überprüft
			while (!abnahmemengeOk && abnahmemenge != null) {
				/*Erlaubt sind nur Eingaben von Zahlen und nur 10-stellig*/
				if (!validate.checkZahl(abnahmemenge)) {
					jOptionPaneConfirm.setWantsInput(true);
					abnahmemenge = JOptionPane.showInputDialog(this, "Ungültige Mengenangabe (Format: 1 - 999)! Bitte neu eingeben:", abnahmemenge);
				} else {
					abnahmemengeOk = true;
				}
			}
			if (abnahmemenge != null) {
				jTextFieldNeuerVertragAbnahmemenge.setText(abnahmemenge);
			} else {
				jTextFieldNeuerVertragAbnahmemenge.setText("");
			}

		}
	}

	/** Gets the discount from the form.
	 * 
	 * @return double Discount
	 */
	private double getDiscount() {
		double discount = 0;
		String discountString = jTextFieldRabatt.getText();
		if (!discountString.equals("") && validate.checkPercent(discountString)) {
			if (discountString.matches("^[0-9]*[,][0-9]*")) {
				discountString = discountString.replaceAll(",", ".");
			}

			discount = Double.parseDouble(discountString);

		}
		return discount;
	}

	/** Gets the cash discount from the form.
	 * 
	 * @return double CashDiscount
	 */
	private double getCashDiscount() {
		double cashDiscount = 0;
		String cashDiscountString = jTextFieldSkonto.getText();
		if (!cashDiscountString.equals("") && validate.checkPercent(cashDiscountString)) {

			if (cashDiscountString.matches("^[0-9]*[,][0-9]*")) {
				cashDiscountString = cashDiscountString.replaceAll(",", ".");
			}
			cashDiscount = Double.parseDouble(cashDiscountString);

		}
		return cashDiscount;
	}

	/** Gets the price from the form.
	 * 
	 * @return double Prise
	 */
	private double getPrice() {
		double price = 0;
		if (!jTextFieldNeuerVertragStueckpreis.getText().equals("")) {
			try {
				price = form.parse(jTextFieldNeuerVertragStueckpreis.getText()).doubleValue();
			} catch (ParseException e) {
				wiSimLogger.log(Level.WARNING, "JPanelNeuerVertrag.getPrice", e, false);
			}
		}
		return price;
	}

	/** Gets the amount from the form.
	 * 
	 * @return double Amount
	 */
	private double getAmount() {
		int amount = 0;
		if (!jTextFieldNeuerVertragAbnahmemenge.getText().equals("")) {
			amount = Integer.parseInt(jTextFieldNeuerVertragAbnahmemenge.getText());
		}
		return amount;
	}

	/** Calculates the offer price and all intermediate results */
	private void calculate() {
		double iResult1 = 0, iResult2 = 0, iResult3 = 0;
		double discount = 0, cashDiscount = 0, offerPrice = 0, offerPriceWithMwST = 0;
		// Calculate intermediate result 1
		iResult1 = getPrice() * getAmount();
		jTextFieldNeuerVertragIntermediateResult1.setText(form.format(iResult1));
		// Calculate intermediate result 2
		iResult2 = iResult1;
		jTextFieldNeuerVertragIntermediateResult2.setText(form.format(iResult2));
		discount = getDiscount() * iResult2 / 100;
		jTextFieldNeuerVertragAngebotspreisOhneRabatt.setText(form.format(discount));
		// Calculate intermediate result 3
		iResult3 = iResult2 - discount;
		jTextFieldNeuerVertragIntermediateResult3.setText(form.format(iResult3));
		cashDiscount = getCashDiscount() * iResult3 / 100;
		jTextFieldNeuerVertragAngebotspreisOhneSkonto.setText(form.format(cashDiscount));
		offerPrice = iResult3 - cashDiscount;
		jTextFieldNeuerVertragAngebotspreis.setText(form.format(offerPrice));
		offerPriceWithMwST = offerPrice + (offerPrice * mwst / 100);
		jTextFieldNeuerVertragAngebotspreisMwST.setText(form.format(offerPriceWithMwST));

	}

	/**
	 * Method ladeKunden. Lädt alle Kunden aus der Datenbank.
	 */
	private void loadCustomer() {
		Collection kunden = null;
		try {
			kunden = dao.getKunden();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("ladeKunden()", e);
		}

		DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBoxKunde.getModel();
		model.removeAllElements();
		model.addElement("Bitte wählen:");

		// Verhindert NullPointerException bei einer leeren Liste
		if (kunden != null) {
			Iterator it = kunden.iterator();
			while (it.hasNext()) {
				Customer kunde = (Customer) it.next();
				//Merken des Nachnamen und Vornamen, um diese in die ComboBox einzutragen
				String merkeName = String.valueOf(kunde.getVorname()).concat(" ");
				merkeName = merkeName.concat(String.valueOf(kunde.getNachname()));
				model.addElement(merkeName);
				//kundeObjekt.put(String.valueOf(kunde.getId()), kunde);
				kundeObjekt.put(merkeName, kunde);
				//	kundenTabelle.put(kunde.getNachname(), String.valueOf(kunde.getId()));
			}
			jComboBoxKunde.setModel(model);
		}
	}

	/**
	 * Method ladeKundendaten. Lädt den Kundentyp, Zahlungsmoral und Ansprüche
	 * zum ausgewählten Kunden aus der Hashtable kundeObjekt.
	 */
	private void loadCustomerData() {

		//liefert listItem des selektierten Eintrags
		String listItem = String.valueOf(jComboBoxKunde.getSelectedItem());

		//sucht das ausgewählte KundenObjekt in Hashtabelle kundeObjekt
		Customer auswahlKunde = (Customer) kundeObjekt.get(listItem);

		if (auswahlKunde != null) {

			// sucht vorhandenen Vertraege zum Kunden
			Collection vertraege = null;
			int vertragszaehler = 0;

			try {
				vertraege = dao.getVertraege();
			} catch (WiSimDAOException e) {
				wiSimLogger.log("ladeKundendaten()", e);
			}

			if (vertraege != null) {
				Iterator it = vertraege.iterator();

				while (it.hasNext()) {
					Contract vertrag = (Contract) it.next();

					if (vertrag.getKundenId() == auswahlKunde.getId()) {
						vertragszaehler++;
					}
				}
			}

			//Gibt aus dem vorher ausgewähltem und dann gespeichertem Kundenobjekt die Daten zu Kundentyp, Zahlungsmoral und Ansprüche aus
			jTextFieldNeuerVertragKundentyp.setText(auswahlKunde.getKundentyp());
			jTextFieldNeuerVertragAnsprueche.setText(auswahlKunde.getAnspruch());
			jTextFieldNeuerVertragZahlungsmoral.setText(auswahlKunde.getZahlungsmoral());
			jTextFieldNeuerVertragAnzahlVertraege.setText(String.valueOf(vertragszaehler));
		} else {
			jTextFieldNeuerVertragKundentyp.setText("");
			jTextFieldNeuerVertragAnsprueche.setText("");
			jTextFieldNeuerVertragZahlungsmoral.setText("");
			jTextFieldNeuerVertragAnzahlVertraege.setText("");
		}
	}

	/**
	 * Method ladeArtikel. Lädt die Article aus der Datenbank.
	 */
	private void loadArticle() {
		Collection artikel = null;
		try {
			artikel = dao.getAlleArtikel();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("ladeArtikel()", e);
		}

		DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBoxArtikel.getModel();
		model.removeAllElements();
		model.addElement("Bitte wählen:");

		// Verhindert NullPointerException bei einer leeren Liste
		if (artikel != null) {
			Iterator it = artikel.iterator();
			while (it.hasNext()) {
				Article artikel2 = (Article) it.next();
				model.addElement(artikel2.getName());
				artikelTabelle.put(artikel2.getName(), String.valueOf(artikel2.getNr()));
				//speichert das Objekt zum ausgewählten Article in die Hashtable artikelObjekt
				artikelObjekt.put(String.valueOf(artikel2.getNr()), artikel2);
			}
			jComboBoxArtikel.setModel(model);
		}
	}

	/**
	 * Method ladeStueckpreis. Lädt von dem ausgewähltem Article den Stückpreis aus der Datenbank.
	 */
	private void loadPrice() {

		//liefert listItem des selektierten Eintrags
		String listItem = String.valueOf(jComboBoxArtikel.getSelectedIndex());

		//sucht das ausgewählte ArtikelObjekt in Hashtabelle artikelObjekt
		Article auswahlArtikel = (Article) artikelObjekt.get(listItem);

		if (auswahlArtikel != null) {
			//Gibt aus dem vorher ausgewähltem und dann gespeichertem Artikelobjekt den Stückpreis aus
			jTextFieldNeuerVertragStueckpreis.setText(form.format(auswahlArtikel.getStueckpreis()));
			calculate();
		} else {
			jTextFieldNeuerVertragStueckpreis.setText("");
			calculate();
		}
	}

	/**
	 * Method ladeMwSt. Ladet den Wert der Mwst aus der Datenbank.
	 */
	private void loadMwSt() {
		//MwSt-Satz bestimmen
		try {
			mwst = dao.getMwSt();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("ladeMwSt()", e);
		}
		jTextFieldMwst.setText(String.valueOf(mwst));
	}

	/** Überprüft alle Pflichtfelder auf Inhalt. Gibt eine Fehlemeldung
	   * an den Benutzer, falls ein oder mehrere Felder leer gelassen
	   * wurden.
	   * @return false: Es wurden nicht alle Felder gefüllt.
	   * true: Alle Pflichtfelder sind gefüllt.
	   */
	private boolean checkFields() {
		Collection pflichtfelder = new Vector();

		if (jComboBoxKunde.getSelectedIndex() == 0) {
			pflichtfelder.add("Kunde");
		}

		if (jComboBoxArtikel.getSelectedIndex() == 0) {
			pflichtfelder.add("Article");
		}

		if (jTextFieldNeuerVertragAbnahmemenge.getText().equals("")) {
			pflichtfelder.add("Abnahmemenge");
		}

		if (jTextFieldRabatt.getText().equals("")) {
			pflichtfelder.add("Rabatt");
		}

		if (jTextFieldSkonto.getText().equals("")) {
			pflichtfelder.add("Skonto");
		}

		if (jTextFieldSkontofristTage.getText().equals("")) {
			pflichtfelder.add("Skontofrist");
		}

		if (jTextFieldNeuerVertragTag.getText().equals("") || jTextFieldNeuerVertragMonat.getText().equals("") || jTextFieldNeuerVertragJahr.getText().equals("")) {
			pflichtfelder.add("Lieferdatum");
		}

		/*Wurde ein oder mehrere Pflichtfelder nicht ausgefüllt erscheint ein JOptionPane, dass dem
		 *Benutzer die fehlenden noch leeren Felder anzeigt*/
		if (!pflichtfelder.isEmpty()) {
			if (pflichtfelder.size() > 1)
				JOptionPane.showMessageDialog(this, "Folgende Felder müssen ausgefüllt werden: " + pflichtfelder.toString().substring(1, pflichtfelder.toString().length() - 1), "Fehler beim Anlegen des neuen Vertrages", JOptionPane.ERROR_MESSAGE);
			else
				JOptionPane.showMessageDialog(this, "Das folgende Feld muss ausgefüllt werden: " + pflichtfelder.toString().substring(1, pflichtfelder.toString().length() - 1), "Fehler beim Anlegen des neuen Vertrages", JOptionPane.ERROR_MESSAGE);

			return false;
		}
		return true;
	}

	/** Überprüft das eingegebene Lieferdatum
	   * @return Gibt das Lieferdatum als GregorianDate zurück. Oder NULL, wenn das
	   * Datum ungültig ist.
	   */
	private GregorianCalendar checkDate() {
		int lieferTag = Integer.parseInt(jTextFieldNeuerVertragTag.getText());
		int lieferMonat = Integer.parseInt(jTextFieldNeuerVertragMonat.getText()) - 1;
		int lieferJahr = Integer.parseInt(jTextFieldNeuerVertragJahr.getText());

		GregorianCalendar lieferDatum = new GregorianCalendar(lieferJahr, lieferMonat, lieferTag);

		if (lieferTag != lieferDatum.get(Calendar.DATE)) {
			JOptionPane.showMessageDialog(this, "Ungültiges Lieferdatum!", "Fehler", 0);
			return null;
		}

		if (lieferDatum.getTime().before(wiSimMainController.getActDate())) {
			JOptionPane.showMessageDialog(this, "Lieferdatum liegt in der Vergangenheit!", "Fehler", 0);
			return null;
		}
		return lieferDatum;
	}

	/** Löscht alle Felder und setzt alle Werte zurück. */
	private void clearFields() {
		jTextFieldNeuerVertragKundentyp.setText("");
		jTextFieldNeuerVertragAnsprueche.setText("");
		jTextFieldNeuerVertragZahlungsmoral.setText("");
		jTextFieldNeuerVertragAnzahlVertraege.setText("");
		jTextFieldNeuerVertragStueckpreis.setText("");
		jTextFieldNeuerVertragAbnahmemenge.setText("");
		jTextFieldSkonto.setText("");
		jTextFieldSkontofristTage.setText("");
		jTextFieldRabatt.setText("");
		jTextFieldNeuerVertragTag.setText("");
		jTextFieldNeuerVertragMonat.setText("");
		jTextFieldNeuerVertragJahr.setText("");
		jTextFieldNeuerVertragNettozahldatum.setText("");
		jTextFieldNeuerVertragIntermediateResult1.setText("");
		jTextFieldNeuerVertragIntermediateResult2.setText("");
		jTextFieldNeuerVertragIntermediateResult3.setText("");
		jTextFieldNeuerVertragAngebotspreisOhneRabatt.setText("");
		jTextFieldNeuerVertragAngebotspreisOhneSkonto.setText("");
		jTextFieldNeuerVertragAngebotspreisMwST.setText("");
		jTextFieldNeuerVertragAngebotspreis.setText("");

		jComboBoxArtikel.setSelectedIndex(0);
		jComboBoxKunde.setSelectedIndex(0);
	}

	/**
	 * Method speicherVertrag. Schreibt die Daten in die Datenbank.
	 */
	private void saveContract() {

		int i = 0;
		int j = 0;

		//Test der Pflichtfelder
		if (!checkFields()) {
			return;
		}

		//Validierung des Lieferdatums
		GregorianCalendar lieferDatum = checkDate();
		if (lieferDatum == null) {
			return;
		}
		java.sql.Date lieferDateSQL = new java.sql.Date(lieferDatum.getTimeInMillis());

		// Id's in ContractAccount und in Auftrag zählen

		Collection vertraege = null;
		Collection atrechnungen = null;

		try {
			vertraege = dao.getVertraege();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}
		// Verhindert NullPointerException bei einer leeren Liste
		if (vertraege != null) {
			Iterator it = vertraege.iterator();
			while (it.hasNext()) {
				it.next(); //dispensable?
				i++;
			}
		}

		try {
			atrechnungen = dao.getAuftragsrechnungen();
		} catch (WiSimDAOException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}

		if (atrechnungen != null) {
			Iterator it = atrechnungen.iterator();
			while (it.hasNext()) {
				it.next(); //dispensable?
				j++;
			}
		}

		//liefert listItem des selektierten Eintrags aus der ComboBox vom Kunden
		String listItem1 = String.valueOf(jComboBoxKunde.getSelectedItem());
		//sucht das ausgewählte KundenObjekt in Hashtabelle kundeObjekt
		Customer auswahlKunde = (Customer) kundeObjekt.get(listItem1);
		int kdId = auswahlKunde.getId();

		//liefert listItem des selektierten Eintrags aus der ComboBox vom Article
		String listItem2 = String.valueOf(jComboBoxArtikel.getSelectedIndex());
		//sucht das ausgewählte Artikelobjekt in Hashtabelle artikelObjekt
		Article auswahlArtikel = (Article) artikelObjekt.get(listItem2);
		int artId = auswahlArtikel.getNr();
		boolean zleingang = false;

		ContractAccount atr = new ContractAccount();
		// Auftragsrechnungsdaten vorbereiten
		atr.setNr(j + 1);
		try {
			atr.setBetrag(form.parse(jTextFieldNeuerVertragAngebotspreis.getText()).doubleValue());
		} catch (ParseException e) {
			wiSimLogger.log(Level.WARNING, "JPanelNeuerVertrag.speicherVertrag", e, false);
		}
		atr.setAuftragNr(i + 1);
		atr.setMwSt(mwst);
		atr.setzEingang(zleingang);

		try {
			dao.setAuftragsrechnung(atr);
		} catch (WiSimDAOException e) {
			wiSimLogger.log("speicherVertrag()", e);
		} catch (WiSimDAOWriteException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}

		Contract vertrag = new Contract();
		// Vertragsdaten vorbereiten
		vertrag.setVertragsId(i + 1);
		vertrag.setKundenId(kdId);
		vertrag.setLieferdatum(lieferDateSQL);
		vertrag.setRabatt(getDiscount());
		vertrag.setSkonto(getCashDiscount());
		vertrag.setSkontofrist(Long.parseLong(jTextFieldSkontofristTage.getText().toString()));
		vertrag.setVertragsdatum(new java.sql.Date(wiSimMainController.getActDate().getTime()));
		vertrag.setAuftragsrechnungsId(j + 1);

		try {
			dao.setNeuenVertrag(vertrag);
		} catch (WiSimDAOException e) {
			wiSimLogger.log("speicherVertrag()", e);
		} catch (WiSimDAOWriteException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}

		OrderItem atp = new OrderItem();
		//AuftragsPositionsdaten vorbereiten
		atp.setAtNr(i + 1);
		atp.setArtNr(artId);
		atp.setBestellmenge(Long.parseLong(jTextFieldNeuerVertragAbnahmemenge.getText().toString()));

		try {
			dao.setAuftragsPosition(atp);
		} catch (WiSimDAOWriteException e) {
			wiSimLogger.log("speicherVertrag()", e);
		}

		i = 0;
		j = 0;
		clearFields();
		loadCustomer();
		loadArticle();

		JOptionPane.showMessageDialog(this, "Der Vertrag wurde erfolgreich gespeichert.", "Vertrag", JOptionPane.INFORMATION_MESSAGE);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonNeuerVertragAbbrechen;
	private javax.swing.JButton jButtonNeuerVertragSpeichern;
	private javax.swing.JComboBox jComboBoxArtikel;
	private javax.swing.JComboBox jComboBoxKunde;
	private javax.swing.JLabel jLabelAngebotspreis;
	private javax.swing.JLabel jLabelArtikel;
	private javax.swing.JLabel jLabelEUR;
	private javax.swing.JLabel jLabelEUR1;
	private javax.swing.JLabel jLabelEUR2;
	private javax.swing.JLabel jLabelEUR3;
	private javax.swing.JLabel jLabelEUR4;
	private javax.swing.JLabel jLabelEUR5;
	private javax.swing.JLabel jLabelEUR6;
	private javax.swing.JLabel jLabelEUR7;
	private javax.swing.JLabel jLabelGleich;
	private javax.swing.JLabel jLabelGleich2;
	private javax.swing.JLabel jLabelGleich3;
	private javax.swing.JLabel jLabelKunde;
	private javax.swing.JLabel jLabelMinus;
	private javax.swing.JLabel jLabelMinus2;
	private javax.swing.JLabel jLabelMwst;
	private javax.swing.JLabel jLabelNeuerVertrag;
	private javax.swing.JLabel jLabelNeuerVertragAbnahmemenge;
	private javax.swing.JLabel jLabelNeuerVertragAnsprueche;
	private javax.swing.JLabel jLabelNeuerVertragAnzahlVertraege;
	private javax.swing.JLabel jLabelNeuerVertragKundenTyp;
	private javax.swing.JLabel jLabelNeuerVertragLieferdatum;
	private javax.swing.JLabel jLabelNeuerVertragNettozahldatum;
	private javax.swing.JLabel jLabelNeuerVertragZahlungsmoral;
	private javax.swing.JLabel jLabelProzent;
	private javax.swing.JLabel jLabelProzent1;
	private javax.swing.JLabel jLabelProzent2;
	private javax.swing.JLabel jLabelRabatt;
	private javax.swing.JLabel jLabelRabatt2;
	private javax.swing.JLabel jLabelSkonto;
	private javax.swing.JLabel jLabelSkonto2;
	private javax.swing.JLabel jLabelSkontofrist;
	private javax.swing.JLabel jLabelStueckpreis;
	private javax.swing.JLabel jLabelTage;
	private javax.swing.JLabel jLabelZwischensumme1;
	private javax.swing.JLabel jLabelZwischensumme2;
	private javax.swing.JLabel jLabelZwischensumme3;
	private javax.swing.JOptionPane jOptionAlert;
	private javax.swing.JOptionPane jOptionPaneConfirm;
	private javax.swing.JPanel jPanelAngebotspreis;
	private javax.swing.JPanel jPanelArtikelWaehlen;
	private javax.swing.JPanel jPanelBestelldatenEingeben;
	private javax.swing.JPanel jPanelKundeWaehlen;
	private javax.swing.JPanel jPanelKundendaten;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JTextField jTextFieldMwst;
	private javax.swing.JTextField jTextFieldNeuerVertragAbnahmemenge;
	private javax.swing.JTextField jTextFieldNeuerVertragAngebotspreis;
	private javax.swing.JTextField jTextFieldNeuerVertragAngebotspreisMwST;
	private javax.swing.JTextField jTextFieldNeuerVertragAngebotspreisOhneRabatt;
	private javax.swing.JTextField jTextFieldNeuerVertragAngebotspreisOhneSkonto;
	private javax.swing.JTextField jTextFieldNeuerVertragAnsprueche;
	private javax.swing.JTextField jTextFieldNeuerVertragAnzahlVertraege;
	private javax.swing.JTextField jTextFieldNeuerVertragIntermediateResult1;
	private javax.swing.JTextField jTextFieldNeuerVertragIntermediateResult2;
	private javax.swing.JTextField jTextFieldNeuerVertragIntermediateResult3;
	private javax.swing.JTextField jTextFieldNeuerVertragJahr;
	private javax.swing.JTextField jTextFieldNeuerVertragKundentyp;
	private javax.swing.JTextField jTextFieldNeuerVertragMonat;
	private javax.swing.JTextField jTextFieldNeuerVertragNettozahldatum;
	private javax.swing.JTextField jTextFieldNeuerVertragStueckpreis;
	private javax.swing.JTextField jTextFieldNeuerVertragTag;
	private javax.swing.JTextField jTextFieldNeuerVertragZahlungsmoral;
	private javax.swing.JTextField jTextFieldRabatt;
	private javax.swing.JTextField jTextFieldSkonto;
	private javax.swing.JTextField jTextFieldSkontofristTage;
	// End of variables declaration//GEN-END:variables
}