/*   ********************************************************************   **
**   Copyright notice                                                       **
**                                                                          **
**   (c) 2003 WiSim Development Team					                              **
**   http://wisim.sourceforge.net/   			                                  **
**                                                                          **
**   All rights reserved                                                    **
**                                                                          **
**   This script is part of the WiSim Business Game project. The WiSim      **
**   project is free software; you can redistribute it and/or modify        **
**   it under the terms of the GNU General Public License as published by   **
**   the Free Software Foundation; either version 2 of the License, or      **
**   (at your option) any later version.                                    **
**                                                                          **
**   The GNU General Public License can be found at                         **
**   http://www.gnu.org/copyleft/gpl.html.                                  **
**   A copy is found in the textfile GPL.txt and important notices to the   **
**   license from the team is found in the textfile LICENSE.txt distributed **
**   in these package.                                                      **
**                                                                          **
**   This copyright notice MUST APPEAR in all copies of the file!           **
**   ********************************************************************   */

/*
 * NewWiSimGUI.java
 *
 * Created on 23. Mai 2003, 14:36
 */

package net.sourceforge.wisim.controller;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.beans.PropertyVetoException;
import java.util.Hashtable;

import javax.swing.JInternalFrame;

/**
 *
 * @author  Kay Patzwald
 */
public class NewWiSimGUI extends javax.swing.JFrame {
	private Hashtable actions;
	private Point lastIFramePostion;

	/** Creates new form NewWiSimGUI */
	public NewWiSimGUI() {
		initComponents();
		initActions();
		initApplication();
	}

	private void initActions() {
		actions = new Hashtable();
		actions.put("NewCustomer", new JInternalFrameNewCustomer());
		actions.put("ModifyCustomer", new JInternalFrameModifyCustomer());
		actions.put("ViewCustomers", new JInternalFrameViewCustomers());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  private void initComponents() {//GEN-BEGIN:initComponents
    jToolBarMain = new javax.swing.JToolBar();
    jButton1 = new javax.swing.JButton();
    jDesktopPaneMain = new javax.swing.JDesktopPane();
    jLabelWiSim = new javax.swing.JLabel();
    jMenuBarWiSim = new javax.swing.JMenuBar();
    jMenuFile = new javax.swing.JMenu();
    jMenuVertrieb = new javax.swing.JMenu();
    jMenuCustomer = new javax.swing.JMenu();
    jMenuItemNewCustomer = new javax.swing.JMenuItem();
    jMenuItemModifyCustomer = new javax.swing.JMenuItem();
    jMenuItemViewCustomers = new javax.swing.JMenuItem();

    setTitle("WiSim");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });

    jToolBarMain.setFloatable(false);
    jToolBarMain.setRollover(true);
    jButton1.setText("Start");
    jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jToolBarMain.add(jButton1);

    getContentPane().add(jToolBarMain, java.awt.BorderLayout.NORTH);

    jLabelWiSim.setFont(new java.awt.Font("Dialog", 1, 80));
    jLabelWiSim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelWiSim.setText("WiSim 2.0");
    jLabelWiSim.setRequestFocusEnabled(false);
    jLabelWiSim.setBounds(270, 120, -1, -1);
    jDesktopPaneMain.add(jLabelWiSim, javax.swing.JLayeredPane.DEFAULT_LAYER);

    getContentPane().add(jDesktopPaneMain, java.awt.BorderLayout.CENTER);

    jMenuFile.setMnemonic('D');
    jMenuFile.setText("Datei");
    jMenuBarWiSim.add(jMenuFile);

    jMenuVertrieb.setMnemonic('V');
    jMenuVertrieb.setText("Vertrieb");
    jMenuCustomer.setText("Kunde");
    jMenuItemNewCustomer.setMnemonic('N');
    jMenuItemNewCustomer.setText("Neuer Kunde");
    jMenuItemNewCustomer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItemNewCustomerActionPerformed(evt);
      }
    });

    jMenuCustomer.add(jMenuItemNewCustomer);

    jMenuItemModifyCustomer.setMnemonic('b');
    jMenuItemModifyCustomer.setText("Kunde bearbeiten");
    jMenuItemModifyCustomer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItemModifyCustomerActionPerformed(evt);
      }
    });

    jMenuCustomer.add(jMenuItemModifyCustomer);

    jMenuItemViewCustomers.setMnemonic('u');
    jMenuItemViewCustomers.setText("Kunden\u00fcbersicht");
    jMenuItemViewCustomers.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItemViewCustomersActionPerformed(evt);
      }
    });

    jMenuCustomer.add(jMenuItemViewCustomers);

    jMenuVertrieb.add(jMenuCustomer);

    jMenuBarWiSim.add(jMenuVertrieb);

    setJMenuBar(jMenuBarWiSim);

    pack();
    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    java.awt.Dimension dialogSize = getSize();
    setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
  }//GEN-END:initComponents

	private void jMenuItemViewCustomersActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jMenuItemViewCustomersActionPerformed
		addInternalFrame("ViewCustomers");
	} //GEN-LAST:event_jMenuItemViewCustomersActionPerformed

	private void jMenuItemModifyCustomerActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jMenuItemModifyCustomerActionPerformed
		addInternalFrame("ModifyCustomer");
	} //GEN-LAST:event_jMenuItemModifyCustomerActionPerformed

	private void jMenuItemNewCustomerActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jMenuItemNewCustomerActionPerformed
		addInternalFrame("NewCustomer");
	} //GEN-LAST:event_jMenuItemNewCustomerActionPerformed

	/** Exit the Application */
	private void exitForm(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_exitForm
		System.exit(0);
	} //GEN-LAST:event_exitForm

	/*
	 * Sets the size of the application to maximum
	 */
	private void initApplication() {
		GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
		setSize(ge.getMaximumWindowBounds().width, ge.getMaximumWindowBounds().height);
		setLocation(0, 0);
		jDesktopPaneMain.setPreferredSize(new Dimension(getSize().width, getSize().height - jMenuBarWiSim.getHeight() - jToolBarMain.getHeight()));
	//jDesktopPaneMain.setMaximumSize(new Dimension(getSize().width, getSize().height - jMenuBarWiSim.getHeight() - jToolBarMain.getHeight()));
		jLabelWiSim.setBounds(0, 0, getSize().width, getSize().height - jMenuBarWiSim.getHeight() - jToolBarMain.getHeight());
		lastIFramePostion = new Point(-25, -25);
		jDesktopPaneMain.setPreferredSize(new Dimension(getSize().width, getSize().height - jMenuBarWiSim.getHeight() - jToolBarMain.getHeight()));
	}

	/*
	 * Adds a new Frame to the JDesktopPane
	 */
	private void addInternalFrame(String iFrame) {
		System.out.println(jDesktopPaneMain.getSize().width);
		JInternalFrame newIFrame = (JInternalFrame) actions.get(iFrame);
		if (newIFrame.isVisible()) {
			if (newIFrame.isIcon()) {
				if (newIFrame.isPreferredSizeSet()) {
					newIFrame.setSize(newIFrame.getPreferredSize());
					try {
						newIFrame.setIcon(false);
					} catch (PropertyVetoException e1) {
						System.err.println(e1.getMessage());
					}
				} else
					try {
						newIFrame.setMaximum(true);
					} catch (PropertyVetoException e) {
						System.err.println(e.getMessage());
					}
			}
			if (!newIFrame.isSelected()) {
				try {
					newIFrame.setSelected(true);
				} catch (PropertyVetoException e) {
					System.err.println(e.getMessage());
				}
			}

		} else {
			newIFrame.setVisible(true);
			jDesktopPaneMain.add(newIFrame);
			if (newIFrame.isPreferredSizeSet()) {
				newIFrame.setSize(newIFrame.getPreferredSize());

				if (newIFrame.getSize().width + lastIFramePostion.x + 25 > jDesktopPaneMain.getSize().width || newIFrame.getSize().height + lastIFramePostion.y + 25 > jDesktopPaneMain.getSize().height) {
					lastIFramePostion = new Point(-25, -25);
				}

				lastIFramePostion = new Point(lastIFramePostion.x + 25, lastIFramePostion.y + 25);
				if (newIFrame.getSize().width < jDesktopPaneMain.getSize().width && newIFrame.getSize().height < jDesktopPaneMain.getSize().height) {
					newIFrame.setLocation(lastIFramePostion.x, lastIFramePostion.y);
				} else {
					newIFrame.setSize(jDesktopPaneMain.getSize());
					try {
						newIFrame.setMaximum(true);
					} catch (PropertyVetoException e) {
						System.err.println(e.getMessage());
					}
				}
			} else {
				try {
					newIFrame.setMaximum(true);
				} catch (PropertyVetoException e) {
					System.err.println(e.getMessage());
				}
			}
			try {
				newIFrame.setSelected(true);
			} catch (PropertyVetoException e) {
				System.err.println(e.getMessage());
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		new NewWiSimGUI().show();
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JDesktopPane jDesktopPaneMain;
  private javax.swing.JLabel jLabelWiSim;
  private javax.swing.JMenuBar jMenuBarWiSim;
  private javax.swing.JMenu jMenuCustomer;
  private javax.swing.JMenu jMenuFile;
  private javax.swing.JMenuItem jMenuItemModifyCustomer;
  private javax.swing.JMenuItem jMenuItemNewCustomer;
  private javax.swing.JMenuItem jMenuItemViewCustomers;
  private javax.swing.JMenu jMenuVertrieb;
  private javax.swing.JToolBar jToolBarMain;
  // End of variables declaration//GEN-END:variables

}
