/*
 * WiSimMainController.java
 *
 * Created on 18. Januar 2003, 18:16
 */

package net.sourceforge.wisim.controller;

import net.sourceforge.wisim.dao.*;
import java.util.Hashtable;
import javax.swing.*;
import java.text.DateFormat;
import java.util.*;

/** Haupt-Klasse der gesamten Anwendung WiSim
 * @author Kay Patzwald
 */
public class WiSimMainController extends javax.swing.JFrame {
    
    private Hashtable actions;
    private WiSimDAO dao;
    private WiSimLogger wiSimLogger;
    private Date actDate;
    private GregorianCalendar actDateGC;
    private DateFormat df;
    private DateFormat justDate;
    
    /** Creates new form WiSimMainController */
    public WiSimMainController() {
        wiSimLogger = new WiSimLogger("wisimlog.xml");
        initDAO();
        initComponents();
        initActions();
        
        ButtonModel bm = jMenuDatum.getModel();
        bm.setEnabled(true);
        jMenuDatum.setModel(bm);

        com.incors.plaf.kunststoff.KunststoffLookAndFeel plaf = new com.incors.plaf.kunststoff.KunststoffLookAndFeel();

        try {
            UIManager.setLookAndFeel(plaf);
        } catch (Exception e) {}
        
        actDate = new Date(new GregorianCalendar(2003, 8, 1, 0, 0).getTimeInMillis());
	actDateGC = new GregorianCalendar();
	df = DateFormat.getDateTimeInstance(DateFormat.FULL, DateFormat.SHORT, Locale.GERMANY);
	justDate = DateFormat.getDateInstance(DateFormat.FULL, Locale.GERMANY);		
    }
    
    private void initActions() {
        actions = new Hashtable();
        actions.put("Bestellung", new JPanelBestellung(this));
        actions.put("Hilfe", new JPanelHilfe(this));
        actions.put("KundeBearbeiten", new JPanelKundeBearbeiten(this));
        actions.put("Lager",  new JPanelLager(this));
        actions.put("LieferantBearbeiten", new JPanelLieferantBearbeiten(this));
        actions.put("Lieferantenliste", new JPanelLieferantenliste(this));
        actions.put("NeuerKunde", new JPanelNeuerKunde(this));
        actions.put("Kundenuebersicht", new JPanelKundenUebersicht(this));
        actions.put("NeuerLieferant", new JPanelNeuerLieferant(this));
        actions.put("NeuerVertrag", new JPanelNeuerVertrag(this));
        actions.put("VertragEinsehen", new JPanelVertragEinsehen(this));
        actions.put("Options", new JPanelOptions(this));
        actions.put("EtatEinsehen", new JPanelEtatEinsehen(this));
        actions.put("SimulationStart", new JPanelSimulationStart(this));
        actions.put("Arbeitsplatzlager", new JPanelArbeitsplatzlager(this));
        actions.put("Zahlungseingang", new JPanelZahlungseingang(this));
    }
    
    private void initDAO() {
        dao = null;
        try {
            WiSimDAOFactory factory = new WiSimDAOFactory();
            dao = factory.getDAO();
        } catch (Throwable t) {        
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelStart = new javax.swing.JPanel();
        jLabelWillkommen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonVertrieb = new javax.swing.JButton();
        jButtonLager = new javax.swing.JButton();
        jButtonEinkauf = new javax.swing.JButton();
        jButtonProduktion = new javax.swing.JButton();
        jButtonRechnungswesen = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDatei = new javax.swing.JMenu();
        jMenuItemInfo = new javax.swing.JMenuItem();
        jMenuItemOptions = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItemBeenden = new javax.swing.JMenuItem();
        jMenuVertrieb = new javax.swing.JMenu();
        jMenuKunde = new javax.swing.JMenu();
        jMenuItemNeuerKunde = new javax.swing.JMenuItem();
        jMenuItemKundeEditieren = new javax.swing.JMenuItem();
        jMenuItemKundenuebersicht = new javax.swing.JMenuItem();
        jMenuVertrag = new javax.swing.JMenu();
        jMenuItemNeuerVertrag = new javax.swing.JMenuItem();
        jMenuItemVertragEinsehen = new javax.swing.JMenuItem();
        jMenuLager = new javax.swing.JMenu();
        jMenuItemLagerUebersicht = new javax.swing.JMenuItem();
        jMenuProduktion = new javax.swing.JMenu();
        jMenuItemArbeitsplatzlager = new javax.swing.JMenuItem();
        jMenuEinkauf = new javax.swing.JMenu();
        jMenuEtat = new javax.swing.JMenu();
        jMenuItemEtatEinsehen = new javax.swing.JMenuItem();
        jMenuItemBestellung = new javax.swing.JMenuItem();
        jMenuLieferanten = new javax.swing.JMenu();
        jMenuItemNeuerLieferant = new javax.swing.JMenuItem();
        jMenuItemLieferantenBearbeiten = new javax.swing.JMenuItem();
        jMenuItemLieferantenliste = new javax.swing.JMenuItem();
        jMenuRechnungswesen = new javax.swing.JMenu();
        jMenuItemZahlungseingang = new javax.swing.JMenuItem();
        jMenuSimulation = new javax.swing.JMenu();
        jMenuItemSimStart = new javax.swing.JMenuItem();
        jMenuSeperator = new javax.swing.JMenu();
        jMenuItemSimStart1 = new javax.swing.JMenuItem();
        jMenuDatum = new javax.swing.JMenu();

        jLabelWillkommen.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabelWillkommen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWillkommen.setText("Willkommen");
        jPanelStart.add(jLabelWillkommen);

        setTitle("Wirtschaftssimulation");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 40));
        jButtonVertrieb.setText("Vertrieb");
        jButtonVertrieb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVertriebActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonVertrieb);
        jButtonVertrieb.setBounds(270, 180, 140, 26);

        jButtonLager.setText("Lager");
        jButtonLager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLagerActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonLager);
        jButtonLager.setBounds(270, 220, 140, 26);

        jButtonEinkauf.setText("Einkauf");
        jButtonEinkauf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinkaufActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonEinkauf);
        jButtonEinkauf.setBounds(430, 180, 140, 26);

        jButtonProduktion.setText("Produktion");
        jButtonProduktion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProduktionActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonProduktion);
        jButtonProduktion.setBounds(430, 220, 140, 26);

        jButtonRechnungswesen.setText("Rechnungswesen");
        jButtonRechnungswesen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechnungswesenActionPerformed(evt);
            }
        });

        jPanel1.add(jButtonRechnungswesen);
        jButtonRechnungswesen.setBounds(350, 260, 140, 26);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuDatei.setMnemonic('D');
        jMenuDatei.setText("Datei");
        jMenuItemInfo.setMnemonic('I');
        jMenuItemInfo.setText("Info");
        jMenuItemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInfoActionPerformed(evt);
            }
        });

        jMenuDatei.add(jMenuItemInfo);

        jMenuItemOptions.setMnemonic('O');
        jMenuItemOptions.setText("Options");
        jMenuItemOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOptionsActionPerformed(evt);
            }
        });

        jMenuDatei.add(jMenuItemOptions);

        jMenuDatei.add(jSeparator2);

        jMenuItemBeenden.setMnemonic('B');
        jMenuItemBeenden.setText("Beenden");
        jMenuItemBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBeendenActionPerformed(evt);
            }
        });

        jMenuDatei.add(jMenuItemBeenden);

        jMenuBar1.add(jMenuDatei);

        jMenuVertrieb.setMnemonic('V');
        jMenuVertrieb.setText("Vertrieb");
        jMenuVertrieb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVertriebActionPerformed(evt);
            }
        });

        jMenuKunde.setMnemonic('K');
        jMenuKunde.setText("Kunde");
        jMenuItemNeuerKunde.setMnemonic('N');
        jMenuItemNeuerKunde.setText("Neu");
        jMenuItemNeuerKunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNeuerKundeActionPerformed(evt);
            }
        });

        jMenuKunde.add(jMenuItemNeuerKunde);

        jMenuItemKundeEditieren.setMnemonic('B');
        jMenuItemKundeEditieren.setText("Bearbeiten");
        jMenuItemKundeEditieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKundeEditierenActionPerformed(evt);
            }
        });

        jMenuKunde.add(jMenuItemKundeEditieren);

        jMenuItemKundenuebersicht.setMnemonic('u');
        jMenuItemKundenuebersicht.setText("Kundenuebersicht");
        jMenuItemKundenuebersicht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKundenuebersichtActionPerformed(evt);
            }
        });

        jMenuKunde.add(jMenuItemKundenuebersicht);

        jMenuVertrieb.add(jMenuKunde);

        jMenuVertrag.setMnemonic('V');
        jMenuVertrag.setText("Vertrag");
        jMenuVertrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVertragActionPerformed(evt);
            }
        });

        jMenuItemNeuerVertrag.setMnemonic('N');
        jMenuItemNeuerVertrag.setText("Neu");
        jMenuItemNeuerVertrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNeuerVertragActionPerformed(evt);
            }
        });

        jMenuVertrag.add(jMenuItemNeuerVertrag);

        jMenuItemVertragEinsehen.setMnemonic('E');
        jMenuItemVertragEinsehen.setText("Einsehen");
        jMenuItemVertragEinsehen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVertragEinsehenActionPerformed(evt);
            }
        });

        jMenuVertrag.add(jMenuItemVertragEinsehen);

        jMenuVertrieb.add(jMenuVertrag);

        jMenuBar1.add(jMenuVertrieb);

        jMenuLager.setMnemonic('L');
        jMenuLager.setText("Lager");
        jMenuItemLagerUebersicht.setMnemonic('L');
        jMenuItemLagerUebersicht.setText("Lager\u00fcbersicht");
        jMenuItemLagerUebersicht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLagerUebersichtActionPerformed(evt);
            }
        });

        jMenuLager.add(jMenuItemLagerUebersicht);

        jMenuBar1.add(jMenuLager);

        jMenuProduktion.setMnemonic('P');
        jMenuProduktion.setText("Produktion");
        jMenuItemArbeitsplatzlager.setMnemonic('A');
        jMenuItemArbeitsplatzlager.setText("Arbeitsplatzlager");
        jMenuItemArbeitsplatzlager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemArbeitsplatzlagerActionPerformed(evt);
            }
        });

        jMenuProduktion.add(jMenuItemArbeitsplatzlager);

        jMenuBar1.add(jMenuProduktion);

        jMenuEinkauf.setMnemonic('E');
        jMenuEinkauf.setText("Einkauf");
        jMenuEtat.setMnemonic('E');
        jMenuEtat.setText("Ersatzteil Auftrag");
        jMenuItemEtatEinsehen.setMnemonic('A');
        jMenuItemEtatEinsehen.setText("Auftr\u00e4ge einsehen");
        jMenuItemEtatEinsehen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEtatEinsehenActionPerformed(evt);
            }
        });

        jMenuEtat.add(jMenuItemEtatEinsehen);

        jMenuItemBestellung.setMnemonic('E');
        jMenuItemBestellung.setText("Ersatzteile bestellen");
        jMenuItemBestellung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBestellungActionPerformed(evt);
            }
        });

        jMenuEtat.add(jMenuItemBestellung);

        jMenuEinkauf.add(jMenuEtat);

        jMenuLieferanten.setMnemonic('L');
        jMenuLieferanten.setText("Lieferanten");
        jMenuLieferanten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLieferantenActionPerformed(evt);
            }
        });

        jMenuItemNeuerLieferant.setMnemonic('N');
        jMenuItemNeuerLieferant.setText("Neu");
        jMenuItemNeuerLieferant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNeuerLieferantActionPerformed(evt);
            }
        });

        jMenuLieferanten.add(jMenuItemNeuerLieferant);

        jMenuItemLieferantenBearbeiten.setMnemonic('B');
        jMenuItemLieferantenBearbeiten.setText("Bearbeiten");
        jMenuItemLieferantenBearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLieferantenBearbeitenActionPerformed(evt);
            }
        });

        jMenuLieferanten.add(jMenuItemLieferantenBearbeiten);

        jMenuItemLieferantenliste.setMnemonic('L');
        jMenuItemLieferantenliste.setText("Lieferantenliste");
        jMenuItemLieferantenliste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLieferantenlisteActionPerformed(evt);
            }
        });

        jMenuLieferanten.add(jMenuItemLieferantenliste);

        jMenuEinkauf.add(jMenuLieferanten);

        jMenuBar1.add(jMenuEinkauf);

        jMenuRechnungswesen.setMnemonic('R');
        jMenuRechnungswesen.setText("Rechnungswesen");
        jMenuItemZahlungseingang.setMnemonic('Z');
        jMenuItemZahlungseingang.setText("Zahlungseingang");
        jMenuItemZahlungseingang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZahlungseingangActionPerformed(evt);
            }
        });

        jMenuRechnungswesen.add(jMenuItemZahlungseingang);

        jMenuBar1.add(jMenuRechnungswesen);

        jMenuSimulation.setMnemonic('S');
        jMenuSimulation.setText("Simulation");
        jMenuItemSimStart.setMnemonic('S');
        jMenuItemSimStart.setText("Start / Stop");
        jMenuItemSimStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSimStartActionPerformed(evt);
            }
        });

        jMenuSimulation.add(jMenuItemSimStart);

        jMenuBar1.add(jMenuSimulation);

        jMenuSeperator.setPreferredSize(new java.awt.Dimension(100, 21));
        jMenuSeperator.setEnabled(false);
        jMenuItemSimStart1.setText("Start / Stop");
        jMenuSeperator.add(jMenuItemSimStart1);

        jMenuBar1.add(jMenuSeperator);

        jMenuDatum.setBorder(null);
        jMenuDatum.setText("Montag, 1. September 2003");
        jMenuDatum.setFont(new java.awt.Font("Dialog", 0, 14));
        jMenuDatum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuDatum.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenuDatum.setPreferredSize(new java.awt.Dimension(270, 15));
        jMenuDatum.setEnabled(false);
        jMenuBar1.add(jMenuDatum);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }//GEN-END:initComponents

    private void jMenuItemZahlungseingangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZahlungseingangActionPerformed
        changePanel("Zahlungseingang");
    }//GEN-LAST:event_jMenuItemZahlungseingangActionPerformed

    private void jMenuItemKundenuebersichtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKundenuebersichtActionPerformed
        changePanel("Kundenuebersicht");
    }//GEN-LAST:event_jMenuItemKundenuebersichtActionPerformed

    private void jMenuVertriebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVertriebActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenuVertriebActionPerformed

    private void jMenuVertragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVertragActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenuVertragActionPerformed

    private void jMenuItemArbeitsplatzlagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemArbeitsplatzlagerActionPerformed
        changePanel("Arbeitsplatzlager");
    }//GEN-LAST:event_jMenuItemArbeitsplatzlagerActionPerformed

    private void jMenuItemLieferantenlisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLieferantenlisteActionPerformed
        changePanel("Lieferantenliste");
    }//GEN-LAST:event_jMenuItemLieferantenlisteActionPerformed

    private void jMenuLieferantenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLieferantenActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenuLieferantenActionPerformed

    private void jMenuItemSimStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSimStartActionPerformed
        changePanel("SimulationStart");
    }//GEN-LAST:event_jMenuItemSimStartActionPerformed

    private void jMenuItemEtatEinsehenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEtatEinsehenActionPerformed
        changePanel("EtatEinsehen");
    }//GEN-LAST:event_jMenuItemEtatEinsehenActionPerformed

    private void jMenuItemOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOptionsActionPerformed
        changePanel("Options");
    }//GEN-LAST:event_jMenuItemOptionsActionPerformed

  private void jButtonRechnungswesenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechnungswesenActionPerformed
    disableButtons(jMenuRechnungswesen, "Rechnungswesen");
  }//GEN-LAST:event_jButtonRechnungswesenActionPerformed

  private void jButtonProduktionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProduktionActionPerformed
    disableButtons(jMenuProduktion, "Produktion");
  }//GEN-LAST:event_jButtonProduktionActionPerformed

  private void jButtonLagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLagerActionPerformed
    disableButtons(jMenuLager, "Lager");
  }//GEN-LAST:event_jButtonLagerActionPerformed

  private void jButtonEinkaufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinkaufActionPerformed
    disableButtons(jMenuEinkauf, "Einkauf");
  }//GEN-LAST:event_jButtonEinkaufActionPerformed

  private void jButtonVertriebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVertriebActionPerformed
    disableButtons(jMenuVertrieb, "Vertrieb");
  }//GEN-LAST:event_jButtonVertriebActionPerformed
  
    private void jMenuItemBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBeendenActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemBeendenActionPerformed
    
    private void jMenuItemLieferantenBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLieferantenBearbeitenActionPerformed
        changePanel("LieferantBearbeiten");
    }//GEN-LAST:event_jMenuItemLieferantenBearbeitenActionPerformed
    
    private void jMenuItemVertragEinsehenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVertragEinsehenActionPerformed
        changePanel("VertragEinsehen");
    }//GEN-LAST:event_jMenuItemVertragEinsehenActionPerformed
        
    private void jMenuItemNeuerLieferantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNeuerLieferantActionPerformed
        changePanel("NeuerLieferant");
    }//GEN-LAST:event_jMenuItemNeuerLieferantActionPerformed
    
    private void jMenuItemLagerUebersichtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLagerUebersichtActionPerformed
        changePanel("Lager");
    }//GEN-LAST:event_jMenuItemLagerUebersichtActionPerformed
    
    private void jMenuItemBestellungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBestellungActionPerformed
        changePanel("Bestellung");
    }//GEN-LAST:event_jMenuItemBestellungActionPerformed
    
    private void jMenuItemNeuerVertragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNeuerVertragActionPerformed
        changePanel("NeuerVertrag");
    }//GEN-LAST:event_jMenuItemNeuerVertragActionPerformed
    
    private void jMenuItemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInfoActionPerformed
        changePanel("Hilfe");
    }//GEN-LAST:event_jMenuItemInfoActionPerformed
    
    private void jMenuItemNeuerKundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNeuerKundeActionPerformed
        changePanel("NeuerKunde");
    }//GEN-LAST:event_jMenuItemNeuerKundeActionPerformed
    
    private void jMenuItemKundeEditierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKundeEditierenActionPerformed
        changePanel("KundeBearbeiten");
    }//GEN-LAST:event_jMenuItemKundeEditierenActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /** Wechselt die Panels
     * @param panel Neues Panel
     */    
    public void changePanel(String panel) {
        getContentPane().removeAll();
        
        //Update Plugable look and feel
        SwingUtilities.updateComponentTreeUI((JPanel)actions.get(panel));
        SwingUtilities.updateComponentTreeUI(jMenuBar1);
        
        getContentPane().add((JPanel)actions.get(panel), java.awt.BorderLayout.CENTER);
        getContentPane().validate();
        getContentPane().repaint();
    }
    
    /** Liefert ein WiSimDao-Objekt
     * @return WiSimDao
     */    
    public WiSimDAO getDAO()
    {
        return dao;
    }
    
    private void disableButtons(JMenu menuWahl, String wahl)
    {
      if (JOptionPane.showConfirmDialog(this, "Möchten Sie in den Bereich " + wahl + " wechseln?", "Bereichswahl", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0)
      {
        menuWahl.setEnabled(true);
        jButtonEinkauf.setEnabled(false);
        jButtonLager.setEnabled(false);
        jButtonProduktion.setEnabled(false);
        jButtonRechnungswesen.setEnabled(false);
        jButtonVertrieb.setEnabled(false);
      }
    }
    
    /** Liefert die Hashtable Actions
     * @return Hashtable
     */    
    public Hashtable getActions()
    {
    	return actions;
    }
    
    /** Liefert den Logger
     * @return WiSimLogger
     */    
    public WiSimLogger getWiSimLogger() {
        return wiSimLogger;
    }
    
    /** Main-Funktion der Anwendung
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new WiSimMainController().show();
    }
    
    /** Setzt das Datumsfeld dieses Panes zurück */
    public void resetTextFieldDate() {
        actDate = new Date(new GregorianCalendar(2003, 8, 1, 0, 0).getTimeInMillis());
        jMenuDatum.setText(justDate.format(actDate));
    }
    
    /** Erneuert die Datumsanzeige.
     * @param actDate
     */
    public void refreshTextFieldDate(java.util.Date actDate) {
        this.actDate = actDate;
        actDateGC.setTimeInMillis(actDate.getTime());
        jMenuDatum.setText(df.format(actDate));
    }
    
    
    /** Gibt die Simulationszeit zurück
     * @return Die Simulationszeit
     */    
    public Date getActDate() {
        return actDate;   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEinkauf;
    private javax.swing.JButton jButtonLager;
    private javax.swing.JButton jButtonProduktion;
    private javax.swing.JButton jButtonRechnungswesen;
    private javax.swing.JButton jButtonVertrieb;
    private javax.swing.JLabel jLabelWillkommen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDatei;
    private javax.swing.JMenu jMenuDatum;
    private javax.swing.JMenu jMenuEinkauf;
    private javax.swing.JMenu jMenuEtat;
    private javax.swing.JMenuItem jMenuItemArbeitsplatzlager;
    private javax.swing.JMenuItem jMenuItemBeenden;
    private javax.swing.JMenuItem jMenuItemBestellung;
    private javax.swing.JMenuItem jMenuItemEtatEinsehen;
    private javax.swing.JMenuItem jMenuItemInfo;
    private javax.swing.JMenuItem jMenuItemKundeEditieren;
    private javax.swing.JMenuItem jMenuItemKundenuebersicht;
    private javax.swing.JMenuItem jMenuItemLagerUebersicht;
    private javax.swing.JMenuItem jMenuItemLieferantenBearbeiten;
    private javax.swing.JMenuItem jMenuItemLieferantenliste;
    private javax.swing.JMenuItem jMenuItemNeuerKunde;
    private javax.swing.JMenuItem jMenuItemNeuerLieferant;
    private javax.swing.JMenuItem jMenuItemNeuerVertrag;
    private javax.swing.JMenuItem jMenuItemOptions;
    private javax.swing.JMenuItem jMenuItemSimStart;
    private javax.swing.JMenuItem jMenuItemSimStart1;
    private javax.swing.JMenuItem jMenuItemVertragEinsehen;
    private javax.swing.JMenuItem jMenuItemZahlungseingang;
    private javax.swing.JMenu jMenuKunde;
    private javax.swing.JMenu jMenuLager;
    private javax.swing.JMenu jMenuLieferanten;
    private javax.swing.JMenu jMenuProduktion;
    private javax.swing.JMenu jMenuRechnungswesen;
    private javax.swing.JMenu jMenuSeperator;
    private javax.swing.JMenu jMenuSimulation;
    private javax.swing.JMenu jMenuVertrag;
    private javax.swing.JMenu jMenuVertrieb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelStart;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
  
}

